// ===== Vocab AI 内置词库 =====
// 例句全部原创，不复制任何教材原文
// 结构: {id, word, phonetic, pos, cn, tip, exampleEn, exampleCn, scene, cat}
//   pos   词性: n./v./adj./adv./phr./prep. 等
//   scene 场景用法(可选): 某词在特定场景的特殊含义，无则留空
//   cat   分类: nce2/dev/tv 或自定义

const WORDS = [
  // ========== 新概念二 Lesson 1-5 生词 (cat: nce2) ==========
  {id:"nce009", word:"ripe", phonetic:"/raɪp/", pos:"adj.", cn:"成熟的（果实）", tip:"形容水果熟了。ripe banana 熟香蕉", exampleEn:"These apples are ripe and ready to eat.", exampleCn:"这些苹果熟了，可以吃了。", scene:"", cat:"nce2"},
  {id:"nce010", word:"weigh", phonetic:"/weɪ/", pos:"v.", cn:"称……的重量；重达", tip:"名词形式 weight（重量）", exampleEn:"Can you weigh this box for me?", exampleCn:"你能帮我称一下这个箱子吗？", scene:"", cat:"nce2"},
  {id:"nce011", word:"customer", phonetic:"/ˈkʌstəmər/", pos:"n.", cn:"顾客", tip:"区别于 client（客户/委托人）", exampleEn:"The shop was full of customers this morning.", exampleCn:"今天上午店里满是顾客。", scene:"", cat:"nce2"},
  {id:"nce015", word:"decide", phonetic:"/dɪˈsaɪd/", pos:"v.", cn:"决定", tip:"decide to do 决定做某事。名词 decision", exampleEn:"We decided to stay home tonight.", exampleCn:"我们决定今晚待在家里。", scene:"", cat:"nce2"},
  {id:"nce016", word:"lonely", phonetic:"/ˈloʊnli/", pos:"adj.", cn:"孤独的", tip:"注意：lonely 是孤独感，alone 只是独自一人", exampleEn:"He felt lonely in the new city.", exampleCn:"在新城市里他感到孤独。", scene:"", cat:"nce2"},
  {id:"nce018", word:"diary", phonetic:"/ˈdaɪəri/", pos:"n.", cn:"日记", tip:"keep a diary 记日记。别和 dairy（乳制品）混", exampleEn:"She writes in her diary every night.", exampleCn:"她每晚都写日记。", scene:"", cat:"nce2"},
  {id:"nce020", word:"capital", phonetic:"/ˈkæpɪtl/", pos:"n.", cn:"首都；资本；大写字母", tip:"一词多义，看语境", exampleEn:"Beijing is the capital of China.", exampleCn:"北京是中国的首都。", scene:"金融里指“资本/本金”；排版里指“大写字母”", cat:"nce2"},
  {id:"nce021", word:"exhibition", phonetic:"/ˌeksɪˈbɪʃn/", pos:"n.", cn:"展览；展览会", tip:"动词 exhibit（展出）", exampleEn:"We saw an art exhibition at the museum.", exampleCn:"我们在博物馆看了一场艺术展。", scene:"", cat:"nce2"},
  {id:"nce022", word:"latest", phonetic:"/ˈleɪtɪst/", pos:"adj.", cn:"最新的", tip:"late 的最高级之一，指时间最近的", exampleEn:"Have you read the latest news?", exampleCn:"你看最新消息了吗？", scene:"", cat:"nce2"},
  {id:"nce023", word:"fashion", phonetic:"/ˈfæʃn/", pos:"n.", cn:"时尚；流行", tip:"in fashion 流行的，out of fashion 过时的", exampleEn:"This style is back in fashion.", exampleCn:"这种风格又流行起来了。", scene:"", cat:"nce2"},
  {id:"nce024", word:"event", phonetic:"/ɪˈvent/", pos:"n.", cn:"事件；大事", tip:"编程里也指“事件”（点击、输入等）", exampleEn:"The wedding was a happy event.", exampleCn:"婚礼是件喜事。", scene:"编程里指“事件”，如点击、输入触发的 event", cat:"nce2"},

  // ========== 开发者高频英语 (cat: dev) ==========
  {id:"dev001", word:"error", phonetic:"/ˈerər/", pos:"n.", cn:"错误；报错", tip:"程序出问题时最常见的词", exampleEn:"The program stopped because of an error.", exampleCn:"程序因为一个错误停止了。", scene:"编程里指程序运行/语法的“报错”", cat:"dev"},
  {id:"dev002", word:"exception", phonetic:"/ɪkˈsepʃn/", pos:"n.", cn:"异常", tip:"程序运行时抛出的错误对象。throw / catch an exception", exampleEn:"The code threw an exception when the file was missing.", exampleCn:"文件缺失时代码抛出了异常。", scene:"编程里指运行时抛出的“异常”对象", cat:"dev"},
  {id:"dev003", word:"traceback", phonetic:"/ˈtreɪsbæk/", pos:"n.", cn:"回溯；错误追踪信息", tip:"Python 报错时打印的调用栈", exampleEn:"Read the traceback to find which line failed.", exampleCn:"看回溯信息找出哪一行出错了。", scene:"Python 报错时打印的调用栈信息", cat:"dev"},
  {id:"dev004", word:"debug", phonetic:"/ˌdiːˈbʌɡ/", pos:"v.", cn:"调试；排错", tip:"de（去除）+ bug（程序错误）", exampleEn:"I spent an hour debugging this function.", exampleCn:"我花了一小时调试这个函数。", scene:"编程里指“调试、找bug”", cat:"dev"},
  {id:"dev005", word:"syntax", phonetic:"/ˈsɪntæks/", pos:"n.", cn:"语法（代码）", tip:"syntax error 语法错误", exampleEn:"A missing colon caused a syntax error.", exampleCn:"少了个冒号导致语法错误。", scene:"编程里指代码的“语法”，syntax error 语法错误", cat:"dev"},
  {id:"dev006", word:"valid", phonetic:"/ˈvælɪd/", pos:"adj.", cn:"有效的；合法的", tip:"反义词 invalid。常见于输入校验", exampleEn:"Please enter a valid email address.", exampleCn:"请输入有效的邮箱地址。", scene:"编程里指数据/输入“有效、合法”", cat:"dev"},
  {id:"dev007", word:"run", phonetic:"/rʌn/", pos:"v.", cn:"运行（代码）", tip:"日常是“跑步”，技术里是“运行程序”", exampleEn:"Run the script to see the result.", exampleCn:"运行脚本看看结果。", scene:"编程里指“运行程序/脚本”，日常指“跑步”", cat:"dev"},
  {id:"dev008", word:"call", phonetic:"/kɔːl/", pos:"v.", cn:"调用（函数）", tip:"日常是“打电话”，技术里是“调用”", exampleEn:"This line calls the login function.", exampleCn:"这一行调用了登录函数。", scene:"编程里指“调用函数”，日常指“打电话”", cat:"dev"},
  {id:"dev009", word:"return", phonetic:"/rɪˈtɜːrn/", pos:"v.", cn:"返回（值）", tip:"函数把结果 return 出去", exampleEn:"The function returns a list of names.", exampleCn:"这个函数返回一个名字列表。", scene:"编程里指函数“返回值”，日常指“归还/返回”", cat:"dev"},
  {id:"dev010", word:"import", phonetic:"/ɪmˈpɔːrt/", pos:"v.", cn:"导入（模块）", tip:"把别的代码引进来用", exampleEn:"Import the math module before using it.", exampleCn:"使用前先导入 math 模块。", scene:"编程里指“导入模块”，日常/贸易里指“进口”", cat:"dev"},
  {id:"dev011", word:"deploy", phonetic:"/dɪˈplɔɪ/", pos:"v.", cn:"部署（上线）", tip:"把代码发布到服务器/线上", exampleEn:"We deploy the app every Friday.", exampleCn:"我们每周五部署应用。", scene:"编程里指把代码“部署”上线", cat:"dev"},
  {id:"dev012", word:"merge", phonetic:"/mɜːrdʒ/", pos:"v.", cn:"合并（分支/代码）", tip:"Git 里把两个分支合到一起", exampleEn:"Merge your branch into main when ready.", exampleCn:"准备好后把你的分支合并到 main。", scene:"Git 里指“合并分支”", cat:"dev"},
  {id:"dev013", word:"commit", phonetic:"/kəˈmɪt/", pos:"v./n.", cn:"提交（代码记录）", tip:"Git 里保存一次改动", exampleEn:"Write a clear message for each commit.", exampleCn:"每次提交都写清楚说明。", scene:"Git 里指一次“提交”记录", cat:"dev"},
  {id:"dev014", word:"branch", phonetic:"/bræntʃ/", pos:"n.", cn:"分支", tip:"从主线分出来独立开发", exampleEn:"Create a new branch for this feature.", exampleCn:"为这个功能新建一个分支。", scene:"Git 里指代码“分支”，日常指“树枝/分店”", cat:"dev"},
  {id:"dev015", word:"repository", phonetic:"/rɪˈpɑːzətɔːri/", pos:"n.", cn:"代码仓库", tip:"简称 repo。代码存放的地方", exampleEn:"Clone the repository to your computer.", exampleCn:"把仓库克隆到你的电脑。", scene:"编程里指“代码仓库”，简称 repo", cat:"dev"},
  {id:"dev016", word:"pull", phonetic:"/pʊl/", pos:"v.", cn:"拉取（远程代码）", tip:"把远程的更新拉到本地", exampleEn:"Pull the latest changes before you start.", exampleCn:"开始前先拉取最新改动。", scene:"Git 里指“拉取”远程更新，日常指“拉”", cat:"dev"},
  {id:"dev017", word:"push", phonetic:"/pʊʃ/", pos:"v.", cn:"推送（到远程）", tip:"把本地提交推到远程仓库", exampleEn:"Push your commits to the remote repository.", exampleCn:"把你的提交推送到远程仓库。", scene:"Git 里指“推送”到远程，日常指“推”", cat:"dev"},
  {id:"dev018", word:"request", phonetic:"/rɪˈkwest/", pos:"n./v.", cn:"请求", tip:"客户端向服务器发的请求", exampleEn:"The app sends a request to the server.", exampleCn:"应用向服务器发送一个请求。", scene:"网络里指客户端发的“请求”", cat:"dev"},
  {id:"dev019", word:"response", phonetic:"/rɪˈspɑːns/", pos:"n.", cn:"响应；回复", tip:"服务器返回的结果", exampleEn:"The server returned an empty response.", exampleCn:"服务器返回了空响应。", scene:"网络里指服务器的“响应”", cat:"dev"},
  {id:"dev020", word:"endpoint", phonetic:"/ˈendpɔɪnt/", pos:"n.", cn:"接口端点", tip:"API 的某个访问地址", exampleEn:"This endpoint returns user data.", exampleCn:"这个端点返回用户数据。", scene:"API 里指一个访问“端点”地址", cat:"dev"},
  {id:"dev021", word:"parse", phonetic:"/pɑːrs/", pos:"v.", cn:"解析", tip:"把文本/数据拆解成结构。parse JSON", exampleEn:"Parse the JSON before reading the values.", exampleCn:"读取数值前先解析 JSON。", scene:"编程里指“解析”文本/数据，如 parse JSON", cat:"dev"},
  {id:"dev022", word:"token", phonetic:"/ˈtoʊkən/", pos:"n.", cn:"令牌；词元", tip:"既指身份令牌，也指 LLM 的词元", exampleEn:"The API key is sent as an access token.", exampleCn:"API 密钥以访问令牌的形式发送。", scene:"安全里指身份“令牌”；大模型里指“词元”", cat:"dev"},
  {id:"dev023", word:"prompt", phonetic:"/prɑːmpt/", pos:"n.", cn:"提示词", tip:"给大模型的输入指令", exampleEn:"A clear prompt gives a better answer.", exampleCn:"清晰的提示词能得到更好的回答。", scene:"AI 里指给模型的“提示词”；命令行里指“提示符”", cat:"dev"},
  {id:"dev024", word:"model", phonetic:"/ˈmɑːdl/", pos:"n.", cn:"模型", tip:"指 AI 模型，如 Claude、GPT", exampleEn:"Choose a smaller model for fast replies.", exampleCn:"想要快速回复就选小一点的模型。", scene:"AI 里指“模型”，日常指“模特/模型”", cat:"dev"},
  {id:"dev025", word:"stream", phonetic:"/striːm/", pos:"v./n.", cn:"流式传输", tip:"逐字返回结果，而非一次性给", exampleEn:"The model streams the answer word by word.", exampleCn:"模型逐字流式返回答案。", scene:"编程里指“流式传输”，日常指“小溪/流”", cat:"dev"},
  {id:"dev026", word:"schema", phonetic:"/ˈskiːmə/", pos:"n.", cn:"结构定义；模式", tip:"规定数据长什么样的模板", exampleEn:"The tool needs a schema to know the inputs.", exampleCn:"工具需要一个结构定义来识别输入。", scene:"编程里指数据的“结构定义/模式”", cat:"dev"},

  // ========== 影视口语高频 (cat: tv) ==========
  {id:"tv001", word:"figure out", phonetic:"/ˈfɪɡjər aʊt/", pos:"phr.", cn:"弄明白；搞清楚", tip:"看剧最高频之一。= work out / understand", exampleEn:"I can't figure out why she's so upset.", exampleCn:"我搞不懂她为什么这么生气。", scene:"", cat:"tv"},
  {id:"tv002", word:"deal", phonetic:"/diːl/", pos:"n./v.", cn:"约定；交易；处理", tip:"It's a deal 就这么定了；deal with 处理", exampleEn:"Okay, it's a deal. See you at eight.", exampleCn:"好，说定了，八点见。", scene:"", cat:"tv"},
  {id:"tv003", word:"whatever", phonetic:"/wʌtˈevər/", pos:"pron./int.", cn:"随便；无所谓（语气）", tip:"口语里常带不耐烦/敷衍的味道", exampleEn:"Whatever, I don't really care anymore.", exampleCn:"随便吧，我已经懒得管了。", scene:"", cat:"tv"},
  {id:"tv004", word:"freak out", phonetic:"/friːk aʊt/", pos:"phr.", cn:"吓坏；抓狂", tip:"情绪失控、慌了。剧里超常见", exampleEn:"Don't freak out, but I lost your keys.", exampleCn:"你先别慌，我把你钥匙弄丢了。", scene:"", cat:"tv"},
  {id:"tv005", word:"awesome", phonetic:"/ˈɔːsəm/", pos:"adj.", cn:"太棒了；超赞", tip:"美剧口头禅，表示赞叹", exampleEn:"You finished it already? Awesome!", exampleCn:"你已经做完了？太棒了！", scene:"", cat:"tv"},
  {id:"tv006", word:"guess", phonetic:"/ɡes/", pos:"v.", cn:"猜；觉得（口语）", tip:"I guess 我觉得吧（不太确定的语气）", exampleEn:"I guess we could try that.", exampleCn:"我觉得我们可以试试那个吧。", scene:"", cat:"tv"},
  {id:"tv007", word:"mean", phonetic:"/miːn/", pos:"v./adj.", cn:"意思是；刻薄的", tip:"I mean… 我是说……（解释/改口）", exampleEn:"I mean, it's not a big deal.", exampleCn:"我是说，这没什么大不了的。", scene:"", cat:"tv"},
  {id:"tv008", word:"kidding", phonetic:"/ˈkɪdɪŋ/", pos:"v.", cn:"开玩笑", tip:"Are you kidding me? 你逗我呢？", exampleEn:"Relax, I'm just kidding.", exampleCn:"放松，我开玩笑的。", scene:"", cat:"tv"},
  {id:"tv009", word:"point", phonetic:"/pɔɪnt/", pos:"n.", cn:"重点；意义", tip:"What's the point? 有什么意义？That's the point 这就是重点", exampleEn:"What's the point of waiting here?", exampleCn:"在这儿等着有什么意义？", scene:"", cat:"tv"},
  {id:"tv010", word:"stuff", phonetic:"/stʌf/", pos:"n.", cn:"东西；玩意儿", tip:"泛指一堆东西，比 things 更随意", exampleEn:"Just put your stuff over there.", exampleCn:"把你的东西放那边就行。", scene:"", cat:"tv"},
  {id:"tv011", word:"hang out", phonetic:"/hæŋ aʊt/", pos:"phr.", cn:"一起玩；闲混", tip:"约朋友出去玩、消磨时间", exampleEn:"We used to hang out every weekend.", exampleCn:"我们以前每周末都一起玩。", scene:"", cat:"tv"},
  {id:"tv012", word:"awkward", phonetic:"/ˈɔːkwərd/", pos:"adj.", cn:"尴尬的", tip:"That's so awkward 太尴尬了", exampleEn:"There was an awkward silence at dinner.", exampleCn:"晚饭时有段尴尬的沉默。", scene:"", cat:"tv"},
  {id:"tv013", word:"creepy", phonetic:"/ˈkriːpi/", pos:"adj.", cn:"瘆人的；令人发毛的", tip:"形容人或场景让人不舒服", exampleEn:"That old house is really creepy at night.", exampleCn:"那栋老房子晚上真瘆人。", scene:"", cat:"tv"},
  {id:"tv014", word:"mess", phonetic:"/mes/", pos:"n.", cn:"一团糟；搞砸", tip:"a mess 乱七八糟；mess up 搞砸", exampleEn:"Sorry about the mess, I just moved in.", exampleCn:"抱歉这么乱，我刚搬进来。", scene:"", cat:"tv"},
  {id:"tv015", word:"weird", phonetic:"/wɪrd/", pos:"adj.", cn:"奇怪的；古怪的", tip:"比 strange 更口语、更高频", exampleEn:"It feels weird being back home.", exampleCn:"回到家感觉怪怪的。", scene:"", cat:"tv"},
  {id:"tv016", word:"totally", phonetic:"/ˈtoʊtəli/", pos:"adv.", cn:"完全；绝对（赞同）", tip:"Totally! 完全同意！", exampleEn:"You're totally right about that.", exampleCn:"这件事你说得完全对。", scene:"", cat:"tv"},
  {id:"tv017", word:"chill", phonetic:"/tʃɪl/", pos:"v./adj.", cn:"放松；冷静", tip:"chill out 放松点；也指“很酷/淡定”", exampleEn:"Just chill, everything will be fine.", exampleCn:"放轻松，一切都会好的。", scene:"", cat:"tv"},
  {id:"tv018", word:"gonna", phonetic:"/ˈɡɒnə/", pos:"phr.", cn:"将要（going to 口语缩写）", tip:"剧里几乎没人说 going to，都说 gonna", exampleEn:"I'm gonna grab some coffee.", exampleCn:"我要去买杯咖啡。", scene:"", cat:"tv"},
  {id:"tv019", word:"wanna", phonetic:"/ˈwɒnə/", pos:"phr.", cn:"想要（want to 口语缩写）", tip:"Do you wanna…? 你想不想……？", exampleEn:"Do you wanna come with us?", exampleCn:"你想跟我们一起去吗？", scene:"", cat:"tv"},
  {id:"tv020", word:"barely", phonetic:"/ˈberli/", pos:"adv.", cn:"几乎不；勉强", tip:"barely + 动词 = 差点没……", exampleEn:"I barely slept last night.", exampleCn:"我昨晚几乎没睡。", scene:"", cat:"tv"},
  {id:"tv021", word:"owe", phonetic:"/oʊ/", pos:"v.", cn:"欠（钱/人情）", tip:"I owe you one 我欠你个人情", exampleEn:"Thanks, I owe you one.", exampleCn:"谢了，我欠你个人情。", scene:"", cat:"tv"},
  {id:"tv022", word:"creep", phonetic:"/kriːp/", pos:"n./v.", cn:"讨厌鬼；慢慢移动", tip:"骂人时指“变态/讨厌的家伙”", exampleEn:"That guy is such a creep.", exampleCn:"那家伙真是个讨厌鬼。", scene:"", cat:"tv"},

  // ===== 科技开发增补 (cat: dev) =====
  // -- Python 核心实操 --
  {id:"dev027", word:"variable", phonetic:"/ˈveriəbl/", pos:"n.", cn:"变量", tip:"存数据的容器", exampleEn:"Store the result in a variable.", exampleCn:"把结果存进一个变量。", scene:"编程里指存值的“变量”", cat:"dev"},
  {id:"dev028", word:"function", phonetic:"/ˈfʌŋkʃn/", pos:"n.", cn:"函数；功能", tip:"def 定义函数", exampleEn:"This function returns the total.", exampleCn:"这个函数返回总和。", scene:"编程里指“函数”，数学里指“函数”，日常指“功能/作用”", cat:"dev"},
  {id:"dev029", word:"parameter", phonetic:"/pəˈræmɪtər/", pos:"n.", cn:"参数（形参）", tip:"函数定义里的占位变量", exampleEn:"This function takes two parameters.", exampleCn:"这个函数接收两个参数。", scene:"编程里指函数定义时的“形参”", cat:"dev"},
  {id:"dev030", word:"argument", phonetic:"/ˈɑːrɡjumənt/", pos:"n.", cn:"实参；论点", tip:"调用时实际传的值；日常指“争论”", exampleEn:"Pass the file name as an argument.", exampleCn:"把文件名作为实参传进去。", scene:"编程里指调用时传的“实参”；日常指“争论/论点”", cat:"dev"},
  {id:"dev031", word:"module", phonetic:"/ˈmɑːdʒuːl/", pos:"n.", cn:"模块", tip:"一个 .py 文件就是一个模块", exampleEn:"Import the os module first.", exampleCn:"先导入 os 模块。", scene:"编程里指可复用的“模块”", cat:"dev"},
  {id:"dev032", word:"package", phonetic:"/ˈpækɪdʒ/", pos:"n.", cn:"包；软件包", tip:"一组模块的集合；pip install 装包", exampleEn:"Install the package with pip.", exampleCn:"用 pip 安装这个包。", scene:"编程里指“代码包”；日常指“包裹”", cat:"dev"},
  {id:"dev033", word:"library", phonetic:"/ˈlaɪbreri/", pos:"n.", cn:"库；图书馆", tip:"现成的代码工具集，如 numpy", exampleEn:"Use a third-party library to save time.", exampleCn:"用第三方库省时间。", scene:"编程里指“代码库”；日常指“图书馆”", cat:"dev"},
  {id:"dev034", word:"keyword", phonetic:"/ˈkiːwɜːrd/", pos:"n.", cn:"关键字", tip:"语言保留的特殊词，如 if/for", exampleEn:"if and for are Python keywords.", exampleCn:"if 和 for 是 Python 关键字。", scene:"编程里指语言保留的“关键字”", cat:"dev"},
  {id:"dev035", word:"indent", phonetic:"/ɪnˈdent/", pos:"v.", cn:"缩进", tip:"Python 靠缩进分代码块", exampleEn:"Indent the code inside the loop.", exampleCn:"把循环里的代码缩进。", scene:"编程里指代码“缩进”（Python 很关键）", cat:"dev"},
  {id:"dev036", word:"comment", phonetic:"/ˈkɑːment/", pos:"n.", cn:"注释；评论", tip:"# 开头的说明，程序不执行", exampleEn:"Add a comment to explain this line.", exampleCn:"加个注释解释这一行。", scene:"编程里指代码“注释”；日常指“评论”", cat:"dev"},
  {id:"dev037", word:"string", phonetic:"/strɪŋ/", pos:"n.", cn:"字符串", tip:"引号包起来的文本", exampleEn:"Convert the number to a string.", exampleCn:"把数字转成字符串。", scene:"编程里指文本类型“字符串”；日常指“线/串”", cat:"dev"},
  {id:"dev038", word:"integer", phonetic:"/ˈɪntɪdʒər/", pos:"n.", cn:"整数", tip:"简称 int，没有小数点", exampleEn:"Age must be an integer.", exampleCn:"年龄必须是整数。", scene:"编程/数学里指“整数”", cat:"dev"},
  {id:"dev039", word:"boolean", phonetic:"/ˈbuːliən/", pos:"n.", cn:"布尔值", tip:"只有 True/False 两个值", exampleEn:"The check returns a boolean.", exampleCn:"这个检查返回一个布尔值。", scene:"编程里指真假“布尔值”", cat:"dev"},
  {id:"dev040", word:"list", phonetic:"/lɪst/", pos:"n.", cn:"列表", tip:"有序可变的元素集合 []", exampleEn:"Add the item to the list.", exampleCn:"把这个元素加进列表。", scene:"Python 里指有序的“列表”；日常指“清单”", cat:"dev"},
  {id:"dev041", word:"dictionary", phonetic:"/ˈdɪkʃəneri/", pos:"n.", cn:"字典", tip:"键值对集合 {}，简称 dict", exampleEn:"Store the settings in a dictionary.", exampleCn:"把配置存在字典里。", scene:"编程里指键值对“字典”；日常指“词典”", cat:"dev"},
  {id:"dev042", word:"loop", phonetic:"/luːp/", pos:"n.", cn:"循环", tip:"for / while 重复执行", exampleEn:"Use a loop to go through the list.", exampleCn:"用循环遍历列表。", scene:"编程里指“循环”", cat:"dev"},
  {id:"dev043", word:"iterate", phonetic:"/ˈɪtəreɪt/", pos:"v.", cn:"遍历；迭代", tip:"逐个处理集合里的元素", exampleEn:"Iterate over each row in the file.", exampleCn:"遍历文件里的每一行。", scene:"编程里指“遍历/迭代”", cat:"dev"},
  {id:"dev044", word:"recursion", phonetic:"/rɪˈkɜːrʒn/", pos:"n.", cn:"递归", tip:"函数调用自己", exampleEn:"This problem is easy to solve with recursion.", exampleCn:"这个问题用递归很好解。", scene:"编程里指函数自调用的“递归”", cat:"dev"},
  {id:"dev045", word:"lambda", phonetic:"/ˈlæmdə/", pos:"n.", cn:"匿名函数", tip:"一行写的小函数", exampleEn:"Use a lambda for a quick sort key.", exampleCn:"用 lambda 写个简易排序键。", scene:"编程里指“匿名函数”", cat:"dev"},
  {id:"dev046", word:"decorator", phonetic:"/ˈdekəreɪtər/", pos:"n.", cn:"装饰器", tip:"@ 开头，给函数加功能", exampleEn:"Add a decorator to log each call.", exampleCn:"加个装饰器记录每次调用。", scene:"Python 里指 @ 语法的“装饰器”", cat:"dev"},
  {id:"dev047", word:"instance", phonetic:"/ˈɪnstəns/", pos:"n.", cn:"实例；例子", tip:"类创建出的具体对象", exampleEn:"Create an instance of the class.", exampleCn:"创建这个类的一个实例。", scene:"编程里指类的“实例”；日常指“例子/情况”", cat:"dev"},
  {id:"dev048", word:"attribute", phonetic:"/ˈætrɪbjuːt/", pos:"n.", cn:"属性", tip:"对象身上的数据，用 . 访问", exampleEn:"Access the name attribute with a dot.", exampleCn:"用点号访问 name 属性。", scene:"编程里指对象的“属性”", cat:"dev"},
  {id:"dev049", word:"inherit", phonetic:"/ɪnˈherɪt/", pos:"v.", cn:"继承", tip:"子类拿到父类的能力", exampleEn:"The child class inherits from the parent.", exampleCn:"子类继承自父类。", scene:"面向对象里指类的“继承”；日常指“继承遗产”", cat:"dev"},
  {id:"dev050", word:"input", phonetic:"/ˈɪnpʊt/", pos:"n.", cn:"输入", tip:"用户/程序提供的数据", exampleEn:"Read the user input from the keyboard.", exampleCn:"从键盘读取用户输入。", scene:"编程里指“输入”", cat:"dev"},
  {id:"dev051", word:"output", phonetic:"/ˈaʊtpʊt/", pos:"n.", cn:"输出", tip:"程序产生的结果", exampleEn:"Print the output to the screen.", exampleCn:"把输出打印到屏幕。", scene:"编程里指“输出”", cat:"dev"},
  {id:"dev052", word:"print", phonetic:"/prɪnt/", pos:"v.", cn:"打印输出", tip:"日常是“打印”，编程是“输出到屏幕”", exampleEn:"Print the result to check it.", exampleCn:"打印结果检查一下。", scene:"编程里指“输出到控制台”；日常指“打印/印刷”", cat:"dev"},
  // -- 数据/文件 --
  {id:"dev053", word:"dataset", phonetic:"/ˈdeɪtəset/", pos:"n.", cn:"数据集", tip:"训练模型用的成批数据", exampleEn:"This dataset has 10,000 images.", exampleCn:"这个数据集有一万张图。", scene:"AI 里指训练用的“数据集”", cat:"dev"},
  {id:"dev055", word:"format", phonetic:"/ˈfɔːrmæt/", pos:"n./v.", cn:"格式；格式化", tip:"数据/文本的排列方式", exampleEn:"Save the file in JSON format.", exampleCn:"用 JSON 格式保存文件。", scene:"编程里指数据“格式”或“格式化”", cat:"dev"},
  {id:"dev056", word:"directory", phonetic:"/dəˈrektəri/", pos:"n.", cn:"目录；文件夹", tip:"= folder，命令行常说 dir", exampleEn:"Change to the project directory.", exampleCn:"切换到项目目录。", scene:"系统里指“目录/文件夹”", cat:"dev"},
  {id:"dev057", word:"path", phonetic:"/pæθ/", pos:"n.", cn:"路径", tip:"文件的位置地址", exampleEn:"Give the full path to the file.", exampleCn:"给出文件的完整路径。", scene:"系统里指文件“路径”；日常指“小路”", cat:"dev"},
  // -- 命令行 / Termux --
  {id:"dev058", word:"terminal", phonetic:"/ˈtɜːrmɪnl/", pos:"n.", cn:"终端", tip:"输入命令的黑窗口", exampleEn:"Open the terminal and type the command.", exampleCn:"打开终端输入命令。", scene:"系统里指命令行“终端”；日常指“航站楼/终点站”", cat:"dev"},
  {id:"dev059", word:"shell", phonetic:"/ʃel/", pos:"n.", cn:"shell（命令解释器）", tip:"bash/zsh 这类", exampleEn:"Run the script in the shell.", exampleCn:"在 shell 里运行脚本。", scene:"系统里指命令“解释器”；日常指“贝壳/外壳”", cat:"dev"},
  {id:"dev060", word:"command", phonetic:"/kəˈmænd/", pos:"n.", cn:"命令", tip:"敲给终端执行的指令", exampleEn:"Type the install command.", exampleCn:"输入安装命令。", scene:"系统里指“命令”；日常指“命令/指挥”", cat:"dev"},
  {id:"dev061", word:"script", phonetic:"/skrɪpt/", pos:"n.", cn:"脚本", tip:"一串可执行的命令/代码", exampleEn:"Write a shell script to automate it.", exampleCn:"写个 shell 脚本自动化它。", scene:"编程里指“脚本”；影视里指“剧本”", cat:"dev"},
  {id:"dev062", word:"install", phonetic:"/ɪnˈstɔːl/", pos:"v.", cn:"安装", tip:"pkg install / pip install", exampleEn:"Install the package before running.", exampleCn:"运行前先安装这个包。", scene:"软件里指“安装”", cat:"dev"},
  {id:"dev063", word:"upgrade", phonetic:"/ˌʌpˈɡreɪd/", pos:"v.", cn:"升级", tip:"升到更新版本", exampleEn:"Upgrade all packages weekly.", exampleCn:"每周升级所有的包。", scene:"软件里指“升级”", cat:"dev"},
  {id:"dev064", word:"dependency", phonetic:"/dɪˈpendənsi/", pos:"n.", cn:"依赖", tip:"这个项目运行需要的别的包", exampleEn:"Install all dependencies first.", exampleCn:"先安装所有依赖。", scene:"编程里指项目“依赖”", cat:"dev"},
  {id:"dev065", word:"permission", phonetic:"/pərˈmɪʃn/", pos:"n.", cn:"权限", tip:"chmod 改文件权限", exampleEn:"You don't have permission to edit this file.", exampleCn:"你没有权限编辑这个文件。", scene:"系统里指文件/操作“权限”", cat:"dev"},
  {id:"dev066", word:"process", phonetic:"/ˈprɑːses/", pos:"n.", cn:"进程；过程", tip:"正在运行的程序实例", exampleEn:"Kill the process that is stuck.", exampleCn:"杀掉卡住的那个进程。", scene:"系统里指运行中的“进程”；日常指“过程”", cat:"dev"},
  // -- 网络 / HTTP / API --
  {id:"dev067", word:"server", phonetic:"/ˈsɜːrvər/", pos:"n.", cn:"服务器", tip:"提供服务的远程电脑", exampleEn:"The server is down right now.", exampleCn:"服务器现在挂了。", scene:"网络里指“服务器”", cat:"dev"},
  {id:"dev068", word:"client", phonetic:"/ˈklaɪənt/", pos:"n.", cn:"客户端", tip:"向服务器请求的一方", exampleEn:"The client sends a request to the server.", exampleCn:"客户端向服务器发请求。", scene:"网络里指“客户端”；商务里指“客户”", cat:"dev"},
  {id:"dev069", word:"connect", phonetic:"/kəˈnekt/", pos:"v.", cn:"连接", tip:"建立网络/设备连接", exampleEn:"Connect to the WiFi first.", exampleCn:"先连上 WiFi。", scene:"网络里指“连接”", cat:"dev"},
  {id:"dev070", word:"timeout", phonetic:"/ˈtaɪmaʊt/", pos:"n.", cn:"超时", tip:"等太久没响应就超时", exampleEn:"The request failed with a timeout.", exampleCn:"请求因超时失败了。", scene:"网络里指请求“超时”", cat:"dev"},
  {id:"dev071", word:"header", phonetic:"/ˈhedər/", pos:"n.", cn:"请求头；头部", tip:"HTTP 请求附带的元信息", exampleEn:"Add the API key in the header.", exampleCn:"把 API 密钥加在请求头里。", scene:"HTTP 里指“请求头”", cat:"dev"},
  {id:"dev072", word:"payload", phonetic:"/ˈpeɪloʊd/", pos:"n.", cn:"负载；数据体", tip:"请求/响应里真正传的数据", exampleEn:"Send the data as a JSON payload.", exampleCn:"把数据作为 JSON 负载发送。", scene:"网络里指传输的“数据体”", cat:"dev"},
  {id:"dev073", word:"status", phonetic:"/ˈsteɪtəs/", pos:"n.", cn:"状态", tip:"HTTP 状态码如 200/404", exampleEn:"Check the status code of the response.", exampleCn:"检查响应的状态码。", scene:"网络里指“状态（码）”；日常指“身份/状况”", cat:"dev"},
  {id:"dev074", word:"cache", phonetic:"/kæʃ/", pos:"n.", cn:"缓存", tip:"临时存起来加速的数据", exampleEn:"Clear the cache and try again.", exampleCn:"清缓存再试一次。", scene:"计算机里指“缓存”", cat:"dev"},
  // -- Git 补充 --
  {id:"dev075", word:"clone", phonetic:"/kloʊn/", pos:"v.", cn:"克隆（仓库）", tip:"把远程仓库整个拷到本地", exampleEn:"Clone the repo to start working.", exampleCn:"克隆仓库开始干活。", scene:"Git 里指“克隆仓库”；生物里指“克隆”", cat:"dev"},
  {id:"dev076", word:"conflict", phonetic:"/ˈkɑːnflɪkt/", pos:"n.", cn:"冲突", tip:"合并时两边改了同一处", exampleEn:"Resolve the merge conflict first.", exampleCn:"先解决合并冲突。", scene:"Git 里指“合并冲突”；日常指“冲突/矛盾”", cat:"dev"},
  {id:"dev077", word:"stage", phonetic:"/steɪdʒ/", pos:"v.", cn:"暂存（git add）", tip:"git add 把改动放进暂存区", exampleEn:"Stage your changes before committing.", exampleCn:"提交前先暂存改动。", scene:"Git 里指“暂存”；日常指“舞台/阶段”", cat:"dev"},
  // -- AI / LLM 补充 --
  {id:"dev078", word:"train", phonetic:"/treɪn/", pos:"v.", cn:"训练（模型）", tip:"喂数据让模型学习", exampleEn:"Train the model on the dataset.", exampleCn:"在数据集上训练模型。", scene:"AI 里指“训练模型”；日常指“火车/训练”", cat:"dev"},
  {id:"dev079", word:"inference", phonetic:"/ˈɪnfərəns/", pos:"n.", cn:"推理（模型出结果）", tip:"用训练好的模型做预测", exampleEn:"Inference is fast on this GPU.", exampleCn:"这块 GPU 上推理很快。", scene:"AI 里指模型“推理”；日常指“推断”", cat:"dev"},
  {id:"dev080", word:"embedding", phonetic:"/ɪmˈbedɪŋ/", pos:"n.", cn:"嵌入向量", tip:"把文本转成数字向量", exampleEn:"Store the embeddings in a vector database.", exampleCn:"把嵌入向量存进向量数据库。", scene:"AI 里指文本的“嵌入向量”", cat:"dev"},
  {id:"dev081", word:"fine-tune", phonetic:"/ˌfaɪnˈtuːn/", pos:"v.", cn:"微调", tip:"在已有模型上小幅再训练", exampleEn:"Fine-tune the model on your own data.", exampleCn:"用你自己的数据微调模型。", scene:"AI 里指模型“微调”", cat:"dev"},
  {id:"dev082", word:"hallucination", phonetic:"/həˌluːsɪˈneɪʃn/", pos:"n.", cn:"幻觉（模型瞎编）", tip:"模型一本正经胡说", exampleEn:"Watch out for hallucinations in the answer.", exampleCn:"小心回答里的幻觉。", scene:"AI 里指模型“幻觉/瞎编”；医学里指“幻觉”", cat:"dev"},
  {id:"dev083", word:"latency", phonetic:"/ˈleɪtənsi/", pos:"n.", cn:"延迟", tip:"从请求到响应的耗时", exampleEn:"Lower latency means faster replies.", exampleCn:"延迟越低回复越快。", scene:"网络/AI 里指响应“延迟”", cat:"dev"},
  {id:"dev084", word:"benchmark", phonetic:"/ˈbentʃmɑːrk/", pos:"n.", cn:"基准测试", tip:"衡量性能的标准测试", exampleEn:"This model tops the benchmark.", exampleCn:"这个模型在基准测试里居首。", scene:"技术里指“基准测试”；商业里指“标杆”", cat:"dev"},
  {id:"dev085", word:"retrieval", phonetic:"/rɪˈtriːvl/", pos:"n.", cn:"检索", tip:"RAG 里从知识库找资料", exampleEn:"Retrieval brings in relevant documents.", exampleCn:"检索会拉进相关文档。", scene:"AI 里指 RAG 的“检索”", cat:"dev"},
  // -- 报错 / 调试补充 --
  {id:"dev086", word:"warning", phonetic:"/ˈwɔːrnɪŋ/", pos:"n.", cn:"警告", tip:"不致命但要注意的提示", exampleEn:"The code runs but shows a warning.", exampleCn:"代码能跑但有个警告。", scene:"编程里指“警告”（比 error 轻）", cat:"dev"},
  {id:"dev087", word:"crash", phonetic:"/kræʃ/", pos:"v.", cn:"崩溃", tip:"程序意外退出", exampleEn:"The app crashes on startup.", exampleCn:"应用一启动就崩溃。", scene:"软件里指程序“崩溃”；日常指“撞车/坠毁”", cat:"dev"},
  {id:"dev088", word:"freeze", phonetic:"/friːz/", pos:"v.", cn:"卡死；冻结", tip:"程序无响应卡住", exampleEn:"The screen froze for a few seconds.", exampleCn:"屏幕卡死了几秒。", scene:"软件里指界面“卡死”；日常指“结冰/冻结”", cat:"dev"},
  {id:"dev089", word:"overflow", phonetic:"/ˈoʊvərfloʊ/", pos:"n.", cn:"溢出", tip:"超出容量，如栈溢出", exampleEn:"Too much recursion causes a stack overflow.", exampleCn:"递归太深导致栈溢出。", scene:"编程里指数据/栈“溢出”", cat:"dev"},
  {id:"dev090", word:"deprecated", phonetic:"/ˈdeprəkeɪtɪd/", pos:"adj.", cn:"已弃用的", tip:"还能用但不推荐、将移除", exampleEn:"This function is deprecated, use the new one.", exampleCn:"这个函数已弃用，用新的。", scene:"编程里指 API“已弃用”", cat:"dev"},
  {id:"dev091", word:"override", phonetic:"/ˌoʊvərˈraɪd/", pos:"v.", cn:"重写；覆盖", tip:"子类重新定义父类方法", exampleEn:"Override this method in the subclass.", exampleCn:"在子类里重写这个方法。", scene:"编程里指方法“重写/覆盖”", cat:"dev"},
  {id:"dev092", word:"default", phonetic:"/dɪˈfɔːlt/", pos:"n./adj.", cn:"默认（值）", tip:"不指定时用的预设值", exampleEn:"The default value is zero.", exampleCn:"默认值是零。", scene:"编程里指“默认值”；金融里指“违约”", cat:"dev"},
  {id:"dev093", word:"async", phonetic:"/ˈeɪsɪŋk/", pos:"adj.", cn:"异步的", tip:"不等结果继续往下走", exampleEn:"Use an async function for network calls.", exampleCn:"网络调用用异步函数。", scene:"编程里指“异步”", cat:"dev"},
  {id:"dev094", word:"queue", phonetic:"/kjuː/", pos:"n.", cn:"队列", tip:"先进先出的排队结构", exampleEn:"Add the task to the queue.", exampleCn:"把任务加进队列。", scene:"编程里指“队列”；英式日常指“排队”", cat:"dev"},
  {id:"dev095", word:"thread", phonetic:"/θred/", pos:"n.", cn:"线程", tip:"程序里并发执行的单元", exampleEn:"Run the download on a separate thread.", exampleCn:"在单独的线程上跑下载。", scene:"编程里指“线程”；日常指“线/话题串”", cat:"dev"},
  {id:"dev096", word:"environment", phonetic:"/ɪnˈvaɪrənmənt/", pos:"n.", cn:"环境", tip:"虚拟环境 / 环境变量", exampleEn:"Activate the virtual environment first.", exampleCn:"先激活虚拟环境。", scene:"编程里指运行“环境”；日常指“环境/自然环境”", cat:"dev"},
  {id:"dev097", word:"config", phonetic:"/kənˈfɪɡ/", pos:"n.", cn:"配置", tip:"configuration 缩写，设置项", exampleEn:"Edit the config file to change the port.", exampleCn:"改配置文件来换端口。", scene:"编程里指“配置”", cat:"dev"},
  {id:"dev098", word:"log", phonetic:"/lɔːɡ/", pos:"n.", cn:"日志", tip:"程序记录的运行信息", exampleEn:"Check the logs to find the bug.", exampleCn:"看日志找 bug。", scene:"编程里指运行“日志”；日常指“原木/记录”", cat:"dev"},
  {id:"dev099", word:"backup", phonetic:"/ˈbækʌp/", pos:"n.", cn:"备份", tip:"防丢失的副本", exampleEn:"Make a backup before you delete it.", exampleCn:"删之前先做个备份。", scene:"通用：数据“备份”", cat:"dev"},
  {id:"dev100", word:"version", phonetic:"/ˈvɜːrʒn/", pos:"n.", cn:"版本", tip:"v1.0 这种", exampleEn:"Update to the latest version.", exampleCn:"更新到最新版本。", scene:"软件里指“版本”", cat:"dev"},

  // ===== 影视口语增补 (cat: tv) =====
  // -- 短语动词 --
  {id:"tv023", word:"come on", phonetic:"/kʌm ɑːn/", pos:"phr.", cn:"拜托；快点；得了吧", tip:"语气词，催促或不信", exampleEn:"Come on, we're going to be late!", exampleCn:"快点，我们要迟到了！", scene:"", cat:"tv"},
  {id:"tv024", word:"hold on", phonetic:"/hoʊld ɑːn/", pos:"phr.", cn:"等一下；坚持住", tip:"打电话/让人稍等", exampleEn:"Hold on, I'll be right back.", exampleCn:"等一下，我马上回来。", scene:"", cat:"tv"},
  {id:"tv025", word:"calm down", phonetic:"/kɑːm daʊn/", pos:"phr.", cn:"冷静；平静下来", tip:"安抚别人常用", exampleEn:"Calm down and tell me what happened.", exampleCn:"冷静点，告诉我怎么了。", scene:"", cat:"tv"},
  {id:"tv026", word:"shut up", phonetic:"/ʃʌt ʌp/", pos:"phr.", cn:"闭嘴；不会吧", tip:"也可表惊讶“不会吧”", exampleEn:"Shut up, no way that happened!", exampleCn:"不会吧，真发生了？！", scene:"", cat:"tv"},
  {id:"tv027", word:"give up", phonetic:"/ɡɪv ʌp/", pos:"phr.", cn:"放弃", tip:"don't give up 别放弃", exampleEn:"Don't give up so easily.", exampleCn:"别这么轻易放弃。", scene:"", cat:"tv"},
  {id:"tv028", word:"show up", phonetic:"/ʃoʊ ʌp/", pos:"phr.", cn:"露面；出现", tip:"= turn up", exampleEn:"He didn't show up at the party.", exampleCn:"他没来参加派对。", scene:"", cat:"tv"},
  {id:"tv029", word:"work out", phonetic:"/wɜːrk aʊt/", pos:"phr.", cn:"解决；锻炼；成功", tip:"一词多义，看语境", exampleEn:"Don't worry, it'll work out.", exampleCn:"别担心，会成的。", scene:"健身里指“锻炼”；日常指“解决/搞定/成功”", cat:"tv"},
  {id:"tv030", word:"check out", phonetic:"/tʃek aʊt/", pos:"phr.", cn:"看看；退房", tip:"Check it out! 快看！", exampleEn:"Check out this new song.", exampleCn:"听听这首新歌。", scene:"酒店里指“退房”；日常指“看看/查看”", cat:"tv"},
  {id:"tv031", word:"hang on", phonetic:"/hæŋ ɑːn/", pos:"phr.", cn:"等等；抓紧", tip:"= hold on", exampleEn:"Hang on, I'm almost done.", exampleCn:"等等，我快好了。", scene:"", cat:"tv"},
  {id:"tv032", word:"get over", phonetic:"/ɡet ˈoʊvər/", pos:"phr.", cn:"克服；走出（情伤）", tip:"get over someone 忘掉某人", exampleEn:"It took her months to get over it.", exampleCn:"她花了几个月才走出来。", scene:"", cat:"tv"},
  {id:"tv033", word:"run into", phonetic:"/rʌn ˈɪntuː/", pos:"phr.", cn:"偶遇；撞见", tip:"= bump into", exampleEn:"I ran into an old friend today.", exampleCn:"我今天偶遇一个老朋友。", scene:"", cat:"tv"},
  {id:"tv034", word:"make it", phonetic:"/meɪk ɪt/", pos:"phr.", cn:"赶上；成功；出席", tip:"语境很活", exampleEn:"Sorry, I can't make it tonight.", exampleCn:"抱歉，我今晚来不了。", scene:"", cat:"tv"},
  {id:"tv035", word:"pull off", phonetic:"/pʊl ɔːf/", pos:"phr.", cn:"成功做成（难事）", tip:"完成了别人觉得难的事", exampleEn:"I can't believe you pulled it off!", exampleCn:"真不敢相信你做成了！", scene:"", cat:"tv"},
  {id:"tv036", word:"back off", phonetic:"/bæk ɔːf/", pos:"phr.", cn:"退后；别逼了", tip:"让人别管/别靠近", exampleEn:"Back off, this is none of your business.", exampleCn:"退后，这不关你事。", scene:"", cat:"tv"},
  {id:"tv037", word:"settle down", phonetic:"/ˈsetl daʊn/", pos:"phr.", cn:"安定下来；冷静", tip:"成家/平静下来", exampleEn:"It's time to settle down and relax.", exampleCn:"该安定下来放松了。", scene:"", cat:"tv"},
  {id:"tv038", word:"throw up", phonetic:"/θroʊ ʌp/", pos:"phr.", cn:"呕吐", tip:"= vomit，口语常用", exampleEn:"I feel like I'm going to throw up.", exampleCn:"我感觉要吐了。", scene:"", cat:"tv"},
  // -- 情绪 / 评价 --
  {id:"tv039", word:"upset", phonetic:"/ʌpˈset/", pos:"adj.", cn:"难过；心烦的", tip:"比 sad 更强的烦乱", exampleEn:"She was really upset about the news.", exampleCn:"她对那消息很难过。", scene:"", cat:"tv"},
  {id:"tv040", word:"annoying", phonetic:"/əˈnɔɪɪŋ/", pos:"adj.", cn:"烦人的", tip:"形容惹人厌的人或事", exampleEn:"That noise is so annoying.", exampleCn:"那噪音太烦人了。", scene:"", cat:"tv"},
  {id:"tv041", word:"ridiculous", phonetic:"/rɪˈdɪkjələs/", pos:"adj.", cn:"荒谬的；可笑的", tip:"This is ridiculous! 太离谱了", exampleEn:"That price is ridiculous.", exampleCn:"那价格太离谱了。", scene:"", cat:"tv"},
  {id:"tv042", word:"gorgeous", phonetic:"/ˈɡɔːrdʒəs/", pos:"adj.", cn:"美极了；超好看", tip:"夸人/景物漂亮", exampleEn:"You look gorgeous tonight.", exampleCn:"你今晚美极了。", scene:"", cat:"tv"},
  {id:"tv043", word:"jerk", phonetic:"/dʒɜːrk/", pos:"n.", cn:"混蛋；讨厌鬼", tip:"骂人，比 creep 轻", exampleEn:"Stop being such a jerk.", exampleCn:"别这么混蛋。", scene:"", cat:"tv"},
  {id:"tv044", word:"loser", phonetic:"/ˈluːzər/", pos:"n.", cn:"废物；失败者", tip:"骂人没出息", exampleEn:"Don't call yourself a loser.", exampleCn:"别说自己是废物。", scene:"", cat:"tv"},
  {id:"tv045", word:"nuts", phonetic:"/nʌts/", pos:"adj.", cn:"疯了；着迷", tip:"go nuts 抓狂；be nuts about 痴迷", exampleEn:"Are you nuts? That's dangerous!", exampleCn:"你疯了吗？那很危险！", scene:"", cat:"tv"},
  {id:"tv046", word:"broke", phonetic:"/broʊk/", pos:"adj.", cn:"没钱了；破产的", tip:"I'm broke 我穷得叮当响", exampleEn:"I can't go out, I'm broke.", exampleCn:"我不能出去，没钱了。", scene:"", cat:"tv"},
  {id:"tv047", word:"starving", phonetic:"/ˈstɑːrvɪŋ/", pos:"adj.", cn:"饿坏了", tip:"夸张说很饿", exampleEn:"Let's eat, I'm starving.", exampleCn:"吃饭吧，我饿坏了。", scene:"", cat:"tv"},
  {id:"tv048", word:"exhausted", phonetic:"/ɪɡˈzɔːstɪd/", pos:"adj.", cn:"累垮了", tip:"比 tired 更强", exampleEn:"I'm exhausted after the trip.", exampleCn:"旅行后我累垮了。", scene:"", cat:"tv"},
  // -- 日常对话高频 --
  {id:"tv049", word:"seriously", phonetic:"/ˈsɪriəsli/", pos:"adv.", cn:"认真地；真的假的", tip:"Seriously? 真的假的？", exampleEn:"Seriously, you have to try this.", exampleCn:"说真的，你得试试这个。", scene:"", cat:"tv"},
  {id:"tv050", word:"honestly", phonetic:"/ˈɑːnəstli/", pos:"adv.", cn:"老实说", tip:"开头缓冲，引出真心话", exampleEn:"Honestly, I don't care.", exampleCn:"老实说，我不在乎。", scene:"", cat:"tv"},
  {id:"tv051", word:"basically", phonetic:"/ˈbeɪsɪkli/", pos:"adv.", cn:"基本上；说白了", tip:"总结/简化时用", exampleEn:"Basically, we have no choice.", exampleCn:"说白了，我们没得选。", scene:"", cat:"tv"},
  {id:"tv052", word:"anyway", phonetic:"/ˈeniweɪ/", pos:"adv.", cn:"不管怎样；反正", tip:"转换话题或下结论", exampleEn:"Anyway, let's move on.", exampleCn:"不管怎样，我们继续吧。", scene:"", cat:"tv"},
  {id:"tv053", word:"actually", phonetic:"/ˈæktʃuəli/", pos:"adv.", cn:"其实；实际上", tip:"纠正或补充", exampleEn:"Actually, that's not true.", exampleCn:"其实那不是真的。", scene:"", cat:"tv"},
  {id:"tv054", word:"probably", phonetic:"/ˈprɑːbəbli/", pos:"adv.", cn:"大概；很可能", tip:"不太确定的推测", exampleEn:"He's probably still asleep.", exampleCn:"他大概还在睡。", scene:"", cat:"tv"},
  {id:"tv055", word:"definitely", phonetic:"/ˈdefɪnətli/", pos:"adv.", cn:"绝对；肯定", tip:"强烈肯定", exampleEn:"I will definitely be there.", exampleCn:"我肯定会到。", scene:"", cat:"tv"},
  {id:"tv056", word:"supposed to", phonetic:"/səˈpoʊzd tuː/", pos:"phr.", cn:"应该；本应", tip:"be supposed to do 理应做", exampleEn:"You're supposed to knock first.", exampleCn:"你应该先敲门的。", scene:"", cat:"tv"},
  {id:"tv057", word:"no big deal", phonetic:"/noʊ bɪɡ diːl/", pos:"phr.", cn:"没什么大不了", tip:"安慰/谦虚", exampleEn:"It's no big deal, don't worry.", exampleCn:"没什么大不了的，别担心。", scene:"", cat:"tv"},
  {id:"tv058", word:"come up with", phonetic:"/kʌm ʌp wɪð/", pos:"phr.", cn:"想出（主意）", tip:"想出办法/点子", exampleEn:"She came up with a great idea.", exampleCn:"她想出个好主意。", scene:"", cat:"tv"},
  {id:"tv059", word:"by the way", phonetic:"/baɪ ðə weɪ/", pos:"phr.", cn:"顺便说；对了", tip:"缩写 BTW，转话题", exampleEn:"By the way, did you call her?", exampleCn:"对了，你给她打电话了吗？", scene:"", cat:"tv"},
  {id:"tv060", word:"or something", phonetic:"/ɔːr ˈsʌmθɪŋ/", pos:"phr.", cn:"……之类的", tip:"句尾，表示不确定", exampleEn:"He's a doctor or something.", exampleCn:"他是医生还是什么的。", scene:"", cat:"tv"},
  {id:"tv061", word:"kind of", phonetic:"/kaɪnd əv/", pos:"phr.", cn:"有点；算是", tip:"读快成 kinda，软化语气", exampleEn:"I'm kind of tired today.", exampleCn:"我今天有点累。", scene:"", cat:"tv"},
  {id:"tv062", word:"a bit", phonetic:"/ə bɪt/", pos:"phr.", cn:"一点点", tip:"= a little", exampleEn:"Can you speak a bit slower?", exampleCn:"你能说慢一点吗？", scene:"", cat:"tv"},
  {id:"tv063", word:"for real", phonetic:"/fɔːr riːl/", pos:"phr.", cn:"真的；当真", tip:"For real? 真的假的？", exampleEn:"Are you for real right now?", exampleCn:"你现在是认真的吗？", scene:"", cat:"tv"},
  {id:"tv064", word:"no way", phonetic:"/noʊ weɪ/", pos:"phr.", cn:"不可能；没门", tip:"惊讶或拒绝", exampleEn:"No way, that's amazing!", exampleCn:"不会吧，太棒了！", scene:"", cat:"tv"},
  {id:"tv065", word:"my bad", phonetic:"/maɪ bæd/", pos:"phr.", cn:"我的错", tip:"轻松道歉，= my fault", exampleEn:"Oh, my bad, I forgot.", exampleCn:"哦，我的错，我忘了。", scene:"", cat:"tv"},
  {id:"tv066", word:"never mind", phonetic:"/ˈnevər maɪnd/", pos:"phr.", cn:"算了；别在意", tip:"放下话题", exampleEn:"Never mind, it's not important.", exampleCn:"算了，不重要。", scene:"", cat:"tv"},
  {id:"tv067", word:"what's up", phonetic:"/wʌts ʌp/", pos:"phr.", cn:"怎么了；最近咋样", tip:"打招呼或问出什么事", exampleEn:"Hey, what's up with you today?", exampleCn:"嘿，你今天怎么了？", scene:"", cat:"tv"},
  {id:"tv068", word:"hang in there", phonetic:"/hæŋ ɪn ðer/", pos:"phr.", cn:"撑住；挺住", tip:"鼓励别人坚持", exampleEn:"Hang in there, it gets better.", exampleCn:"挺住，会好起来的。", scene:"", cat:"tv"},
  {id:"tv069", word:"keep up", phonetic:"/kiːp ʌp/", pos:"phr.", cn:"跟上；保持", tip:"keep up with 跟上进度", exampleEn:"You're doing great, keep it up!", exampleCn:"你做得很好，继续保持！", scene:"", cat:"tv"},
  {id:"tv070", word:"figure", phonetic:"/ˈfɪɡjər/", pos:"v./n.", cn:"认为；身材；数字", tip:"I figure 我觉得；nice figure 身材好", exampleEn:"I figure we should leave now.", exampleCn:"我觉得我们该走了。", scene:"", cat:"tv"},
  {id:"tv071", word:"grab", phonetic:"/ɡræb/", pos:"v.", cn:"抓；随便弄（吃的）", tip:"grab a coffee 随便喝杯咖啡", exampleEn:"Let's grab some lunch.", exampleCn:"我们随便吃个午饭吧。", scene:"", cat:"tv"},
  {id:"tv072", word:"mess up", phonetic:"/mes ʌp/", pos:"phr.", cn:"搞砸", tip:"= screw up", exampleEn:"I really messed up this time.", exampleCn:"这次我真搞砸了。", scene:"", cat:"tv"},
  {id:"tv073", word:"freak", phonetic:"/friːk/", pos:"n.", cn:"怪人；狂热者", tip:"control freak 控制狂", exampleEn:"He's a bit of a neat freak.", exampleCn:"他有点洁癖。", scene:"", cat:"tv"},
  {id:"tv074", word:"creep out", phonetic:"/kriːp aʊt/", pos:"phr.", cn:"让人发毛", tip:"You're creeping me out 你吓到我了", exampleEn:"That clown really creeps me out.", exampleCn:"那小丑真让我发毛。", scene:"", cat:"tv"},
  {id:"tv075", word:"big deal", phonetic:"/bɪɡ diːl/", pos:"phr.", cn:"大事；了不起", tip:"反讽时=没什么了不起", exampleEn:"So what? Big deal.", exampleCn:"那又怎样？有什么了不起。", scene:"", cat:"tv"},
  {id:"tv076", word:"get it", phonetic:"/ɡet ɪt/", pos:"phr.", cn:"懂了；明白", tip:"I get it 我懂了", exampleEn:"Okay, I get it now.", exampleCn:"好，我现在懂了。", scene:"", cat:"tv"},
  {id:"tv077", word:"knock it off", phonetic:"/nɑːk ɪt ɔːf/", pos:"phr.", cn:"住手；别闹了", tip:"让人停止烦人行为", exampleEn:"Knock it off, you two!", exampleCn:"你俩别闹了！", scene:"", cat:"tv"},
  {id:"tv078", word:"good for you", phonetic:"/ɡʊd fɔːr juː/", pos:"phr.", cn:"真为你高兴", tip:"也可反讽", exampleEn:"You got the job? Good for you!", exampleCn:"你拿到工作了？真为你高兴！", scene:"", cat:"tv"},
  {id:"tv079", word:"take it easy", phonetic:"/teɪk ɪt ˈiːzi/", pos:"phr.", cn:"放轻松；慢慢来", tip:"也用作告别“保重”", exampleEn:"Take it easy, we have time.", exampleCn:"放轻松，我们有时间。", scene:"", cat:"tv"},
  {id:"tv080", word:"sort of", phonetic:"/sɔːrt əv/", pos:"phr.", cn:"有点；算是吧", tip:"= kind of，软化", exampleEn:"I sort of like him.", exampleCn:"我算是有点喜欢他。", scene:"", cat:"tv"},

  // ===== 日常生活 (cat: life) =====
  // -- 食 --
  {id:"life001", word:"grocery", phonetic:"/ˈɡroʊsəri/", pos:"n.", cn:"食品杂货", tip:"grocery store 杂货店", exampleEn:"I need to buy some groceries.", exampleCn:"我得买点食品杂货。", scene:"", cat:"life"},
  {id:"life002", word:"recipe", phonetic:"/ˈresəpi/", pos:"n.", cn:"食谱；菜谱", tip:"别读成 re-cipe", exampleEn:"This recipe is really easy.", exampleCn:"这个食谱很简单。", scene:"", cat:"life"},
  {id:"life003", word:"ingredient", phonetic:"/ɪnˈɡriːdiənt/", pos:"n.", cn:"原料；食材", tip:"做菜要的东西", exampleEn:"Mix all the ingredients together.", exampleCn:"把所有食材混在一起。", scene:"", cat:"life"},
  {id:"life004", word:"leftover", phonetic:"/ˈleftoʊvər/", pos:"n.", cn:"剩饭剩菜", tip:"常用复数 leftovers", exampleEn:"We had leftovers for dinner.", exampleCn:"我们晚饭吃的剩菜。", scene:"", cat:"life"},
  {id:"life005", word:"takeout", phonetic:"/ˈteɪkaʊt/", pos:"n.", cn:"外卖", tip:"美式 takeout，英式 takeaway", exampleEn:"Let's order takeout tonight.", exampleCn:"今晚点外卖吧。", scene:"", cat:"life"},
  {id:"life006", word:"snack", phonetic:"/snæk/", pos:"n.", cn:"零食；点心", tip:"正餐之外吃的", exampleEn:"Grab a snack if you're hungry.", exampleCn:"饿了就拿点零食。", scene:"", cat:"life"},
  {id:"life007", word:"spicy", phonetic:"/ˈspaɪsi/", pos:"adj.", cn:"辣的", tip:"形容辣味", exampleEn:"This soup is too spicy for me.", exampleCn:"这汤对我太辣了。", scene:"", cat:"life"},
  {id:"life008", word:"thirsty", phonetic:"/ˈθɜːrsti/", pos:"adj.", cn:"渴的", tip:"hungry 饿 / thirsty 渴", exampleEn:"I'm thirsty, can I have some water?", exampleCn:"我渴了，能喝点水吗？", scene:"", cat:"life"},
  // -- 衣 --
  {id:"life009", word:"outfit", phonetic:"/ˈaʊtfɪt/", pos:"n.", cn:"一身行头；穿搭", tip:"整套搭配", exampleEn:"I love your outfit today.", exampleCn:"我喜欢你今天的穿搭。", scene:"", cat:"life"},
  {id:"life010", word:"laundry", phonetic:"/ˈlɔːndri/", pos:"n.", cn:"要洗的衣物；洗衣", tip:"do the laundry 洗衣服", exampleEn:"I have to do the laundry today.", exampleCn:"我今天得洗衣服。", scene:"", cat:"life"},
  {id:"life011", word:"fit", phonetic:"/fɪt/", pos:"v.", cn:"合身；适合", tip:"These jeans fit well 这裤子合身", exampleEn:"This shirt doesn't fit me.", exampleCn:"这件衬衫我穿不合身。", scene:"", cat:"life"},
  {id:"life012", word:"brand", phonetic:"/brænd/", pos:"n.", cn:"品牌", tip:"name brand 名牌", exampleEn:"What brand are these shoes?", exampleCn:"这鞋什么牌子的？", scene:"", cat:"life"},
  // -- 住 --
  {id:"life013", word:"rent", phonetic:"/rent/", pos:"n./v.", cn:"租金；租", tip:"pay the rent 付房租", exampleEn:"The rent is due next week.", exampleCn:"房租下周到期。", scene:"", cat:"life"},
  {id:"life014", word:"landlord", phonetic:"/ˈlændlɔːrd/", pos:"n.", cn:"房东", tip:"女房东 landlady", exampleEn:"My landlord raised the rent again.", exampleCn:"我房东又涨房租了。", scene:"", cat:"life"},
  {id:"life015", word:"furniture", phonetic:"/ˈfɜːrnɪtʃər/", pos:"n.", cn:"家具", tip:"不可数，没有复数", exampleEn:"We need to buy some furniture.", exampleCn:"我们得买些家具。", scene:"", cat:"life"},
  {id:"life016", word:"chore", phonetic:"/tʃɔːr/", pos:"n.", cn:"家务杂活", tip:"household chores 家务", exampleEn:"Doing chores takes all weekend.", exampleCn:"做家务占了整个周末。", scene:"", cat:"life"},
  {id:"life017", word:"trash", phonetic:"/træʃ/", pos:"n.", cn:"垃圾", tip:"take out the trash 倒垃圾", exampleEn:"Can you take out the trash?", exampleCn:"你能去倒垃圾吗？", scene:"", cat:"life"},
  {id:"life018", word:"plug", phonetic:"/plʌɡ/", pos:"n./v.", cn:"插头；插上", tip:"plug in 插电", exampleEn:"Plug in your phone to charge it.", exampleCn:"把手机插上充电。", scene:"", cat:"life"},
  {id:"life019", word:"leak", phonetic:"/liːk/", pos:"v./n.", cn:"漏；泄漏", tip:"水管漏水/信息泄露", exampleEn:"The faucet is leaking again.", exampleCn:"水龙头又漏水了。", scene:"信息安全里也指数据“泄漏”", cat:"life"},
  // -- 行 / 出门 --
  {id:"life020", word:"commute", phonetic:"/kəˈmjuːt/", pos:"n./v.", cn:"通勤", tip:"上下班路程", exampleEn:"My commute takes an hour.", exampleCn:"我通勤要一小时。", scene:"", cat:"life"},
  {id:"life021", word:"traffic", phonetic:"/ˈtræfɪk/", pos:"n.", cn:"交通；车流", tip:"heavy traffic 堵车", exampleEn:"The traffic is terrible today.", exampleCn:"今天堵得厉害。", scene:"", cat:"life"},
  {id:"life022", word:"subway", phonetic:"/ˈsʌbweɪ/", pos:"n.", cn:"地铁", tip:"美式 subway，英式 underground/tube", exampleEn:"Take the subway, it's faster.", exampleCn:"坐地铁吧，更快。", scene:"", cat:"life"},
  {id:"life023", word:"fare", phonetic:"/fer/", pos:"n.", cn:"车费；票价", tip:"交通费用", exampleEn:"The bus fare went up.", exampleCn:"公交车费涨了。", scene:"", cat:"life"},
  {id:"life024", word:"detour", phonetic:"/ˈdiːtʊr/", pos:"n.", cn:"绕路", tip:"take a detour 绕道", exampleEn:"We took a detour around the construction.", exampleCn:"我们绕开施工区走了。", scene:"", cat:"life"},
  {id:"life025", word:"parking", phonetic:"/ˈpɑːrkɪŋ/", pos:"n.", cn:"停车（位）", tip:"parking lot 停车场", exampleEn:"Parking is hard to find downtown.", exampleCn:"市中心很难找停车位。", scene:"", cat:"life"},
  // -- 购物 / 钱 --
  {id:"life026", word:"receipt", phonetic:"/rɪˈsiːt/", pos:"n.", cn:"收据；小票", tip:"p 不发音", exampleEn:"Keep the receipt in case you return it.", exampleCn:"留好小票以防退货。", scene:"", cat:"life"},
  {id:"life027", word:"refund", phonetic:"/ˈriːfʌnd/", pos:"n./v.", cn:"退款", tip:"get a refund 拿到退款", exampleEn:"I'd like a refund, please.", exampleCn:"我想退款，谢谢。", scene:"", cat:"life"},
  {id:"life028", word:"discount", phonetic:"/ˈdɪskaʊnt/", pos:"n.", cn:"折扣", tip:"on discount 打折中", exampleEn:"Is there any discount on this?", exampleCn:"这个有折扣吗？", scene:"", cat:"life"},
  {id:"life029", word:"afford", phonetic:"/əˈfɔːrd/", pos:"v.", cn:"负担得起", tip:"can't afford 买不起", exampleEn:"I can't afford a new car.", exampleCn:"我买不起新车。", scene:"", cat:"life"},
  {id:"life030", word:"budget", phonetic:"/ˈbʌdʒɪt/", pos:"n.", cn:"预算", tip:"on a budget 手头紧", exampleEn:"We're on a tight budget this month.", exampleCn:"我们这个月预算很紧。", scene:"", cat:"life"},
  {id:"life031", word:"cash", phonetic:"/kæʃ/", pos:"n.", cn:"现金", tip:"pay in cash 付现金", exampleEn:"Do you take cash or card?", exampleCn:"你们收现金还是卡？", scene:"", cat:"life"},
  {id:"life032", word:"bill", phonetic:"/bɪl/", pos:"n.", cn:"账单；钞票", tip:"电费水费等账单", exampleEn:"I forgot to pay the electricity bill.", exampleCn:"我忘付电费了。", scene:"", cat:"life"},
  // -- 社交 / 关系 --
  {id:"life033", word:"roommate", phonetic:"/ˈruːmmeɪt/", pos:"n.", cn:"室友", tip:"合租/同宿舍", exampleEn:"My roommate is really tidy.", exampleCn:"我室友很爱干净。", scene:"", cat:"life"},
  {id:"life034", word:"neighbor", phonetic:"/ˈneɪbər/", pos:"n.", cn:"邻居", tip:"英式拼 neighbour", exampleEn:"Our neighbors are very friendly.", exampleCn:"我们邻居很友好。", scene:"", cat:"life"},
  {id:"life035", word:"colleague", phonetic:"/ˈkɑːliːɡ/", pos:"n.", cn:"同事", tip:"= coworker", exampleEn:"She's a colleague from work.", exampleCn:"她是我同事。", scene:"", cat:"life"},
  {id:"life036", word:"invite", phonetic:"/ɪnˈvaɪt/", pos:"v.", cn:"邀请", tip:"名词 invitation", exampleEn:"They invited us to dinner.", exampleCn:"他们邀我们吃晚饭。", scene:"", cat:"life"},
  {id:"life037", word:"apologize", phonetic:"/əˈpɑːlədʒaɪz/", pos:"v.", cn:"道歉", tip:"apologize to sb 向某人道歉", exampleEn:"He apologized for being late.", exampleCn:"他为迟到道歉。", scene:"", cat:"life"},
  {id:"life038", word:"favor", phonetic:"/ˈfeɪvər/", pos:"n.", cn:"帮忙；恩惠", tip:"do me a favor 帮个忙", exampleEn:"Can you do me a favor?", exampleCn:"你能帮我个忙吗？", scene:"", cat:"life"},
  {id:"life039", word:"promise", phonetic:"/ˈprɑːmɪs/", pos:"v./n.", cn:"承诺；保证", tip:"keep a promise 守诺", exampleEn:"You promised to help me.", exampleCn:"你答应过帮我的。", scene:"", cat:"life"},
  {id:"life040", word:"argue", phonetic:"/ˈɑːrɡjuː/", pos:"v.", cn:"争吵；争论", tip:"名词 argument", exampleEn:"They argue about money a lot.", exampleCn:"他们经常为钱争吵。", scene:"", cat:"life"},
  // -- 身体 / 健康 --
  {id:"life041", word:"appointment", phonetic:"/əˈpɔɪntmənt/", pos:"n.", cn:"预约；约会", tip:"看医生/约见", exampleEn:"I have a doctor's appointment at 3.", exampleCn:"我三点有个医生预约。", scene:"", cat:"life"},
  {id:"life042", word:"prescription", phonetic:"/prɪˈskrɪpʃn/", pos:"n.", cn:"处方", tip:"医生开的药方", exampleEn:"Pick up your prescription at the pharmacy.", exampleCn:"去药房取你的处方药。", scene:"", cat:"life"},
  {id:"life043", word:"symptom", phonetic:"/ˈsɪmptəm/", pos:"n.", cn:"症状", tip:"生病的表现", exampleEn:"What are your symptoms?", exampleCn:"你有什么症状？", scene:"", cat:"life"},
  {id:"life044", word:"sore", phonetic:"/sɔːr/", pos:"adj.", cn:"酸痛的", tip:"sore throat 嗓子疼", exampleEn:"My legs are sore from running.", exampleCn:"我跑步跑得腿酸。", scene:"", cat:"life"},
  {id:"life045", word:"dizzy", phonetic:"/ˈdɪzi/", pos:"adj.", cn:"头晕的", tip:"feel dizzy 感到晕", exampleEn:"I feel dizzy when I stand up.", exampleCn:"我一站起来就头晕。", scene:"", cat:"life"},
  {id:"life046", word:"workout", phonetic:"/ˈwɜːrkaʊt/", pos:"n.", cn:"锻炼（一次）", tip:"a good workout 练得很好", exampleEn:"I had a great workout today.", exampleCn:"我今天练得很爽。", scene:"健身里指一次“训练”", cat:"life"},
  // -- 时间 / 安排 --
  {id:"life047", word:"schedule", phonetic:"/ˈskedʒuːl/", pos:"n./v.", cn:"日程；安排", tip:"美式 sked-，英式 shed-", exampleEn:"My schedule is full this week.", exampleCn:"我这周日程满了。", scene:"", cat:"life"},
  {id:"life048", word:"deadline", phonetic:"/ˈdedlaɪn/", pos:"n.", cn:"截止日期", tip:"meet the deadline 赶上截止", exampleEn:"The deadline is this Friday.", exampleCn:"截止日期是这周五。", scene:"", cat:"life"},
  {id:"life049", word:"reschedule", phonetic:"/ˌriːˈskedʒuːl/", pos:"v.", cn:"改期", tip:"re + schedule 重新安排", exampleEn:"Can we reschedule the meeting?", exampleCn:"我们能改下会议时间吗？", scene:"", cat:"life"},
  {id:"life050", word:"available", phonetic:"/əˈveɪləbl/", pos:"adj.", cn:"有空的；可用的", tip:"Are you available? 你有空吗", exampleEn:"Are you available tomorrow?", exampleCn:"你明天有空吗？", scene:"", cat:"life"},
  {id:"life051", word:"errand", phonetic:"/ˈerənd/", pos:"n.", cn:"差事；跑腿", tip:"run errands 出门办事", exampleEn:"I have a few errands to run.", exampleCn:"我有几件事要去办。", scene:"", cat:"life"},
  // -- 天气 / 环境 --
  {id:"life052", word:"forecast", phonetic:"/ˈfɔːrkæst/", pos:"n.", cn:"预报", tip:"weather forecast 天气预报", exampleEn:"The forecast says it'll rain.", exampleCn:"预报说会下雨。", scene:"", cat:"life"},
  {id:"life053", word:"humid", phonetic:"/ˈhjuːmɪd/", pos:"adj.", cn:"潮湿的", tip:"闷热潮湿", exampleEn:"It's so humid in summer here.", exampleCn:"这儿夏天很潮湿。", scene:"", cat:"life"},
  {id:"life054", word:"freezing", phonetic:"/ˈfriːzɪŋ/", pos:"adj.", cn:"冻死了", tip:"夸张说很冷", exampleEn:"It's freezing outside, bundle up.", exampleCn:"外面冻死了，多穿点。", scene:"", cat:"life"},
  // -- 杂项高频 --
  {id:"life055", word:"charger", phonetic:"/ˈtʃɑːrdʒər/", pos:"n.", cn:"充电器", tip:"phone charger 手机充电器", exampleEn:"Did you bring your charger?", exampleCn:"你带充电器了吗？", scene:"", cat:"life"},
  {id:"life056", word:"battery", phonetic:"/ˈbætəri/", pos:"n.", cn:"电池；电量", tip:"low battery 电量低", exampleEn:"My phone battery is almost dead.", exampleCn:"我手机快没电了。", scene:"", cat:"life"},
  {id:"life057", word:"borrow", phonetic:"/ˈbɔːroʊ/", pos:"v.", cn:"借（进）", tip:"borrow 借进，lend 借出", exampleEn:"Can I borrow your pen?", exampleCn:"我能借你的笔吗？", scene:"", cat:"life"},
  {id:"life058", word:"lend", phonetic:"/lend/", pos:"v.", cn:"借（出）", tip:"lend sb sth 把东西借给某人", exampleEn:"Can you lend me ten bucks?", exampleCn:"你能借我十块钱吗？", scene:"", cat:"life"},
  {id:"life059", word:"spare", phonetic:"/sper/", pos:"adj./v.", cn:"备用的；抽出（时间）", tip:"spare key 备用钥匙；spare time 空闲", exampleEn:"Do you have a spare charger?", exampleCn:"你有备用充电器吗？", scene:"", cat:"life"},
  {id:"life060", word:"stuff", phonetic:"/stʌf/", pos:"v.", cn:"塞满；填", tip:"作动词：塞进去", exampleEn:"She stuffed everything into one bag.", exampleCn:"她把所有东西塞进一个包。", scene:"作名词时指“东西”（已在影视口语收录）", cat:"life"},
];

if (typeof module !== "undefined") module.exports = { WORDS };
