// ===== Vocab AI 内置词库 =====
// 例句全部原创，不复制任何教材原文
// 结构: {id, word, phonetic, pos, cn, tip, exampleEn, exampleCn, scene, cat}
//   pos   词性: n./v./adj./adv./phr./prep. 等
//   scene 场景用法(可选): 某词在特定场景的特殊含义，无则留空
//   cat   分类: nce2/dev/tv 或自定义

const WORDS = [
  // ========== 新概念二 Lesson 1-5 生词 (cat: nce2) ==========
  {id:"nce009", word:"ripe", phonetic:"/raɪp/", pos:"adj.", cn:"成熟的（果实）", tip:"形容水果熟了。ripe banana 熟香蕉", exampleEn:"These apples are ripe and ready to eat.", exampleCn:"这些苹果熟了，可以吃了。", scene:"", cat:"nce2"},
  {id:"nce010", word:"weigh", phonetic:"/weɪ/", pos:"v.", cn:"称……的重量；重达", tip:"名词形式 weight（重量）", exampleEn:"Can you weigh this box for me?", exampleCn:"你能帮我称一下这个箱子吗？", scene:"", cat:"nce2"},
  {id:"nce011", word:"customer", phonetic:"/ˈkʌstəmər/", pos:"n.", cn:"顾客", tip:"区别于 client（客户/委托人）", exampleEn:"The shop was full of customers this morning.", exampleCn:"今天上午店里满是顾客。", scene:"", cat:"nce2"},
  {id:"nce015", word:"decide", phonetic:"/dɪˈsaɪd/", pos:"v.", cn:"决定", tip:"decide to do 决定做某事。名词 decision", exampleEn:"We decided to stay home tonight.", exampleCn:"我们决定今晚待在家里。", scene:"", cat:"nce2"},
  {id:"nce016", word:"lonely", phonetic:"/ˈloʊnli/", pos:"adj.", cn:"孤独的", tip:"注意：lonely 是孤独感，alone 只是独自一人", exampleEn:"He felt lonely in the new city.", exampleCn:"在新城市里他感到孤独。", scene:"", cat:"nce2"},
  {id:"nce018", word:"diary", phonetic:"/ˈdaɪəri/", pos:"n.", cn:"日记", tip:"keep a diary 记日记。别和 dairy（乳制品）混", exampleEn:"She writes in her diary every night.", exampleCn:"她每晚都写日记。", scene:"", cat:"nce2"},
  {id:"nce020", word:"capital", phonetic:"/ˈkæpɪtl/", pos:"n.", cn:"首都；资本；大写字母", tip:"一词多义，看语境", exampleEn:"Beijing is the capital of China.", exampleCn:"北京是中国的首都。", scene:"金融里指“资本/本金”；排版里指“大写字母”", cat:"nce2"},
  {id:"nce021", word:"exhibition", phonetic:"/ˌeksɪˈbɪʃn/", pos:"n.", cn:"展览；展览会", tip:"动词 exhibit（展出）", exampleEn:"We saw an art exhibition at the museum.", exampleCn:"我们在博物馆看了一场艺术展。", scene:"", cat:"nce2"},
  {id:"nce022", word:"latest", phonetic:"/ˈleɪtɪst/", pos:"adj.", cn:"最新的", tip:"late 的最高级之一，指时间最近的", exampleEn:"Have you read the latest news?", exampleCn:"你看最新消息了吗？", scene:"", cat:"nce2"},
  {id:"nce023", word:"fashion", phonetic:"/ˈfæʃn/", pos:"n.", cn:"时尚；流行", tip:"in fashion 流行的，out of fashion 过时的", exampleEn:"This style is back in fashion.", exampleCn:"这种风格又流行起来了。", scene:"", cat:"nce2"},
  {id:"nce024", word:"event", phonetic:"/ɪˈvent/", pos:"n.", cn:"事件；大事", tip:"编程里也指“事件”（点击、输入等）", exampleEn:"The wedding was a happy event.", exampleCn:"婚礼是件喜事。", scene:"编程里指“事件”，如点击、输入触发的 event", cat:"nce2"},

  // ========== 开发者高频英语 (cat: dev) ==========
  {id:"dev001", word:"error", phonetic:"/ˈerər/", pos:"n.", cn:"错误；报错", tip:"程序出问题时最常见的词", exampleEn:"The program stopped because of an error.", exampleCn:"程序因为一个错误停止了。", scene:"编程里指程序运行/语法的“报错”", cat:"dev"},
  {id:"dev002", word:"exception", phonetic:"/ɪkˈsepʃn/", pos:"n.", cn:"异常", tip:"程序运行时抛出的错误对象。throw / catch an exception", exampleEn:"The code threw an exception when the file was missing.", exampleCn:"文件缺失时代码抛出了异常。", scene:"编程里指运行时抛出的“异常”对象", cat:"dev"},
  {id:"dev003", word:"traceback", phonetic:"/ˈtreɪsbæk/", pos:"n.", cn:"回溯；错误追踪信息", tip:"Python 报错时打印的调用栈", exampleEn:"Read the traceback to find which line failed.", exampleCn:"看回溯信息找出哪一行出错了。", scene:"Python 报错时打印的调用栈信息", cat:"dev"},
  {id:"dev004", word:"debug", phonetic:"/ˌdiːˈbʌɡ/", pos:"v.", cn:"调试；排错", tip:"de（去除）+ bug（程序错误）", exampleEn:"I spent an hour debugging this function.", exampleCn:"我花了一小时调试这个函数。", scene:"编程里指“调试、找bug”", cat:"dev"},
  {id:"dev005", word:"syntax", phonetic:"/ˈsɪntæks/", pos:"n.", cn:"语法（代码）", tip:"syntax error 语法错误", exampleEn:"A missing colon caused a syntax error.", exampleCn:"少了个冒号导致语法错误。", scene:"编程里指代码的“语法”，syntax error 语法错误", cat:"dev"},
  {id:"dev006", word:"valid", phonetic:"/ˈvælɪd/", pos:"adj.", cn:"有效的；合法的", tip:"反义词 invalid。常见于输入校验", exampleEn:"Please enter a valid email address.", exampleCn:"请输入有效的邮箱地址。", scene:"编程里指数据/输入“有效、合法”", cat:"dev"},
  {id:"dev007", word:"run", phonetic:"/rʌn/", pos:"v.", cn:"运行（代码）", tip:"日常是“跑步”，技术里是“运行程序”", exampleEn:"Run the script to see the result.", exampleCn:"运行脚本看看结果。", scene:"编程里指“运行程序/脚本”，日常指“跑步”", cat:"dev"},
  {id:"dev008", word:"call", phonetic:"/kɔːl/", pos:"v.", cn:"调用（函数）", tip:"日常是“打电话”，技术里是“调用”", exampleEn:"This line calls the login function.", exampleCn:"这一行调用了登录函数。", scene:"编程里指“调用函数”，日常指“打电话”", cat:"dev"},
  {id:"dev009", word:"return", phonetic:"/rɪˈtɜːrn/", pos:"v.", cn:"返回（值）", tip:"函数把结果 return 出去", exampleEn:"The function returns a list of names.", exampleCn:"这个函数返回一个名字列表。", scene:"编程里指函数“返回值”，日常指“归还/返回”", cat:"dev"},
  {id:"dev010", word:"import", phonetic:"/ɪmˈpɔːrt/", pos:"v.", cn:"导入（模块）", tip:"把别的代码引进来用", exampleEn:"Import the math module before using it.", exampleCn:"使用前先导入 math 模块。", scene:"编程里指“导入模块”，日常/贸易里指“进口”", cat:"dev"},
  {id:"dev011", word:"deploy", phonetic:"/dɪˈplɔɪ/", pos:"v.", cn:"部署（上线）", tip:"把代码发布到服务器/线上", exampleEn:"We deploy the app every Friday.", exampleCn:"我们每周五部署应用。", scene:"编程里指把代码“部署”上线", cat:"dev"},
  {id:"dev012", word:"merge", phonetic:"/mɜːrdʒ/", pos:"v.", cn:"合并（分支/代码）", tip:"Git 里把两个分支合到一起", exampleEn:"Merge your branch into main when ready.", exampleCn:"准备好后把你的分支合并到 main。", scene:"Git 里指“合并分支”", cat:"dev"},
  {id:"dev013", word:"commit", phonetic:"/kəˈmɪt/", pos:"v./n.", cn:"提交（代码记录）", tip:"Git 里保存一次改动", exampleEn:"Write a clear message for each commit.", exampleCn:"每次提交都写清楚说明。", scene:"Git 里指一次“提交”记录", cat:"dev"},
  {id:"dev014", word:"branch", phonetic:"/bræntʃ/", pos:"n.", cn:"分支", tip:"从主线分出来独立开发", exampleEn:"Create a new branch for this feature.", exampleCn:"为这个功能新建一个分支。", scene:"Git 里指代码“分支”，日常指“树枝/分店”", cat:"dev"},
  {id:"dev015", word:"repository", phonetic:"/rɪˈpɑːzətɔːri/", pos:"n.", cn:"代码仓库", tip:"简称 repo。代码存放的地方", exampleEn:"Clone the repository to your computer.", exampleCn:"把仓库克隆到你的电脑。", scene:"编程里指“代码仓库”，简称 repo", cat:"dev"},
  {id:"dev016", word:"pull", phonetic:"/pʊl/", pos:"v.", cn:"拉取（远程代码）", tip:"把远程的更新拉到本地", exampleEn:"Pull the latest changes before you start.", exampleCn:"开始前先拉取最新改动。", scene:"Git 里指“拉取”远程更新，日常指“拉”", cat:"dev"},
  {id:"dev017", word:"push", phonetic:"/pʊʃ/", pos:"v.", cn:"推送（到远程）", tip:"把本地提交推到远程仓库", exampleEn:"Push your commits to the remote repository.", exampleCn:"把你的提交推送到远程仓库。", scene:"Git 里指“推送”到远程，日常指“推”", cat:"dev"},
  {id:"dev018", word:"request", phonetic:"/rɪˈkwest/", pos:"n./v.", cn:"请求", tip:"客户端向服务器发的请求", exampleEn:"The app sends a request to the server.", exampleCn:"应用向服务器发送一个请求。", scene:"网络里指客户端发的“请求”", cat:"dev"},
  {id:"dev019", word:"response", phonetic:"/rɪˈspɑːns/", pos:"n.", cn:"响应；回复", tip:"服务器返回的结果", exampleEn:"The server returned an empty response.", exampleCn:"服务器返回了空响应。", scene:"网络里指服务器的“响应”", cat:"dev"},
  {id:"dev020", word:"endpoint", phonetic:"/ˈendpɔɪnt/", pos:"n.", cn:"接口端点", tip:"API 的某个访问地址", exampleEn:"This endpoint returns user data.", exampleCn:"这个端点返回用户数据。", scene:"API 里指一个访问“端点”地址", cat:"dev"},
  {id:"dev021", word:"parse", phonetic:"/pɑːrs/", pos:"v.", cn:"解析", tip:"把文本/数据拆解成结构。parse JSON", exampleEn:"Parse the JSON before reading the values.", exampleCn:"读取数值前先解析 JSON。", scene:"编程里指“解析”文本/数据，如 parse JSON", cat:"dev"},
  {id:"dev022", word:"token", phonetic:"/ˈtoʊkən/", pos:"n.", cn:"令牌；词元", tip:"既指身份令牌，也指 LLM 的词元", exampleEn:"The API key is sent as an access token.", exampleCn:"API 密钥以访问令牌的形式发送。", scene:"安全里指身份“令牌”；大模型里指“词元”", cat:"dev"},
  {id:"dev023", word:"prompt", phonetic:"/prɑːmpt/", pos:"n.", cn:"提示词", tip:"给大模型的输入指令", exampleEn:"A clear prompt gives a better answer.", exampleCn:"清晰的提示词能得到更好的回答。", scene:"AI 里指给模型的“提示词”；命令行里指“提示符”", cat:"dev"},
  {id:"dev024", word:"model", phonetic:"/ˈmɑːdl/", pos:"n.", cn:"模型", tip:"指 AI 模型，如 Claude、GPT", exampleEn:"Choose a smaller model for fast replies.", exampleCn:"想要快速回复就选小一点的模型。", scene:"AI 里指“模型”，日常指“模特/模型”", cat:"dev"},
  {id:"dev025", word:"stream", phonetic:"/striːm/", pos:"v./n.", cn:"流式传输", tip:"逐字返回结果，而非一次性给", exampleEn:"The model streams the answer word by word.", exampleCn:"模型逐字流式返回答案。", scene:"编程里指“流式传输”，日常指“小溪/流”", cat:"dev"},
  {id:"dev026", word:"schema", phonetic:"/ˈskiːmə/", pos:"n.", cn:"结构定义；模式", tip:"规定数据长什么样的模板", exampleEn:"The tool needs a schema to know the inputs.", exampleCn:"工具需要一个结构定义来识别输入。", scene:"编程里指数据的“结构定义/模式”", cat:"dev"},

  // ========== 影视口语高频 (cat: tv) ==========
  {id:"tv001", word:"figure out", phonetic:"/ˈfɪɡjər aʊt/", pos:"phr.", cn:"弄明白；搞清楚", tip:"看剧最高频之一。= work out / understand", exampleEn:"I can't figure out why she's so upset.", exampleCn:"我搞不懂她为什么这么生气。", scene:"", cat:"tv"},
  {id:"tv002", word:"deal", phonetic:"/diːl/", pos:"n./v.", cn:"约定；交易；处理", tip:"It's a deal 就这么定了；deal with 处理", exampleEn:"Okay, it's a deal. See you at eight.", exampleCn:"好，说定了，八点见。", scene:"", cat:"tv"},
  {id:"tv003", word:"whatever", phonetic:"/wʌtˈevər/", pos:"pron./int.", cn:"随便；无所谓（语气）", tip:"口语里常带不耐烦/敷衍的味道", exampleEn:"Whatever, I don't really care anymore.", exampleCn:"随便吧，我已经懒得管了。", scene:"", cat:"tv"},
  {id:"tv004", word:"freak out", phonetic:"/friːk aʊt/", pos:"phr.", cn:"吓坏；抓狂", tip:"情绪失控、慌了。剧里超常见", exampleEn:"Don't freak out, but I lost your keys.", exampleCn:"你先别慌，我把你钥匙弄丢了。", scene:"", cat:"tv"},
  {id:"tv005", word:"awesome", phonetic:"/ˈɔːsəm/", pos:"adj.", cn:"太棒了；超赞", tip:"美剧口头禅，表示赞叹", exampleEn:"You finished it already? Awesome!", exampleCn:"你已经做完了？太棒了！", scene:"", cat:"tv"},
  {id:"tv006", word:"guess", phonetic:"/ɡes/", pos:"v.", cn:"猜；觉得（口语）", tip:"I guess 我觉得吧（不太确定的语气）", exampleEn:"I guess we could try that.", exampleCn:"我觉得我们可以试试那个吧。", scene:"", cat:"tv"},
  {id:"tv007", word:"mean", phonetic:"/miːn/", pos:"v./adj.", cn:"意思是；刻薄的", tip:"I mean… 我是说……（解释/改口）", exampleEn:"I mean, it's not a big deal.", exampleCn:"我是说，这没什么大不了的。", scene:"", cat:"tv"},
  {id:"tv008", word:"kidding", phonetic:"/ˈkɪdɪŋ/", pos:"v.", cn:"开玩笑", tip:"Are you kidding me? 你逗我呢？", exampleEn:"Relax, I'm just kidding.", exampleCn:"放松，我开玩笑的。", scene:"", cat:"tv"},
  {id:"tv009", word:"point", phonetic:"/pɔɪnt/", pos:"n.", cn:"重点；意义", tip:"What's the point? 有什么意义？That's the point 这就是重点", exampleEn:"What's the point of waiting here?", exampleCn:"在这儿等着有什么意义？", scene:"", cat:"tv"},
  {id:"tv010", word:"stuff", phonetic:"/stʌf/", pos:"n.", cn:"东西；玩意儿", tip:"泛指一堆东西，比 things 更随意", exampleEn:"Just put your stuff over there.", exampleCn:"把你的东西放那边就行。", scene:"", cat:"tv"},
  {id:"tv011", word:"hang out", phonetic:"/hæŋ aʊt/", pos:"phr.", cn:"一起玩；闲混", tip:"约朋友出去玩、消磨时间", exampleEn:"We used to hang out every weekend.", exampleCn:"我们以前每周末都一起玩。", scene:"", cat:"tv"},
  {id:"tv012", word:"awkward", phonetic:"/ˈɔːkwərd/", pos:"adj.", cn:"尴尬的", tip:"That's so awkward 太尴尬了", exampleEn:"There was an awkward silence at dinner.", exampleCn:"晚饭时有段尴尬的沉默。", scene:"", cat:"tv"},
  {id:"tv013", word:"creepy", phonetic:"/ˈkriːpi/", pos:"adj.", cn:"瘆人的；令人发毛的", tip:"形容人或场景让人不舒服", exampleEn:"That old house is really creepy at night.", exampleCn:"那栋老房子晚上真瘆人。", scene:"", cat:"tv"},
  {id:"tv014", word:"mess", phonetic:"/mes/", pos:"n.", cn:"一团糟；搞砸", tip:"a mess 乱七八糟；mess up 搞砸", exampleEn:"Sorry about the mess, I just moved in.", exampleCn:"抱歉这么乱，我刚搬进来。", scene:"", cat:"tv"},
  {id:"tv015", word:"weird", phonetic:"/wɪrd/", pos:"adj.", cn:"奇怪的；古怪的", tip:"比 strange 更口语、更高频", exampleEn:"It feels weird being back home.", exampleCn:"回到家感觉怪怪的。", scene:"", cat:"tv"},
  {id:"tv016", word:"totally", phonetic:"/ˈtoʊtəli/", pos:"adv.", cn:"完全；绝对（赞同）", tip:"Totally! 完全同意！", exampleEn:"You're totally right about that.", exampleCn:"这件事你说得完全对。", scene:"", cat:"tv"},
  {id:"tv017", word:"chill", phonetic:"/tʃɪl/", pos:"v./adj.", cn:"放松；冷静", tip:"chill out 放松点；也指“很酷/淡定”", exampleEn:"Just chill, everything will be fine.", exampleCn:"放轻松，一切都会好的。", scene:"", cat:"tv"},
  {id:"tv018", word:"gonna", phonetic:"/ˈɡɒnə/", pos:"phr.", cn:"将要（going to 口语缩写）", tip:"剧里几乎没人说 going to，都说 gonna", exampleEn:"I'm gonna grab some coffee.", exampleCn:"我要去买杯咖啡。", scene:"", cat:"tv"},
  {id:"tv019", word:"wanna", phonetic:"/ˈwɒnə/", pos:"phr.", cn:"想要（want to 口语缩写）", tip:"Do you wanna…? 你想不想……？", exampleEn:"Do you wanna come with us?", exampleCn:"你想跟我们一起去吗？", scene:"", cat:"tv"},
  {id:"tv020", word:"barely", phonetic:"/ˈberli/", pos:"adv.", cn:"几乎不；勉强", tip:"barely + 动词 = 差点没……", exampleEn:"I barely slept last night.", exampleCn:"我昨晚几乎没睡。", scene:"", cat:"tv"},
  {id:"tv021", word:"owe", phonetic:"/oʊ/", pos:"v.", cn:"欠（钱/人情）", tip:"I owe you one 我欠你个人情", exampleEn:"Thanks, I owe you one.", exampleCn:"谢了，我欠你个人情。", scene:"", cat:"tv"},
  {id:"tv022", word:"creep", phonetic:"/kriːp/", pos:"n./v.", cn:"讨厌鬼；慢慢移动", tip:"骂人时指“变态/讨厌的家伙”", exampleEn:"That guy is such a creep.", exampleCn:"那家伙真是个讨厌鬼。", scene:"", cat:"tv"},

  // ===== 科技开发增补 (cat: dev) =====
  // -- Python 核心实操 --
  {id:"dev027", word:"variable", phonetic:"/ˈveriəbl/", pos:"n.", cn:"变量", tip:"存数据的容器", exampleEn:"Store the result in a variable.", exampleCn:"把结果存进一个变量。", scene:"编程里指存值的“变量”", cat:"dev"},
  {id:"dev028", word:"function", phonetic:"/ˈfʌŋkʃn/", pos:"n.", cn:"函数；功能", tip:"def 定义函数", exampleEn:"This function returns the total.", exampleCn:"这个函数返回总和。", scene:"编程里指“函数”，数学里指“函数”，日常指“功能/作用”", cat:"dev"},
  {id:"dev029", word:"parameter", phonetic:"/pəˈræmɪtər/", pos:"n.", cn:"参数（形参）", tip:"函数定义里的占位变量", exampleEn:"This function takes two parameters.", exampleCn:"这个函数接收两个参数。", scene:"编程里指函数定义时的“形参”", cat:"dev"},
  {id:"dev030", word:"argument", phonetic:"/ˈɑːrɡjumənt/", pos:"n.", cn:"实参；论点", tip:"调用时实际传的值；日常指“争论”", exampleEn:"Pass the file name as an argument.", exampleCn:"把文件名作为实参传进去。", scene:"编程里指调用时传的“实参”；日常指“争论/论点”", cat:"dev"},
  {id:"dev031", word:"module", phonetic:"/ˈmɑːdʒuːl/", pos:"n.", cn:"模块", tip:"一个 .py 文件就是一个模块", exampleEn:"Import the os module first.", exampleCn:"先导入 os 模块。", scene:"编程里指可复用的“模块”", cat:"dev"},
  {id:"dev032", word:"package", phonetic:"/ˈpækɪdʒ/", pos:"n.", cn:"包；软件包", tip:"一组模块的集合；pip install 装包", exampleEn:"Install the package with pip.", exampleCn:"用 pip 安装这个包。", scene:"编程里指“代码包”；日常指“包裹”", cat:"dev"},
  {id:"dev033", word:"library", phonetic:"/ˈlaɪbreri/", pos:"n.", cn:"库；图书馆", tip:"现成的代码工具集，如 numpy", exampleEn:"Use a third-party library to save time.", exampleCn:"用第三方库省时间。", scene:"编程里指“代码库”；日常指“图书馆”", cat:"dev"},
  {id:"dev034", word:"keyword", phonetic:"/ˈkiːwɜːrd/", pos:"n.", cn:"关键字", tip:"语言保留的特殊词，如 if/for", exampleEn:"if and for are Python keywords.", exampleCn:"if 和 for 是 Python 关键字。", scene:"编程里指语言保留的“关键字”", cat:"dev"},
  {id:"dev035", word:"indent", phonetic:"/ɪnˈdent/", pos:"v.", cn:"缩进", tip:"Python 靠缩进分代码块", exampleEn:"Indent the code inside the loop.", exampleCn:"把循环里的代码缩进。", scene:"编程里指代码“缩进”（Python 很关键）", cat:"dev"},
  {id:"dev036", word:"comment", phonetic:"/ˈkɑːment/", pos:"n.", cn:"注释；评论", tip:"# 开头的说明，程序不执行", exampleEn:"Add a comment to explain this line.", exampleCn:"加个注释解释这一行。", scene:"编程里指代码“注释”；日常指“评论”", cat:"dev"},
  {id:"dev037", word:"string", phonetic:"/strɪŋ/", pos:"n.", cn:"字符串", tip:"引号包起来的文本", exampleEn:"Convert the number to a string.", exampleCn:"把数字转成字符串。", scene:"编程里指文本类型“字符串”；日常指“线/串”", cat:"dev"},
  {id:"dev038", word:"integer", phonetic:"/ˈɪntɪdʒər/", pos:"n.", cn:"整数", tip:"简称 int，没有小数点", exampleEn:"Age must be an integer.", exampleCn:"年龄必须是整数。", scene:"编程/数学里指“整数”", cat:"dev"},
  {id:"dev039", word:"boolean", phonetic:"/ˈbuːliən/", pos:"n.", cn:"布尔值", tip:"只有 True/False 两个值", exampleEn:"The check returns a boolean.", exampleCn:"这个检查返回一个布尔值。", scene:"编程里指真假“布尔值”", cat:"dev"},
  {id:"dev040", word:"list", phonetic:"/lɪst/", pos:"n.", cn:"列表", tip:"有序可变的元素集合 []", exampleEn:"Add the item to the list.", exampleCn:"把这个元素加进列表。", scene:"Python 里指有序的“列表”；日常指“清单”", cat:"dev"},
  {id:"dev041", word:"dictionary", phonetic:"/ˈdɪkʃəneri/", pos:"n.", cn:"字典", tip:"键值对集合 {}，简称 dict", exampleEn:"Store the settings in a dictionary.", exampleCn:"把配置存在字典里。", scene:"编程里指键值对“字典”；日常指“词典”", cat:"dev"},
  {id:"dev042", word:"loop", phonetic:"/luːp/", pos:"n.", cn:"循环", tip:"for / while 重复执行", exampleEn:"Use a loop to go through the list.", exampleCn:"用循环遍历列表。", scene:"编程里指“循环”", cat:"dev"},
  {id:"dev043", word:"iterate", phonetic:"/ˈɪtəreɪt/", pos:"v.", cn:"遍历；迭代", tip:"逐个处理集合里的元素", exampleEn:"Iterate over each row in the file.", exampleCn:"遍历文件里的每一行。", scene:"编程里指“遍历/迭代”", cat:"dev"},
  {id:"dev044", word:"recursion", phonetic:"/rɪˈkɜːrʒn/", pos:"n.", cn:"递归", tip:"函数调用自己", exampleEn:"This problem is easy to solve with recursion.", exampleCn:"这个问题用递归很好解。", scene:"编程里指函数自调用的“递归”", cat:"dev"},
  {id:"dev045", word:"lambda", phonetic:"/ˈlæmdə/", pos:"n.", cn:"匿名函数", tip:"一行写的小函数", exampleEn:"Use a lambda for a quick sort key.", exampleCn:"用 lambda 写个简易排序键。", scene:"编程里指“匿名函数”", cat:"dev"},
  {id:"dev046", word:"decorator", phonetic:"/ˈdekəreɪtər/", pos:"n.", cn:"装饰器", tip:"@ 开头，给函数加功能", exampleEn:"Add a decorator to log each call.", exampleCn:"加个装饰器记录每次调用。", scene:"Python 里指 @ 语法的“装饰器”", cat:"dev"},
  {id:"dev047", word:"instance", phonetic:"/ˈɪnstəns/", pos:"n.", cn:"实例；例子", tip:"类创建出的具体对象", exampleEn:"Create an instance of the class.", exampleCn:"创建这个类的一个实例。", scene:"编程里指类的“实例”；日常指“例子/情况”", cat:"dev"},
  {id:"dev048", word:"attribute", phonetic:"/ˈætrɪbjuːt/", pos:"n.", cn:"属性", tip:"对象身上的数据，用 . 访问", exampleEn:"Access the name attribute with a dot.", exampleCn:"用点号访问 name 属性。", scene:"编程里指对象的“属性”", cat:"dev"},
  {id:"dev049", word:"inherit", phonetic:"/ɪnˈherɪt/", pos:"v.", cn:"继承", tip:"子类拿到父类的能力", exampleEn:"The child class inherits from the parent.", exampleCn:"子类继承自父类。", scene:"面向对象里指类的“继承”；日常指“继承遗产”", cat:"dev"},
  {id:"dev050", word:"input", phonetic:"/ˈɪnpʊt/", pos:"n.", cn:"输入", tip:"用户/程序提供的数据", exampleEn:"Read the user input from the keyboard.", exampleCn:"从键盘读取用户输入。", scene:"编程里指“输入”", cat:"dev"},
  {id:"dev051", word:"output", phonetic:"/ˈaʊtpʊt/", pos:"n.", cn:"输出", tip:"程序产生的结果", exampleEn:"Print the output to the screen.", exampleCn:"把输出打印到屏幕。", scene:"编程里指“输出”", cat:"dev"},
  {id:"dev052", word:"print", phonetic:"/prɪnt/", pos:"v.", cn:"打印输出", tip:"日常是“打印”，编程是“输出到屏幕”", exampleEn:"Print the result to check it.", exampleCn:"打印结果检查一下。", scene:"编程里指“输出到控制台”；日常指“打印/印刷”", cat:"dev"},
  // -- 数据/文件 --
  {id:"dev053", word:"dataset", phonetic:"/ˈdeɪtəset/", pos:"n.", cn:"数据集", tip:"训练模型用的成批数据", exampleEn:"This dataset has 10,000 images.", exampleCn:"这个数据集有一万张图。", scene:"AI 里指训练用的“数据集”", cat:"dev"},
  {id:"dev055", word:"format", phonetic:"/ˈfɔːrmæt/", pos:"n./v.", cn:"格式；格式化", tip:"数据/文本的排列方式", exampleEn:"Save the file in JSON format.", exampleCn:"用 JSON 格式保存文件。", scene:"编程里指数据“格式”或“格式化”", cat:"dev"},
  {id:"dev056", word:"directory", phonetic:"/dəˈrektəri/", pos:"n.", cn:"目录；文件夹", tip:"= folder，命令行常说 dir", exampleEn:"Change to the project directory.", exampleCn:"切换到项目目录。", scene:"系统里指“目录/文件夹”", cat:"dev"},
  {id:"dev057", word:"path", phonetic:"/pæθ/", pos:"n.", cn:"路径", tip:"文件的位置地址", exampleEn:"Give the full path to the file.", exampleCn:"给出文件的完整路径。", scene:"系统里指文件“路径”；日常指“小路”", cat:"dev"},
  // -- 命令行 / Termux --
  {id:"dev058", word:"terminal", phonetic:"/ˈtɜːrmɪnl/", pos:"n.", cn:"终端", tip:"输入命令的黑窗口", exampleEn:"Open the terminal and type the command.", exampleCn:"打开终端输入命令。", scene:"系统里指命令行“终端”；日常指“航站楼/终点站”", cat:"dev"},
  {id:"dev059", word:"shell", phonetic:"/ʃel/", pos:"n.", cn:"shell（命令解释器）", tip:"bash/zsh 这类", exampleEn:"Run the script in the shell.", exampleCn:"在 shell 里运行脚本。", scene:"系统里指命令“解释器”；日常指“贝壳/外壳”", cat:"dev"},
  {id:"dev060", word:"command", phonetic:"/kəˈmænd/", pos:"n.", cn:"命令", tip:"敲给终端执行的指令", exampleEn:"Type the install command.", exampleCn:"输入安装命令。", scene:"系统里指“命令”；日常指“命令/指挥”", cat:"dev"},
  {id:"dev061", word:"script", phonetic:"/skrɪpt/", pos:"n.", cn:"脚本", tip:"一串可执行的命令/代码", exampleEn:"Write a shell script to automate it.", exampleCn:"写个 shell 脚本自动化它。", scene:"编程里指“脚本”；影视里指“剧本”", cat:"dev"},
  {id:"dev062", word:"install", phonetic:"/ɪnˈstɔːl/", pos:"v.", cn:"安装", tip:"pkg install / pip install", exampleEn:"Install the package before running.", exampleCn:"运行前先安装这个包。", scene:"软件里指“安装”", cat:"dev"},
  {id:"dev063", word:"upgrade", phonetic:"/ˌʌpˈɡreɪd/", pos:"v.", cn:"升级", tip:"升到更新版本", exampleEn:"Upgrade all packages weekly.", exampleCn:"每周升级所有的包。", scene:"软件里指“升级”", cat:"dev"},
  {id:"dev064", word:"dependency", phonetic:"/dɪˈpendənsi/", pos:"n.", cn:"依赖", tip:"这个项目运行需要的别的包", exampleEn:"Install all dependencies first.", exampleCn:"先安装所有依赖。", scene:"编程里指项目“依赖”", cat:"dev"},
  {id:"dev065", word:"permission", phonetic:"/pərˈmɪʃn/", pos:"n.", cn:"权限", tip:"chmod 改文件权限", exampleEn:"You don't have permission to edit this file.", exampleCn:"你没有权限编辑这个文件。", scene:"系统里指文件/操作“权限”", cat:"dev"},
  {id:"dev066", word:"process", phonetic:"/ˈprɑːses/", pos:"n.", cn:"进程；过程", tip:"正在运行的程序实例", exampleEn:"Kill the process that is stuck.", exampleCn:"杀掉卡住的那个进程。", scene:"系统里指运行中的“进程”；日常指“过程”", cat:"dev"},
  // -- 网络 / HTTP / API --
  {id:"dev067", word:"server", phonetic:"/ˈsɜːrvər/", pos:"n.", cn:"服务器", tip:"提供服务的远程电脑", exampleEn:"The server is down right now.", exampleCn:"服务器现在挂了。", scene:"网络里指“服务器”", cat:"dev"},
  {id:"dev068", word:"client", phonetic:"/ˈklaɪənt/", pos:"n.", cn:"客户端", tip:"向服务器请求的一方", exampleEn:"The client sends a request to the server.", exampleCn:"客户端向服务器发请求。", scene:"网络里指“客户端”；商务里指“客户”", cat:"dev"},
  {id:"dev069", word:"connect", phonetic:"/kəˈnekt/", pos:"v.", cn:"连接", tip:"建立网络/设备连接", exampleEn:"Connect to the WiFi first.", exampleCn:"先连上 WiFi。", scene:"网络里指“连接”", cat:"dev"},
  {id:"dev070", word:"timeout", phonetic:"/ˈtaɪmaʊt/", pos:"n.", cn:"超时", tip:"等太久没响应就超时", exampleEn:"The request failed with a timeout.", exampleCn:"请求因超时失败了。", scene:"网络里指请求“超时”", cat:"dev"},
  {id:"dev071", word:"header", phonetic:"/ˈhedər/", pos:"n.", cn:"请求头；头部", tip:"HTTP 请求附带的元信息", exampleEn:"Add the API key in the header.", exampleCn:"把 API 密钥加在请求头里。", scene:"HTTP 里指“请求头”", cat:"dev"},
  {id:"dev072", word:"payload", phonetic:"/ˈpeɪloʊd/", pos:"n.", cn:"负载；数据体", tip:"请求/响应里真正传的数据", exampleEn:"Send the data as a JSON payload.", exampleCn:"把数据作为 JSON 负载发送。", scene:"网络里指传输的“数据体”", cat:"dev"},
  {id:"dev073", word:"status", phonetic:"/ˈsteɪtəs/", pos:"n.", cn:"状态", tip:"HTTP 状态码如 200/404", exampleEn:"Check the status code of the response.", exampleCn:"检查响应的状态码。", scene:"网络里指“状态（码）”；日常指“身份/状况”", cat:"dev"},
  {id:"dev074", word:"cache", phonetic:"/kæʃ/", pos:"n.", cn:"缓存", tip:"临时存起来加速的数据", exampleEn:"Clear the cache and try again.", exampleCn:"清缓存再试一次。", scene:"计算机里指“缓存”", cat:"dev"},
  // -- Git 补充 --
  {id:"dev075", word:"clone", phonetic:"/kloʊn/", pos:"v.", cn:"克隆（仓库）", tip:"把远程仓库整个拷到本地", exampleEn:"Clone the repo to start working.", exampleCn:"克隆仓库开始干活。", scene:"Git 里指“克隆仓库”；生物里指“克隆”", cat:"dev"},
  {id:"dev076", word:"conflict", phonetic:"/ˈkɑːnflɪkt/", pos:"n.", cn:"冲突", tip:"合并时两边改了同一处", exampleEn:"Resolve the merge conflict first.", exampleCn:"先解决合并冲突。", scene:"Git 里指“合并冲突”；日常指“冲突/矛盾”", cat:"dev"},
  {id:"dev077", word:"stage", phonetic:"/steɪdʒ/", pos:"v.", cn:"暂存（git add）", tip:"git add 把改动放进暂存区", exampleEn:"Stage your changes before committing.", exampleCn:"提交前先暂存改动。", scene:"Git 里指“暂存”；日常指“舞台/阶段”", cat:"dev"},
  // -- AI / LLM 补充 --
  {id:"dev078", word:"train", phonetic:"/treɪn/", pos:"v.", cn:"训练（模型）", tip:"喂数据让模型学习", exampleEn:"Train the model on the dataset.", exampleCn:"在数据集上训练模型。", scene:"AI 里指“训练模型”；日常指“火车/训练”", cat:"dev"},
  {id:"dev079", word:"inference", phonetic:"/ˈɪnfərəns/", pos:"n.", cn:"推理（模型出结果）", tip:"用训练好的模型做预测", exampleEn:"Inference is fast on this GPU.", exampleCn:"这块 GPU 上推理很快。", scene:"AI 里指模型“推理”；日常指“推断”", cat:"dev"},
  {id:"dev080", word:"embedding", phonetic:"/ɪmˈbedɪŋ/", pos:"n.", cn:"嵌入向量", tip:"把文本转成数字向量", exampleEn:"Store the embeddings in a vector database.", exampleCn:"把嵌入向量存进向量数据库。", scene:"AI 里指文本的“嵌入向量”", cat:"dev"},
  {id:"dev081", word:"fine-tune", phonetic:"/ˌfaɪnˈtuːn/", pos:"v.", cn:"微调", tip:"在已有模型上小幅再训练", exampleEn:"Fine-tune the model on your own data.", exampleCn:"用你自己的数据微调模型。", scene:"AI 里指模型“微调”", cat:"dev"},
  {id:"dev082", word:"hallucination", phonetic:"/həˌluːsɪˈneɪʃn/", pos:"n.", cn:"幻觉（模型瞎编）", tip:"模型一本正经胡说", exampleEn:"Watch out for hallucinations in the answer.", exampleCn:"小心回答里的幻觉。", scene:"AI 里指模型“幻觉/瞎编”；医学里指“幻觉”", cat:"dev"},
  {id:"dev083", word:"latency", phonetic:"/ˈleɪtənsi/", pos:"n.", cn:"延迟", tip:"从请求到响应的耗时", exampleEn:"Lower latency means faster replies.", exampleCn:"延迟越低回复越快。", scene:"网络/AI 里指响应“延迟”", cat:"dev"},
  {id:"dev084", word:"benchmark", phonetic:"/ˈbentʃmɑːrk/", pos:"n.", cn:"基准测试", tip:"衡量性能的标准测试", exampleEn:"This model tops the benchmark.", exampleCn:"这个模型在基准测试里居首。", scene:"技术里指“基准测试”；商业里指“标杆”", cat:"dev"},
  {id:"dev085", word:"retrieval", phonetic:"/rɪˈtriːvl/", pos:"n.", cn:"检索", tip:"RAG 里从知识库找资料", exampleEn:"Retrieval brings in relevant documents.", exampleCn:"检索会拉进相关文档。", scene:"AI 里指 RAG 的“检索”", cat:"dev"},
  // -- 报错 / 调试补充 --
  {id:"dev086", word:"warning", phonetic:"/ˈwɔːrnɪŋ/", pos:"n.", cn:"警告", tip:"不致命但要注意的提示", exampleEn:"The code runs but shows a warning.", exampleCn:"代码能跑但有个警告。", scene:"编程里指“警告”（比 error 轻）", cat:"dev"},
  {id:"dev087", word:"crash", phonetic:"/kræʃ/", pos:"v.", cn:"崩溃", tip:"程序意外退出", exampleEn:"The app crashes on startup.", exampleCn:"应用一启动就崩溃。", scene:"软件里指程序“崩溃”；日常指“撞车/坠毁”", cat:"dev"},
  {id:"dev088", word:"freeze", phonetic:"/friːz/", pos:"v.", cn:"卡死；冻结", tip:"程序无响应卡住", exampleEn:"The screen froze for a few seconds.", exampleCn:"屏幕卡死了几秒。", scene:"软件里指界面“卡死”；日常指“结冰/冻结”", cat:"dev"},
  {id:"dev089", word:"overflow", phonetic:"/ˈoʊvərfloʊ/", pos:"n.", cn:"溢出", tip:"超出容量，如栈溢出", exampleEn:"Too much recursion causes a stack overflow.", exampleCn:"递归太深导致栈溢出。", scene:"编程里指数据/栈“溢出”", cat:"dev"},
  {id:"dev090", word:"deprecated", phonetic:"/ˈdeprəkeɪtɪd/", pos:"adj.", cn:"已弃用的", tip:"还能用但不推荐、将移除", exampleEn:"This function is deprecated, use the new one.", exampleCn:"这个函数已弃用，用新的。", scene:"编程里指 API“已弃用”", cat:"dev"},
  {id:"dev091", word:"override", phonetic:"/ˌoʊvərˈraɪd/", pos:"v.", cn:"重写；覆盖", tip:"子类重新定义父类方法", exampleEn:"Override this method in the subclass.", exampleCn:"在子类里重写这个方法。", scene:"编程里指方法“重写/覆盖”", cat:"dev"},
  {id:"dev092", word:"default", phonetic:"/dɪˈfɔːlt/", pos:"n./adj.", cn:"默认（值）", tip:"不指定时用的预设值", exampleEn:"The default value is zero.", exampleCn:"默认值是零。", scene:"编程里指“默认值”；金融里指“违约”", cat:"dev"},
  {id:"dev093", word:"async", phonetic:"/ˈeɪsɪŋk/", pos:"adj.", cn:"异步的", tip:"不等结果继续往下走", exampleEn:"Use an async function for network calls.", exampleCn:"网络调用用异步函数。", scene:"编程里指“异步”", cat:"dev"},
  {id:"dev094", word:"queue", phonetic:"/kjuː/", pos:"n.", cn:"队列", tip:"先进先出的排队结构", exampleEn:"Add the task to the queue.", exampleCn:"把任务加进队列。", scene:"编程里指“队列”；英式日常指“排队”", cat:"dev"},
  {id:"dev095", word:"thread", phonetic:"/θred/", pos:"n.", cn:"线程", tip:"程序里并发执行的单元", exampleEn:"Run the download on a separate thread.", exampleCn:"在单独的线程上跑下载。", scene:"编程里指“线程”；日常指“线/话题串”", cat:"dev"},
  {id:"dev096", word:"environment", phonetic:"/ɪnˈvaɪrənmənt/", pos:"n.", cn:"环境", tip:"虚拟环境 / 环境变量", exampleEn:"Activate the virtual environment first.", exampleCn:"先激活虚拟环境。", scene:"编程里指运行“环境”；日常指“环境/自然环境”", cat:"dev"},
  {id:"dev097", word:"config", phonetic:"/kənˈfɪɡ/", pos:"n.", cn:"配置", tip:"configuration 缩写，设置项", exampleEn:"Edit the config file to change the port.", exampleCn:"改配置文件来换端口。", scene:"编程里指“配置”", cat:"dev"},
  {id:"dev098", word:"log", phonetic:"/lɔːɡ/", pos:"n.", cn:"日志", tip:"程序记录的运行信息", exampleEn:"Check the logs to find the bug.", exampleCn:"看日志找 bug。", scene:"编程里指运行“日志”；日常指“原木/记录”", cat:"dev"},
  {id:"dev099", word:"backup", phonetic:"/ˈbækʌp/", pos:"n.", cn:"备份", tip:"防丢失的副本", exampleEn:"Make a backup before you delete it.", exampleCn:"删之前先做个备份。", scene:"通用：数据“备份”", cat:"dev"},
  {id:"dev100", word:"version", phonetic:"/ˈvɜːrʒn/", pos:"n.", cn:"版本", tip:"v1.0 这种", exampleEn:"Update to the latest version.", exampleCn:"更新到最新版本。", scene:"软件里指“版本”", cat:"dev"},

  // ===== 影视口语增补 (cat: tv) =====
  // -- 短语动词 --
  {id:"tv023", word:"come on", phonetic:"/kʌm ɑːn/", pos:"phr.", cn:"拜托；快点；得了吧", tip:"语气词，催促或不信", exampleEn:"Come on, we're going to be late!", exampleCn:"快点，我们要迟到了！", scene:"", cat:"tv"},
  {id:"tv024", word:"hold on", phonetic:"/hoʊld ɑːn/", pos:"phr.", cn:"等一下；坚持住", tip:"打电话/让人稍等", exampleEn:"Hold on, I'll be right back.", exampleCn:"等一下，我马上回来。", scene:"", cat:"tv"},
  {id:"tv025", word:"calm down", phonetic:"/kɑːm daʊn/", pos:"phr.", cn:"冷静；平静下来", tip:"安抚别人常用", exampleEn:"Calm down and tell me what happened.", exampleCn:"冷静点，告诉我怎么了。", scene:"", cat:"tv"},
  {id:"tv026", word:"shut up", phonetic:"/ʃʌt ʌp/", pos:"phr.", cn:"闭嘴；不会吧", tip:"也可表惊讶“不会吧”", exampleEn:"Shut up, no way that happened!", exampleCn:"不会吧，真发生了？！", scene:"", cat:"tv"},
  {id:"tv027", word:"give up", phonetic:"/ɡɪv ʌp/", pos:"phr.", cn:"放弃", tip:"don't give up 别放弃", exampleEn:"Don't give up so easily.", exampleCn:"别这么轻易放弃。", scene:"", cat:"tv"},
  {id:"tv028", word:"show up", phonetic:"/ʃoʊ ʌp/", pos:"phr.", cn:"露面；出现", tip:"= turn up", exampleEn:"He didn't show up at the party.", exampleCn:"他没来参加派对。", scene:"", cat:"tv"},
  {id:"tv029", word:"work out", phonetic:"/wɜːrk aʊt/", pos:"phr.", cn:"解决；锻炼；成功", tip:"一词多义，看语境", exampleEn:"Don't worry, it'll work out.", exampleCn:"别担心，会成的。", scene:"健身里指“锻炼”；日常指“解决/搞定/成功”", cat:"tv"},
  {id:"tv030", word:"check out", phonetic:"/tʃek aʊt/", pos:"phr.", cn:"看看；退房", tip:"Check it out! 快看！", exampleEn:"Check out this new song.", exampleCn:"听听这首新歌。", scene:"酒店里指“退房”；日常指“看看/查看”", cat:"tv"},
  {id:"tv031", word:"hang on", phonetic:"/hæŋ ɑːn/", pos:"phr.", cn:"等等；抓紧", tip:"= hold on", exampleEn:"Hang on, I'm almost done.", exampleCn:"等等，我快好了。", scene:"", cat:"tv"},
  {id:"tv032", word:"get over", phonetic:"/ɡet ˈoʊvər/", pos:"phr.", cn:"克服；走出（情伤）", tip:"get over someone 忘掉某人", exampleEn:"It took her months to get over it.", exampleCn:"她花了几个月才走出来。", scene:"", cat:"tv"},
  {id:"tv033", word:"run into", phonetic:"/rʌn ˈɪntuː/", pos:"phr.", cn:"偶遇；撞见", tip:"= bump into", exampleEn:"I ran into an old friend today.", exampleCn:"我今天偶遇一个老朋友。", scene:"", cat:"tv"},
  {id:"tv034", word:"make it", phonetic:"/meɪk ɪt/", pos:"phr.", cn:"赶上；成功；出席", tip:"语境很活", exampleEn:"Sorry, I can't make it tonight.", exampleCn:"抱歉，我今晚来不了。", scene:"", cat:"tv"},
  {id:"tv035", word:"pull off", phonetic:"/pʊl ɔːf/", pos:"phr.", cn:"成功做成（难事）", tip:"完成了别人觉得难的事", exampleEn:"I can't believe you pulled it off!", exampleCn:"真不敢相信你做成了！", scene:"", cat:"tv"},
  {id:"tv036", word:"back off", phonetic:"/bæk ɔːf/", pos:"phr.", cn:"退后；别逼了", tip:"让人别管/别靠近", exampleEn:"Back off, this is none of your business.", exampleCn:"退后，这不关你事。", scene:"", cat:"tv"},
  {id:"tv037", word:"settle down", phonetic:"/ˈsetl daʊn/", pos:"phr.", cn:"安定下来；冷静", tip:"成家/平静下来", exampleEn:"It's time to settle down and relax.", exampleCn:"该安定下来放松了。", scene:"", cat:"tv"},
  {id:"tv038", word:"throw up", phonetic:"/θroʊ ʌp/", pos:"phr.", cn:"呕吐", tip:"= vomit，口语常用", exampleEn:"I feel like I'm going to throw up.", exampleCn:"我感觉要吐了。", scene:"", cat:"tv"},
  // -- 情绪 / 评价 --
  {id:"tv039", word:"upset", phonetic:"/ʌpˈset/", pos:"adj.", cn:"难过；心烦的", tip:"比 sad 更强的烦乱", exampleEn:"She was really upset about the news.", exampleCn:"她对那消息很难过。", scene:"", cat:"tv"},
  {id:"tv040", word:"annoying", phonetic:"/əˈnɔɪɪŋ/", pos:"adj.", cn:"烦人的", tip:"形容惹人厌的人或事", exampleEn:"That noise is so annoying.", exampleCn:"那噪音太烦人了。", scene:"", cat:"tv"},
  {id:"tv041", word:"ridiculous", phonetic:"/rɪˈdɪkjələs/", pos:"adj.", cn:"荒谬的；可笑的", tip:"This is ridiculous! 太离谱了", exampleEn:"That price is ridiculous.", exampleCn:"那价格太离谱了。", scene:"", cat:"tv"},
  {id:"tv042", word:"gorgeous", phonetic:"/ˈɡɔːrdʒəs/", pos:"adj.", cn:"美极了；超好看", tip:"夸人/景物漂亮", exampleEn:"You look gorgeous tonight.", exampleCn:"你今晚美极了。", scene:"", cat:"tv"},
  {id:"tv043", word:"jerk", phonetic:"/dʒɜːrk/", pos:"n.", cn:"混蛋；讨厌鬼", tip:"骂人，比 creep 轻", exampleEn:"Stop being such a jerk.", exampleCn:"别这么混蛋。", scene:"", cat:"tv"},
  {id:"tv044", word:"loser", phonetic:"/ˈluːzər/", pos:"n.", cn:"废物；失败者", tip:"骂人没出息", exampleEn:"Don't call yourself a loser.", exampleCn:"别说自己是废物。", scene:"", cat:"tv"},
  {id:"tv045", word:"nuts", phonetic:"/nʌts/", pos:"adj.", cn:"疯了；着迷", tip:"go nuts 抓狂；be nuts about 痴迷", exampleEn:"Are you nuts? That's dangerous!", exampleCn:"你疯了吗？那很危险！", scene:"", cat:"tv"},
  {id:"tv046", word:"broke", phonetic:"/broʊk/", pos:"adj.", cn:"没钱了；破产的", tip:"I'm broke 我穷得叮当响", exampleEn:"I can't go out, I'm broke.", exampleCn:"我不能出去，没钱了。", scene:"", cat:"tv"},
  {id:"tv047", word:"starving", phonetic:"/ˈstɑːrvɪŋ/", pos:"adj.", cn:"饿坏了", tip:"夸张说很饿", exampleEn:"Let's eat, I'm starving.", exampleCn:"吃饭吧，我饿坏了。", scene:"", cat:"tv"},
  {id:"tv048", word:"exhausted", phonetic:"/ɪɡˈzɔːstɪd/", pos:"adj.", cn:"累垮了", tip:"比 tired 更强", exampleEn:"I'm exhausted after the trip.", exampleCn:"旅行后我累垮了。", scene:"", cat:"tv"},
  // -- 日常对话高频 --
  {id:"tv049", word:"seriously", phonetic:"/ˈsɪriəsli/", pos:"adv.", cn:"认真地；真的假的", tip:"Seriously? 真的假的？", exampleEn:"Seriously, you have to try this.", exampleCn:"说真的，你得试试这个。", scene:"", cat:"tv"},
  {id:"tv050", word:"honestly", phonetic:"/ˈɑːnəstli/", pos:"adv.", cn:"老实说", tip:"开头缓冲，引出真心话", exampleEn:"Honestly, I don't care.", exampleCn:"老实说，我不在乎。", scene:"", cat:"tv"},
  {id:"tv051", word:"basically", phonetic:"/ˈbeɪsɪkli/", pos:"adv.", cn:"基本上；说白了", tip:"总结/简化时用", exampleEn:"Basically, we have no choice.", exampleCn:"说白了，我们没得选。", scene:"", cat:"tv"},
  {id:"tv052", word:"anyway", phonetic:"/ˈeniweɪ/", pos:"adv.", cn:"不管怎样；反正", tip:"转换话题或下结论", exampleEn:"Anyway, let's move on.", exampleCn:"不管怎样，我们继续吧。", scene:"", cat:"tv"},
  {id:"tv053", word:"actually", phonetic:"/ˈæktʃuəli/", pos:"adv.", cn:"其实；实际上", tip:"纠正或补充", exampleEn:"Actually, that's not true.", exampleCn:"其实那不是真的。", scene:"", cat:"tv"},
  {id:"tv054", word:"probably", phonetic:"/ˈprɑːbəbli/", pos:"adv.", cn:"大概；很可能", tip:"不太确定的推测", exampleEn:"He's probably still asleep.", exampleCn:"他大概还在睡。", scene:"", cat:"tv"},
  {id:"tv055", word:"definitely", phonetic:"/ˈdefɪnətli/", pos:"adv.", cn:"绝对；肯定", tip:"强烈肯定", exampleEn:"I will definitely be there.", exampleCn:"我肯定会到。", scene:"", cat:"tv"},
  {id:"tv056", word:"supposed to", phonetic:"/səˈpoʊzd tuː/", pos:"phr.", cn:"应该；本应", tip:"be supposed to do 理应做", exampleEn:"You're supposed to knock first.", exampleCn:"你应该先敲门的。", scene:"", cat:"tv"},
  {id:"tv057", word:"no big deal", phonetic:"/noʊ bɪɡ diːl/", pos:"phr.", cn:"没什么大不了", tip:"安慰/谦虚", exampleEn:"It's no big deal, don't worry.", exampleCn:"没什么大不了的，别担心。", scene:"", cat:"tv"},
  {id:"tv058", word:"come up with", phonetic:"/kʌm ʌp wɪð/", pos:"phr.", cn:"想出（主意）", tip:"想出办法/点子", exampleEn:"She came up with a great idea.", exampleCn:"她想出个好主意。", scene:"", cat:"tv"},
  {id:"tv059", word:"by the way", phonetic:"/baɪ ðə weɪ/", pos:"phr.", cn:"顺便说；对了", tip:"缩写 BTW，转话题", exampleEn:"By the way, did you call her?", exampleCn:"对了，你给她打电话了吗？", scene:"", cat:"tv"},
  {id:"tv060", word:"or something", phonetic:"/ɔːr ˈsʌmθɪŋ/", pos:"phr.", cn:"……之类的", tip:"句尾，表示不确定", exampleEn:"He's a doctor or something.", exampleCn:"他是医生还是什么的。", scene:"", cat:"tv"},
  {id:"tv061", word:"kind of", phonetic:"/kaɪnd əv/", pos:"phr.", cn:"有点；算是", tip:"读快成 kinda，软化语气", exampleEn:"I'm kind of tired today.", exampleCn:"我今天有点累。", scene:"", cat:"tv"},
  {id:"tv062", word:"a bit", phonetic:"/ə bɪt/", pos:"phr.", cn:"一点点", tip:"= a little", exampleEn:"Can you speak a bit slower?", exampleCn:"你能说慢一点吗？", scene:"", cat:"tv"},
  {id:"tv063", word:"for real", phonetic:"/fɔːr riːl/", pos:"phr.", cn:"真的；当真", tip:"For real? 真的假的？", exampleEn:"Are you for real right now?", exampleCn:"你现在是认真的吗？", scene:"", cat:"tv"},
  {id:"tv064", word:"no way", phonetic:"/noʊ weɪ/", pos:"phr.", cn:"不可能；没门", tip:"惊讶或拒绝", exampleEn:"No way, that's amazing!", exampleCn:"不会吧，太棒了！", scene:"", cat:"tv"},
  {id:"tv065", word:"my bad", phonetic:"/maɪ bæd/", pos:"phr.", cn:"我的错", tip:"轻松道歉，= my fault", exampleEn:"Oh, my bad, I forgot.", exampleCn:"哦，我的错，我忘了。", scene:"", cat:"tv"},
  {id:"tv066", word:"never mind", phonetic:"/ˈnevər maɪnd/", pos:"phr.", cn:"算了；别在意", tip:"放下话题", exampleEn:"Never mind, it's not important.", exampleCn:"算了，不重要。", scene:"", cat:"tv"},
  {id:"tv067", word:"what's up", phonetic:"/wʌts ʌp/", pos:"phr.", cn:"怎么了；最近咋样", tip:"打招呼或问出什么事", exampleEn:"Hey, what's up with you today?", exampleCn:"嘿，你今天怎么了？", scene:"", cat:"tv"},
  {id:"tv068", word:"hang in there", phonetic:"/hæŋ ɪn ðer/", pos:"phr.", cn:"撑住；挺住", tip:"鼓励别人坚持", exampleEn:"Hang in there, it gets better.", exampleCn:"挺住，会好起来的。", scene:"", cat:"tv"},
  {id:"tv069", word:"keep up", phonetic:"/kiːp ʌp/", pos:"phr.", cn:"跟上；保持", tip:"keep up with 跟上进度", exampleEn:"You're doing great, keep it up!", exampleCn:"你做得很好，继续保持！", scene:"", cat:"tv"},
  {id:"tv070", word:"figure", phonetic:"/ˈfɪɡjər/", pos:"v./n.", cn:"认为；身材；数字", tip:"I figure 我觉得；nice figure 身材好", exampleEn:"I figure we should leave now.", exampleCn:"我觉得我们该走了。", scene:"", cat:"tv"},
  {id:"tv071", word:"grab", phonetic:"/ɡræb/", pos:"v.", cn:"抓；随便弄（吃的）", tip:"grab a coffee 随便喝杯咖啡", exampleEn:"Let's grab some lunch.", exampleCn:"我们随便吃个午饭吧。", scene:"", cat:"tv"},
  {id:"tv072", word:"mess up", phonetic:"/mes ʌp/", pos:"phr.", cn:"搞砸", tip:"= screw up", exampleEn:"I really messed up this time.", exampleCn:"这次我真搞砸了。", scene:"", cat:"tv"},
  {id:"tv073", word:"freak", phonetic:"/friːk/", pos:"n.", cn:"怪人；狂热者", tip:"control freak 控制狂", exampleEn:"He's a bit of a neat freak.", exampleCn:"他有点洁癖。", scene:"", cat:"tv"},
  {id:"tv074", word:"creep out", phonetic:"/kriːp aʊt/", pos:"phr.", cn:"让人发毛", tip:"You're creeping me out 你吓到我了", exampleEn:"That clown really creeps me out.", exampleCn:"那小丑真让我发毛。", scene:"", cat:"tv"},
  {id:"tv075", word:"big deal", phonetic:"/bɪɡ diːl/", pos:"phr.", cn:"大事；了不起", tip:"反讽时=没什么了不起", exampleEn:"So what? Big deal.", exampleCn:"那又怎样？有什么了不起。", scene:"", cat:"tv"},
  {id:"tv076", word:"get it", phonetic:"/ɡet ɪt/", pos:"phr.", cn:"懂了；明白", tip:"I get it 我懂了", exampleEn:"Okay, I get it now.", exampleCn:"好，我现在懂了。", scene:"", cat:"tv"},
  {id:"tv077", word:"knock it off", phonetic:"/nɑːk ɪt ɔːf/", pos:"phr.", cn:"住手；别闹了", tip:"让人停止烦人行为", exampleEn:"Knock it off, you two!", exampleCn:"你俩别闹了！", scene:"", cat:"tv"},
  {id:"tv078", word:"good for you", phonetic:"/ɡʊd fɔːr juː/", pos:"phr.", cn:"真为你高兴", tip:"也可反讽", exampleEn:"You got the job? Good for you!", exampleCn:"你拿到工作了？真为你高兴！", scene:"", cat:"tv"},
  {id:"tv079", word:"take it easy", phonetic:"/teɪk ɪt ˈiːzi/", pos:"phr.", cn:"放轻松；慢慢来", tip:"也用作告别“保重”", exampleEn:"Take it easy, we have time.", exampleCn:"放轻松，我们有时间。", scene:"", cat:"tv"},
  {id:"tv080", word:"sort of", phonetic:"/sɔːrt əv/", pos:"phr.", cn:"有点；算是吧", tip:"= kind of，软化", exampleEn:"I sort of like him.", exampleCn:"我算是有点喜欢他。", scene:"", cat:"tv"},

  // ===== 日常生活 (cat: life) =====
  // -- 食 --
  {id:"life001", word:"grocery", phonetic:"/ˈɡroʊsəri/", pos:"n.", cn:"食品杂货", tip:"grocery store 杂货店", exampleEn:"I need to buy some groceries.", exampleCn:"我得买点食品杂货。", scene:"", cat:"life"},
  {id:"life002", word:"recipe", phonetic:"/ˈresəpi/", pos:"n.", cn:"食谱；菜谱", tip:"别读成 re-cipe", exampleEn:"This recipe is really easy.", exampleCn:"这个食谱很简单。", scene:"", cat:"life"},
  {id:"life003", word:"ingredient", phonetic:"/ɪnˈɡriːdiənt/", pos:"n.", cn:"原料；食材", tip:"做菜要的东西", exampleEn:"Mix all the ingredients together.", exampleCn:"把所有食材混在一起。", scene:"", cat:"life"},
  {id:"life004", word:"leftover", phonetic:"/ˈleftoʊvər/", pos:"n.", cn:"剩饭剩菜", tip:"常用复数 leftovers", exampleEn:"We had leftovers for dinner.", exampleCn:"我们晚饭吃的剩菜。", scene:"", cat:"life"},
  {id:"life005", word:"takeout", phonetic:"/ˈteɪkaʊt/", pos:"n.", cn:"外卖", tip:"美式 takeout，英式 takeaway", exampleEn:"Let's order takeout tonight.", exampleCn:"今晚点外卖吧。", scene:"", cat:"life"},
  {id:"life006", word:"snack", phonetic:"/snæk/", pos:"n.", cn:"零食；点心", tip:"正餐之外吃的", exampleEn:"Grab a snack if you're hungry.", exampleCn:"饿了就拿点零食。", scene:"", cat:"life"},
  {id:"life007", word:"spicy", phonetic:"/ˈspaɪsi/", pos:"adj.", cn:"辣的", tip:"形容辣味", exampleEn:"This soup is too spicy for me.", exampleCn:"这汤对我太辣了。", scene:"", cat:"life"},
  {id:"life008", word:"thirsty", phonetic:"/ˈθɜːrsti/", pos:"adj.", cn:"渴的", tip:"hungry 饿 / thirsty 渴", exampleEn:"I'm thirsty, can I have some water?", exampleCn:"我渴了，能喝点水吗？", scene:"", cat:"life"},
  // -- 衣 --
  {id:"life009", word:"outfit", phonetic:"/ˈaʊtfɪt/", pos:"n.", cn:"一身行头；穿搭", tip:"整套搭配", exampleEn:"I love your outfit today.", exampleCn:"我喜欢你今天的穿搭。", scene:"", cat:"life"},
  {id:"life010", word:"laundry", phonetic:"/ˈlɔːndri/", pos:"n.", cn:"要洗的衣物；洗衣", tip:"do the laundry 洗衣服", exampleEn:"I have to do the laundry today.", exampleCn:"我今天得洗衣服。", scene:"", cat:"life"},
  {id:"life011", word:"fit", phonetic:"/fɪt/", pos:"v.", cn:"合身；适合", tip:"These jeans fit well 这裤子合身", exampleEn:"This shirt doesn't fit me.", exampleCn:"这件衬衫我穿不合身。", scene:"", cat:"life"},
  {id:"life012", word:"brand", phonetic:"/brænd/", pos:"n.", cn:"品牌", tip:"name brand 名牌", exampleEn:"What brand are these shoes?", exampleCn:"这鞋什么牌子的？", scene:"", cat:"life"},
  // -- 住 --
  {id:"life013", word:"rent", phonetic:"/rent/", pos:"n./v.", cn:"租金；租", tip:"pay the rent 付房租", exampleEn:"The rent is due next week.", exampleCn:"房租下周到期。", scene:"", cat:"life"},
  {id:"life014", word:"landlord", phonetic:"/ˈlændlɔːrd/", pos:"n.", cn:"房东", tip:"女房东 landlady", exampleEn:"My landlord raised the rent again.", exampleCn:"我房东又涨房租了。", scene:"", cat:"life"},
  {id:"life015", word:"furniture", phonetic:"/ˈfɜːrnɪtʃər/", pos:"n.", cn:"家具", tip:"不可数，没有复数", exampleEn:"We need to buy some furniture.", exampleCn:"我们得买些家具。", scene:"", cat:"life"},
  {id:"life016", word:"chore", phonetic:"/tʃɔːr/", pos:"n.", cn:"家务杂活", tip:"household chores 家务", exampleEn:"Doing chores takes all weekend.", exampleCn:"做家务占了整个周末。", scene:"", cat:"life"},
  {id:"life017", word:"trash", phonetic:"/træʃ/", pos:"n.", cn:"垃圾", tip:"take out the trash 倒垃圾", exampleEn:"Can you take out the trash?", exampleCn:"你能去倒垃圾吗？", scene:"", cat:"life"},
  {id:"life018", word:"plug", phonetic:"/plʌɡ/", pos:"n./v.", cn:"插头；插上", tip:"plug in 插电", exampleEn:"Plug in your phone to charge it.", exampleCn:"把手机插上充电。", scene:"", cat:"life"},
  {id:"life019", word:"leak", phonetic:"/liːk/", pos:"v./n.", cn:"漏；泄漏", tip:"水管漏水/信息泄露", exampleEn:"The faucet is leaking again.", exampleCn:"水龙头又漏水了。", scene:"信息安全里也指数据“泄漏”", cat:"life"},
  // -- 行 / 出门 --
  {id:"life020", word:"commute", phonetic:"/kəˈmjuːt/", pos:"n./v.", cn:"通勤", tip:"上下班路程", exampleEn:"My commute takes an hour.", exampleCn:"我通勤要一小时。", scene:"", cat:"life"},
  {id:"life021", word:"traffic", phonetic:"/ˈtræfɪk/", pos:"n.", cn:"交通；车流", tip:"heavy traffic 堵车", exampleEn:"The traffic is terrible today.", exampleCn:"今天堵得厉害。", scene:"", cat:"life"},
  {id:"life022", word:"subway", phonetic:"/ˈsʌbweɪ/", pos:"n.", cn:"地铁", tip:"美式 subway，英式 underground/tube", exampleEn:"Take the subway, it's faster.", exampleCn:"坐地铁吧，更快。", scene:"", cat:"life"},
  {id:"life023", word:"fare", phonetic:"/fer/", pos:"n.", cn:"车费；票价", tip:"交通费用", exampleEn:"The bus fare went up.", exampleCn:"公交车费涨了。", scene:"", cat:"life"},
  {id:"life024", word:"detour", phonetic:"/ˈdiːtʊr/", pos:"n.", cn:"绕路", tip:"take a detour 绕道", exampleEn:"We took a detour around the construction.", exampleCn:"我们绕开施工区走了。", scene:"", cat:"life"},
  {id:"life025", word:"parking", phonetic:"/ˈpɑːrkɪŋ/", pos:"n.", cn:"停车（位）", tip:"parking lot 停车场", exampleEn:"Parking is hard to find downtown.", exampleCn:"市中心很难找停车位。", scene:"", cat:"life"},
  // -- 购物 / 钱 --
  {id:"life026", word:"receipt", phonetic:"/rɪˈsiːt/", pos:"n.", cn:"收据；小票", tip:"p 不发音", exampleEn:"Keep the receipt in case you return it.", exampleCn:"留好小票以防退货。", scene:"", cat:"life"},
  {id:"life027", word:"refund", phonetic:"/ˈriːfʌnd/", pos:"n./v.", cn:"退款", tip:"get a refund 拿到退款", exampleEn:"I'd like a refund, please.", exampleCn:"我想退款，谢谢。", scene:"", cat:"life"},
  {id:"life028", word:"discount", phonetic:"/ˈdɪskaʊnt/", pos:"n.", cn:"折扣", tip:"on discount 打折中", exampleEn:"Is there any discount on this?", exampleCn:"这个有折扣吗？", scene:"", cat:"life"},
  {id:"life029", word:"afford", phonetic:"/əˈfɔːrd/", pos:"v.", cn:"负担得起", tip:"can't afford 买不起", exampleEn:"I can't afford a new car.", exampleCn:"我买不起新车。", scene:"", cat:"life"},
  {id:"life030", word:"budget", phonetic:"/ˈbʌdʒɪt/", pos:"n.", cn:"预算", tip:"on a budget 手头紧", exampleEn:"We're on a tight budget this month.", exampleCn:"我们这个月预算很紧。", scene:"", cat:"life"},
  {id:"life031", word:"cash", phonetic:"/kæʃ/", pos:"n.", cn:"现金", tip:"pay in cash 付现金", exampleEn:"Do you take cash or card?", exampleCn:"你们收现金还是卡？", scene:"", cat:"life"},
  {id:"life032", word:"bill", phonetic:"/bɪl/", pos:"n.", cn:"账单；钞票", tip:"电费水费等账单", exampleEn:"I forgot to pay the electricity bill.", exampleCn:"我忘付电费了。", scene:"", cat:"life"},
  // -- 社交 / 关系 --
  {id:"life033", word:"roommate", phonetic:"/ˈruːmmeɪt/", pos:"n.", cn:"室友", tip:"合租/同宿舍", exampleEn:"My roommate is really tidy.", exampleCn:"我室友很爱干净。", scene:"", cat:"life"},
  {id:"life034", word:"neighbor", phonetic:"/ˈneɪbər/", pos:"n.", cn:"邻居", tip:"英式拼 neighbour", exampleEn:"Our neighbors are very friendly.", exampleCn:"我们邻居很友好。", scene:"", cat:"life"},
  {id:"life035", word:"colleague", phonetic:"/ˈkɑːliːɡ/", pos:"n.", cn:"同事", tip:"= coworker", exampleEn:"She's a colleague from work.", exampleCn:"她是我同事。", scene:"", cat:"life"},
  {id:"life036", word:"invite", phonetic:"/ɪnˈvaɪt/", pos:"v.", cn:"邀请", tip:"名词 invitation", exampleEn:"They invited us to dinner.", exampleCn:"他们邀我们吃晚饭。", scene:"", cat:"life"},
  {id:"life037", word:"apologize", phonetic:"/əˈpɑːlədʒaɪz/", pos:"v.", cn:"道歉", tip:"apologize to sb 向某人道歉", exampleEn:"He apologized for being late.", exampleCn:"他为迟到道歉。", scene:"", cat:"life"},
  {id:"life038", word:"favor", phonetic:"/ˈfeɪvər/", pos:"n.", cn:"帮忙；恩惠", tip:"do me a favor 帮个忙", exampleEn:"Can you do me a favor?", exampleCn:"你能帮我个忙吗？", scene:"", cat:"life"},
  {id:"life039", word:"promise", phonetic:"/ˈprɑːmɪs/", pos:"v./n.", cn:"承诺；保证", tip:"keep a promise 守诺", exampleEn:"You promised to help me.", exampleCn:"你答应过帮我的。", scene:"", cat:"life"},
  {id:"life040", word:"argue", phonetic:"/ˈɑːrɡjuː/", pos:"v.", cn:"争吵；争论", tip:"名词 argument", exampleEn:"They argue about money a lot.", exampleCn:"他们经常为钱争吵。", scene:"", cat:"life"},
  // -- 身体 / 健康 --
  {id:"life041", word:"appointment", phonetic:"/əˈpɔɪntmənt/", pos:"n.", cn:"预约；约会", tip:"看医生/约见", exampleEn:"I have a doctor's appointment at 3.", exampleCn:"我三点有个医生预约。", scene:"", cat:"life"},
  {id:"life042", word:"prescription", phonetic:"/prɪˈskrɪpʃn/", pos:"n.", cn:"处方", tip:"医生开的药方", exampleEn:"Pick up your prescription at the pharmacy.", exampleCn:"去药房取你的处方药。", scene:"", cat:"life"},
  {id:"life043", word:"symptom", phonetic:"/ˈsɪmptəm/", pos:"n.", cn:"症状", tip:"生病的表现", exampleEn:"What are your symptoms?", exampleCn:"你有什么症状？", scene:"", cat:"life"},
  {id:"life044", word:"sore", phonetic:"/sɔːr/", pos:"adj.", cn:"酸痛的", tip:"sore throat 嗓子疼", exampleEn:"My legs are sore from running.", exampleCn:"我跑步跑得腿酸。", scene:"", cat:"life"},
  {id:"life045", word:"dizzy", phonetic:"/ˈdɪzi/", pos:"adj.", cn:"头晕的", tip:"feel dizzy 感到晕", exampleEn:"I feel dizzy when I stand up.", exampleCn:"我一站起来就头晕。", scene:"", cat:"life"},
  {id:"life046", word:"workout", phonetic:"/ˈwɜːrkaʊt/", pos:"n.", cn:"锻炼（一次）", tip:"a good workout 练得很好", exampleEn:"I had a great workout today.", exampleCn:"我今天练得很爽。", scene:"健身里指一次“训练”", cat:"life"},
  // -- 时间 / 安排 --
  {id:"life047", word:"schedule", phonetic:"/ˈskedʒuːl/", pos:"n./v.", cn:"日程；安排", tip:"美式 sked-，英式 shed-", exampleEn:"My schedule is full this week.", exampleCn:"我这周日程满了。", scene:"", cat:"life"},
  {id:"life048", word:"deadline", phonetic:"/ˈdedlaɪn/", pos:"n.", cn:"截止日期", tip:"meet the deadline 赶上截止", exampleEn:"The deadline is this Friday.", exampleCn:"截止日期是这周五。", scene:"", cat:"life"},
  {id:"life049", word:"reschedule", phonetic:"/ˌriːˈskedʒuːl/", pos:"v.", cn:"改期", tip:"re + schedule 重新安排", exampleEn:"Can we reschedule the meeting?", exampleCn:"我们能改下会议时间吗？", scene:"", cat:"life"},
  {id:"life050", word:"available", phonetic:"/əˈveɪləbl/", pos:"adj.", cn:"有空的；可用的", tip:"Are you available? 你有空吗", exampleEn:"Are you available tomorrow?", exampleCn:"你明天有空吗？", scene:"", cat:"life"},
  {id:"life051", word:"errand", phonetic:"/ˈerənd/", pos:"n.", cn:"差事；跑腿", tip:"run errands 出门办事", exampleEn:"I have a few errands to run.", exampleCn:"我有几件事要去办。", scene:"", cat:"life"},
  // -- 天气 / 环境 --
  {id:"life052", word:"forecast", phonetic:"/ˈfɔːrkæst/", pos:"n.", cn:"预报", tip:"weather forecast 天气预报", exampleEn:"The forecast says it'll rain.", exampleCn:"预报说会下雨。", scene:"", cat:"life"},
  {id:"life053", word:"humid", phonetic:"/ˈhjuːmɪd/", pos:"adj.", cn:"潮湿的", tip:"闷热潮湿", exampleEn:"It's so humid in summer here.", exampleCn:"这儿夏天很潮湿。", scene:"", cat:"life"},
  {id:"life054", word:"freezing", phonetic:"/ˈfriːzɪŋ/", pos:"adj.", cn:"冻死了", tip:"夸张说很冷", exampleEn:"It's freezing outside, bundle up.", exampleCn:"外面冻死了，多穿点。", scene:"", cat:"life"},
  // -- 杂项高频 --
  {id:"life055", word:"charger", phonetic:"/ˈtʃɑːrdʒər/", pos:"n.", cn:"充电器", tip:"phone charger 手机充电器", exampleEn:"Did you bring your charger?", exampleCn:"你带充电器了吗？", scene:"", cat:"life"},
  {id:"life056", word:"battery", phonetic:"/ˈbætəri/", pos:"n.", cn:"电池；电量", tip:"low battery 电量低", exampleEn:"My phone battery is almost dead.", exampleCn:"我手机快没电了。", scene:"", cat:"life"},
  {id:"life057", word:"borrow", phonetic:"/ˈbɔːroʊ/", pos:"v.", cn:"借（进）", tip:"borrow 借进，lend 借出", exampleEn:"Can I borrow your pen?", exampleCn:"我能借你的笔吗？", scene:"", cat:"life"},
  {id:"life058", word:"lend", phonetic:"/lend/", pos:"v.", cn:"借（出）", tip:"lend sb sth 把东西借给某人", exampleEn:"Can you lend me ten bucks?", exampleCn:"你能借我十块钱吗？", scene:"", cat:"life"},
  {id:"life059", word:"spare", phonetic:"/sper/", pos:"adj./v.", cn:"备用的；抽出（时间）", tip:"spare key 备用钥匙；spare time 空闲", exampleEn:"Do you have a spare charger?", exampleCn:"你有备用充电器吗？", scene:"", cat:"life"},
  {id:"life060", word:"stuff", phonetic:"/stʌf/", pos:"v.", cn:"塞满；填", tip:"作动词：塞进去", exampleEn:"She stuffed everything into one bag.", exampleCn:"她把所有东西塞进一个包。", scene:"作名词时指“东西”（已在影视口语收录）", cat:"life"},

  // ========== 职场商务 (cat: biz) ==========
  {id:"biz001", word:"agenda", phonetic:"/əˈdʒendə/", pos:"n.", cn:"议程；议事日程", tip:"开会前发的那份「今天聊什么」清单", exampleEn:"Can you send the agenda before the meeting?", exampleCn:"能在会前把议程发一下吗？", scene:"", cat:"biz"},
  {id:"biz002", word:"minutes", phonetic:"/ˈmɪnɪts/", pos:"n.", cn:"会议记录", tip:"复数才是「会议纪要」，和「分钟」是两回事", exampleEn:"I'll write up the minutes and share them today.", exampleCn:"我今天整理好会议记录发给大家。", scene:"", cat:"biz"},
  {id:"biz003", word:"stakeholder", phonetic:"/ˈsteɪkhoʊldər/", pos:"n.", cn:"利益相关方", tip:"项目里所有「会被影响、说得上话」的人", exampleEn:"We need to get all the stakeholders on the same page.", exampleCn:"我们得让所有相关方达成一致。", scene:"", cat:"biz"},
  {id:"biz004", word:"deliverable", phonetic:"/dɪˈlɪvərəbl/", pos:"n.", cn:"交付物", tip:"这个阶段最后要交出来的东西", exampleEn:"The final deliverable is due next Friday.", exampleCn:"最终交付物下周五截止。", scene:"", cat:"biz"},
  {id:"biz005", word:"milestone", phonetic:"/ˈmaɪlstoʊn/", pos:"n.", cn:"里程碑；阶段目标", tip:"项目排期表上的关键节点", exampleEn:"We hit our first milestone ahead of schedule.", exampleCn:"我们提前完成了第一个里程碑。", scene:"", cat:"biz"},
  {id:"biz006", word:"scope", phonetic:"/skoʊp/", pos:"n./v.", cn:"范围；界定范围", tip:"scope creep 指需求不断膨胀，职场高频吐槽词", exampleEn:"That feature is outside the scope of this release.", exampleCn:"那个功能不在这个版本的范围内。", scene:"", cat:"biz"},
  {id:"biz007", word:"priority", phonetic:"/praɪˈɔːrəti/", pos:"n.", cn:"优先级", tip:"top priority 最高优先级；prioritize 是动词", exampleEn:"Let's agree on priorities before we start coding.", exampleCn:"动手写代码前先把优先级定下来。", scene:"", cat:"biz"},
  {id:"biz008", word:"blocker", phonetic:"/ˈblɑːkər/", pos:"n.", cn:"阻塞问题；卡点", tip:"站会上最常说的一个词：我被什么卡住了", exampleEn:"My only blocker is waiting on the API key.", exampleCn:"我唯一的卡点是在等 API key。", scene:"", cat:"biz"},
  {id:"biz009", word:"bandwidth", phonetic:"/ˈbændwɪdθ/", pos:"n.", cn:"精力；余力", tip:"职场里几乎不指网速，指「有没有空接活」", exampleEn:"I don't have the bandwidth to take that on this week.", exampleCn:"这周我没精力再接那个活了。", scene:"技术语境下才指「带宽」", cat:"biz"},
  {id:"biz010", word:"sync", phonetic:"/sɪŋk/", pos:"v./n.", cn:"同步；碰头（会）", tip:"a quick sync 指简短的对齐会", exampleEn:"Let's sync on this tomorrow morning.", exampleCn:"我们明天上午对一下这件事。", scene:"", cat:"biz"},
  {id:"biz011", word:"standup", phonetic:"/ˈstændʌp/", pos:"n.", cn:"站会；每日晨会", tip:"敏捷开发里每天十几分钟的短会", exampleEn:"I'll bring it up at standup tomorrow.", exampleCn:"我明天站会上提一下。", scene:"", cat:"biz"},
  {id:"biz012", word:"retro", phonetic:"/ˈretroʊ/", pos:"n.", cn:"复盘会", tip:"retrospective 的简称，迭代结束后聊哪里能改进", exampleEn:"We talked about the incident in the retro.", exampleCn:"我们在复盘会上聊了那次故障。", scene:"", cat:"biz"},
  {id:"biz013", word:"onboarding", phonetic:"/ˈɑːnbɔːrdɪŋ/", pos:"n.", cn:"入职引导；新手上手", tip:"也指产品让新用户上手的流程", exampleEn:"The onboarding docs saved me a lot of time.", exampleCn:"入职文档帮我省了很多时间。", scene:"", cat:"biz"},
  {id:"biz014", word:"headcount", phonetic:"/ˈhedkaʊnt/", pos:"n.", cn:"人员编制；招聘名额", tip:"「有没有 headcount」= 还能不能招人", exampleEn:"We got headcount for two more engineers.", exampleCn:"我们拿到了再招两个工程师的名额。", scene:"", cat:"biz"},
  {id:"biz015", word:"promotion", phonetic:"/prəˈmoʊʃn/", pos:"n.", cn:"晋升；促销", tip:"职场指升职；商业语境指促销活动", exampleEn:"She got a promotion after leading that project.", exampleCn:"她带完那个项目后升职了。", scene:"电商语境指「促销」", cat:"biz"},
  {id:"biz016", word:"appraisal", phonetic:"/əˈpreɪzl/", pos:"n.", cn:"绩效评估", tip:"performance appraisal / review 年终考评", exampleEn:"My appraisal is scheduled for next month.", exampleCn:"我的绩效评估安排在下个月。", scene:"", cat:"biz"},
  {id:"biz017", word:"feedback", phonetic:"/ˈfiːdbæk/", pos:"n.", cn:"反馈；意见", tip:"不可数，别说 a feedback，用 some feedback", exampleEn:"Thanks for the honest feedback on my design.", exampleCn:"谢谢你对我方案的坦诚反馈。", scene:"", cat:"biz"},
  {id:"biz018", word:"escalate", phonetic:"/ˈeskəleɪt/", pos:"v.", cn:"上报；升级处理", tip:"自己搞不定，往上级或更高优先级推", exampleEn:"If it's still broken tomorrow, we'll escalate it.", exampleCn:"如果明天还没修好，我们就上报。", scene:"", cat:"biz"},
  {id:"biz019", word:"delegate", phonetic:"/ˈdelɪɡeɪt/", pos:"v./n.", cn:"委派；代表", tip:"动词重音在前，名词指「代表」", exampleEn:"A good lead knows when to delegate.", exampleCn:"好的负责人知道什么时候该放权。", scene:"", cat:"biz"},
  {id:"biz020", word:"align", phonetic:"/əˈlaɪn/", pos:"v.", cn:"对齐；达成一致", tip:"align on sth 就某事统一意见，职场超高频", exampleEn:"Let's align on the timeline first.", exampleCn:"我们先把时间线对齐。", scene:"", cat:"biz"},
  {id:"biz021", word:"leverage", phonetic:"/ˈlevərɪdʒ/", pos:"v./n.", cn:"利用；借力", tip:"比 use 更「商务腔」，会议里很爱用", exampleEn:"We can leverage the existing infrastructure.", exampleCn:"我们可以利用现有的基础设施。", scene:"金融语境指「杠杆」", cat:"biz"},
  {id:"biz022", word:"streamline", phonetic:"/ˈstriːmlaɪn/", pos:"v.", cn:"精简；优化流程", tip:"把啰嗦的流程砍短", exampleEn:"This tool streamlines our review process.", exampleCn:"这个工具精简了我们的评审流程。", scene:"", cat:"biz"},
  {id:"biz023", word:"proposal", phonetic:"/prəˈpoʊzl/", pos:"n.", cn:"提案；方案", tip:"propose 是动词", exampleEn:"I wrote up a proposal for the new architecture.", exampleCn:"我写了一份新架构的提案。", scene:"", cat:"biz"},
  {id:"biz024", word:"quarterly", phonetic:"/ˈkwɔːrtərli/", pos:"adj./adv.", cn:"季度的；每季度", tip:"Q1-Q4 就是四个 quarter", exampleEn:"We review the roadmap quarterly.", exampleCn:"我们每季度评审一次路线图。", scene:"", cat:"biz"},
  {id:"biz025", word:"revenue", phonetic:"/ˈrevənuː/", pos:"n.", cn:"营收；收入", tip:"公司层面的收入，个人收入用 income", exampleEn:"Revenue grew faster than we expected.", exampleCn:"营收增长比我们预期的快。", scene:"", cat:"biz"},
  {id:"biz026", word:"invoice", phonetic:"/ˈɪnvɔɪs/", pos:"n./v.", cn:"发票；账单", tip:"和中国的「发票」不完全一样，更接近收款单", exampleEn:"I'll send the invoice at the end of the month.", exampleCn:"我月底把账单发过去。", scene:"", cat:"biz"},
  {id:"biz027", word:"contract", phonetic:"/ˈkɑːntrækt/", pos:"n.", cn:"合同", tip:"名词重音在前，动词 contract 重音在后（收缩）", exampleEn:"Read the contract carefully before you sign.", exampleCn:"签之前把合同仔细读一遍。", scene:"", cat:"biz"},
  {id:"biz028", word:"vendor", phonetic:"/ˈvendər/", pos:"n.", cn:"供应商；厂商", tip:"技术圈也指云服务/软件提供方", exampleEn:"We're locked into one vendor right now.", exampleCn:"我们目前被绑定在一家供应商上。", scene:"", cat:"biz"},
  {id:"biz029", word:"client", phonetic:"/ˈklaɪənt/", pos:"n.", cn:"客户；委托方", tip:"和 customer 的区别：client 多为长期服务关系", exampleEn:"The client asked for one more round of changes.", exampleCn:"客户又要求改一轮。", scene:"技术语境指「客户端」（已在科技开发收录）", cat:"biz"},
  {id:"biz030", word:"negotiate", phonetic:"/nɪˈɡoʊʃieɪt/", pos:"v.", cn:"谈判；协商", tip:"negotiate salary 谈薪，非常实用", exampleEn:"Don't be afraid to negotiate your offer.", exampleCn:"别不敢谈你的 offer。", scene:"", cat:"biz"},
  {id:"biz031", word:"compromise", phonetic:"/ˈkɑːmprəmaɪz/", pos:"n./v.", cn:"妥协；折中", tip:"安全语境里 compromised 指「被攻陷」", exampleEn:"We reached a compromise on the deadline.", exampleCn:"我们在截止日期上达成了折中。", scene:"安全语境指系统「被入侵」", cat:"biz"},
  {id:"biz032", word:"consensus", phonetic:"/kənˈsensəs/", pos:"n.", cn:"共识", tip:"reach a consensus 达成共识", exampleEn:"There's no consensus on which framework to use.", exampleCn:"用哪个框架还没有共识。", scene:"", cat:"biz"},
  {id:"biz033", word:"initiative", phonetic:"/ɪˈnɪʃətɪv/", pos:"n.", cn:"主动性；倡议项目", tip:"take the initiative 主动去做", exampleEn:"She took the initiative to fix the flaky tests.", exampleCn:"她主动把那些不稳定的测试修好了。", scene:"", cat:"biz"},
  {id:"biz034", word:"accountable", phonetic:"/əˈkaʊntəbl/", pos:"adj.", cn:"负责的；需担责的", tip:"be accountable for sth 对某事负责到底", exampleEn:"Who is accountable for this service?", exampleCn:"这个服务谁负责？", scene:"", cat:"biz"},
  {id:"biz035", word:"workload", phonetic:"/ˈwɜːrkloʊd/", pos:"n.", cn:"工作量", tip:"抱怨活多时最常用的词", exampleEn:"My workload has doubled since the layoffs.", exampleCn:"裁员之后我的工作量翻倍了。", scene:"", cat:"biz"},
  {id:"biz036", word:"overtime", phonetic:"/ˈoʊvərtaɪm/", pos:"n./adv.", cn:"加班", tip:"work overtime 加班；OT 是缩写", exampleEn:"I worked overtime three nights in a row.", exampleCn:"我连着加了三个晚上的班。", scene:"", cat:"biz"},
  {id:"biz037", word:"remote", phonetic:"/rɪˈmoʊt/", pos:"adj.", cn:"远程的", tip:"work remotely 远程办公；fully remote 全远程", exampleEn:"The team has been fully remote since 2020.", exampleCn:"这个团队从 2020 年起就全远程了。", scene:"Git 里指「远程仓库」", cat:"biz"},
  {id:"biz038", word:"hybrid", phonetic:"/ˈhaɪbrɪd/", pos:"adj./n.", cn:"混合的（办公模式）", tip:"一周几天到岗、几天在家", exampleEn:"We're hybrid — three days in the office.", exampleCn:"我们是混合办公，一周去公司三天。", scene:"", cat:"biz"},
  {id:"biz039", word:"resign", phonetic:"/rɪˈzaɪn/", pos:"v.", cn:"辞职", tip:"hand in your resignation 递辞呈", exampleEn:"He resigned without another job lined up.", exampleCn:"他没找好下家就辞职了。", scene:"", cat:"biz"},
  {id:"biz040", word:"layoff", phonetic:"/ˈleɪɔːf/", pos:"n.", cn:"裁员", tip:"be laid off 被裁，和 fired（因过错开除）不同", exampleEn:"The layoffs hit the whole department.", exampleCn:"这次裁员波及了整个部门。", scene:"", cat:"biz"},
  {id:"biz041", word:"probation", phonetic:"/proʊˈbeɪʃn/", pos:"n.", cn:"试用期", tip:"probation period 试用期", exampleEn:"I'm still on probation for another month.", exampleCn:"我的试用期还有一个月。", scene:"", cat:"biz"},
  {id:"biz042", word:"resume", phonetic:"/ˈrezəmeɪ/", pos:"n.", cn:"简历", tip:"重音在前读「简历」；重音在后 /rɪˈzuːm/ 是「恢复」", exampleEn:"I updated my resume over the weekend.", exampleCn:"我周末更新了简历。", scene:"读作 /rɪˈzuːm/ 时是动词「继续、恢复」", cat:"biz"},
  {id:"biz043", word:"recruiter", phonetic:"/rɪˈkruːtər/", pos:"n.", cn:"招聘人员；猎头", tip:"LinkedIn 上主动找你的多半是 recruiter", exampleEn:"A recruiter reached out about a backend role.", exampleCn:"有个招聘的来找我聊一个后端岗位。", scene:"", cat:"biz"},
  {id:"biz044", word:"referral", phonetic:"/rɪˈfɜːrəl/", pos:"n.", cn:"内推", tip:"ask for a referral 求内推", exampleEn:"Could you give me a referral for that team?", exampleCn:"你能帮我内推那个团队吗？", scene:"", cat:"biz"},
  {id:"biz045", word:"benefit", phonetic:"/ˈbenɪfɪt/", pos:"n.", cn:"福利；好处", tip:"复数 benefits 特指公司福利（保险、年假等）", exampleEn:"The pay is average but the benefits are great.", exampleCn:"薪水一般，但福利很好。", scene:"", cat:"biz"},
  {id:"biz046", word:"reimburse", phonetic:"/ˌriːɪmˈbɜːrs/", pos:"v.", cn:"报销", tip:"名词 reimbursement；出差费用相关高频", exampleEn:"The company will reimburse your travel costs.", exampleCn:"公司会报销你的差旅费。", scene:"", cat:"biz"},
  {id:"biz047", word:"handover", phonetic:"/ˈhændoʊvər/", pos:"n.", cn:"工作交接", tip:"离职或休假前把活交出去", exampleEn:"Let's do the handover before you go on leave.", exampleCn:"你休假前我们把工作交接一下。", scene:"", cat:"biz"},
  {id:"biz048", word:"draft", phonetic:"/dræft/", pos:"n./v.", cn:"草稿；起草", tip:"first draft 初稿；邮件里的「草稿箱」也是它", exampleEn:"Here's a rough draft — tell me what you think.", exampleCn:"这是个初稿，你看看怎么样。", scene:"", cat:"biz"},
  {id:"biz049", word:"attach", phonetic:"/əˈtætʃ/", pos:"v.", cn:"附上；添加附件", tip:"attachment 附件；写邮件必备", exampleEn:"I've attached the report to this email.", exampleCn:"我把报告作为附件放在这封邮件里了。", scene:"", cat:"biz"},
  {id:"biz050", word:"cc", phonetic:"/ˌsiː ˈsiː/", pos:"v./n.", cn:"抄送", tip:"carbon copy 的缩写；bcc 是密送", exampleEn:"Please cc me on that thread.", exampleCn:"那个邮件串请抄送我一份。", scene:"", cat:"biz"},
  {id:"biz051", word:"follow up", phonetic:"/ˈfɑːloʊ ʌp/", pos:"phr.", cn:"跟进", tip:"follow up on sth / with sb，邮件结尾万能句", exampleEn:"I'll follow up with them next week.", exampleCn:"我下周跟他们跟进一下。", scene:"", cat:"biz"},
  {id:"biz052", word:"reach out", phonetic:"/riːtʃ aʊt/", pos:"phr.", cn:"主动联系", tip:"比 contact 更自然、更常用", exampleEn:"Feel free to reach out if you have questions.", exampleCn:"有问题随时找我。", scene:"", cat:"biz"},
  {id:"biz053", word:"touch base", phonetic:"/tʌtʃ beɪs/", pos:"phr.", cn:"简短沟通一下", tip:"棒球来的说法，指快速对个进度", exampleEn:"Let's touch base on Friday.", exampleCn:"我们周五简单对一下。", scene:"", cat:"biz"},
  {id:"biz054", word:"heads-up", phonetic:"/ˈhedz ʌp/", pos:"n.", cn:"提前告知；提个醒", tip:"give sb a heads-up 提前通知一声", exampleEn:"Thanks for the heads-up about the outage.", exampleCn:"谢谢你提前告诉我故障的事。", scene:"", cat:"biz"},
  {id:"biz055", word:"circle back", phonetic:"/ˈsɜːrkl bæk/", pos:"phr.", cn:"稍后再聊；回头再说", tip:"会议里想把话题往后放时说的", exampleEn:"Let's circle back to this after lunch.", exampleCn:"这个我们午饭后再聊。", scene:"", cat:"biz"},
  {id:"biz056", word:"loop in", phonetic:"/luːp ɪn/", pos:"phr.", cn:"把某人拉进来（知情）", tip:"keep sb in the loop 让某人保持知情", exampleEn:"Let me loop in the design team.", exampleCn:"我把设计团队拉进来。", scene:"", cat:"biz"},
  {id:"biz057", word:"take over", phonetic:"/teɪk ˈoʊvər/", pos:"phr.", cn:"接手；接管", tip:"take over from sb 从某人手里接过来", exampleEn:"Can you take over this ticket? I'm swamped.", exampleCn:"这个工单你能接手吗？我忙不过来了。", scene:"", cat:"biz"},
  {id:"biz058", word:"sign off", phonetic:"/saɪn ɔːf/", pos:"phr.", cn:"批准；签字确认", tip:"sign off on sth 对某事点头放行", exampleEn:"We need legal to sign off on this.", exampleCn:"这个需要法务批准。", scene:"", cat:"biz"},
  {id:"biz059", word:"swamped", phonetic:"/swɑːmpt/", pos:"adj.", cn:"忙得不可开交", tip:"比 busy 强烈，指被活淹没了", exampleEn:"I'm swamped this week — can it wait?", exampleCn:"我这周忙疯了，能缓缓吗？", scene:"", cat:"biz"},
  {id:"biz060", word:"pushback", phonetic:"/ˈpʊʃbæk/", pos:"n.", cn:"反对意见；抵触", tip:"get pushback 遭到反对", exampleEn:"We got a lot of pushback on that proposal.", exampleCn:"那个提案遭到了不少反对。", scene:"", cat:"biz"},

  // ========== 学术阅读 (cat: academic) ==========
  {id:"acad001", word:"abstract", phonetic:"/ˈæbstrækt/", pos:"n.", cn:"摘要", tip:"论文开头那段概括；读论文先读它", exampleEn:"I only had time to read the abstract.", exampleCn:"我只来得及读摘要。", scene:"作形容词时是「抽象的」", cat:"academic"},
  {id:"acad002", word:"hypothesis", phonetic:"/haɪˈpɑːθəsɪs/", pos:"n.", cn:"假设", tip:"复数 hypotheses，重音在第二音节", exampleEn:"The data supports our original hypothesis.", exampleCn:"数据支持我们最初的假设。", scene:"", cat:"academic"},
  {id:"acad003", word:"methodology", phonetic:"/ˌmeθəˈdɑːlədʒi/", pos:"n.", cn:"方法论；研究方法", tip:"论文里专门讲「怎么做的」那一节", exampleEn:"The methodology section explains how they collected data.", exampleCn:"方法论一节说明了他们如何收集数据。", scene:"", cat:"academic"},
  {id:"acad004", word:"empirical", phonetic:"/ɪmˈpɪrɪkl/", pos:"adj.", cn:"实证的；基于观测的", tip:"靠实验和数据说话，不是靠推理", exampleEn:"There's little empirical evidence for that claim.", exampleCn:"这个说法几乎没有实证依据。", scene:"", cat:"academic"},
  {id:"acad005", word:"qualitative", phonetic:"/ˈkwɑːlɪteɪtɪv/", pos:"adj.", cn:"定性的", tip:"描述性质，不量化；和 quantitative 成对记", exampleEn:"They ran qualitative interviews with ten users.", exampleCn:"他们对十位用户做了定性访谈。", scene:"", cat:"academic"},
  {id:"acad006", word:"quantitative", phonetic:"/ˈkwɑːntɪteɪtɪv/", pos:"adj.", cn:"定量的", tip:"能用数字衡量的", exampleEn:"We need quantitative data to back this up.", exampleCn:"我们需要定量数据来支撑这一点。", scene:"", cat:"academic"},
  {id:"acad007", word:"correlation", phonetic:"/ˌkɔːrəˈleɪʃn/", pos:"n.", cn:"相关性", tip:"名句：correlation is not causation（相关不等于因果）", exampleEn:"There's a strong correlation between the two.", exampleCn:"这两者之间有很强的相关性。", scene:"", cat:"academic"},
  {id:"acad008", word:"causal", phonetic:"/ˈkɔːzl/", pos:"adj.", cn:"因果的", tip:"causal relationship 因果关系；别和 casual 混", exampleEn:"They couldn't establish a causal link.", exampleCn:"他们无法确立因果联系。", scene:"", cat:"academic"},
  {id:"acad009", word:"sample", phonetic:"/ˈsæmpl/", pos:"n./v.", cn:"样本；抽样", tip:"sample size 样本量，看研究先看它", exampleEn:"The sample size was too small to be convincing.", exampleCn:"样本量太小，不够有说服力。", scene:"", cat:"academic"},
  {id:"acad010", word:"bias", phonetic:"/ˈbaɪəs/", pos:"n.", cn:"偏差；偏见", tip:"机器学习里也指模型偏差", exampleEn:"The study has an obvious selection bias.", exampleCn:"这项研究有明显的选择偏差。", scene:"神经网络里指「偏置项」", cat:"academic"},
  {id:"acad011", word:"significant", phonetic:"/sɪɡˈnɪfɪkənt/", pos:"adj.", cn:"显著的", tip:"统计里 statistically significant 有特定含义，不只是「重要」", exampleEn:"The difference was not statistically significant.", exampleCn:"这个差异在统计上并不显著。", scene:"", cat:"academic"},
  {id:"acad012", word:"threshold", phonetic:"/ˈθreʃhoʊld/", pos:"n.", cn:"阈值；门槛", tip:"超过这个数就触发某个判断", exampleEn:"Anything above this threshold triggers an alert.", exampleCn:"超过这个阈值就会触发告警。", scene:"", cat:"academic"},
  {id:"acad013", word:"criteria", phonetic:"/kraɪˈtɪriə/", pos:"n.", cn:"标准；准则", tip:"复数形式，单数是 criterion", exampleEn:"What criteria did you use to pick the models?", exampleCn:"你是按什么标准挑的这些模型？", scene:"", cat:"academic"},
  {id:"acad014", word:"framework", phonetic:"/ˈfreɪmwɜːrk/", pos:"n.", cn:"框架；理论体系", tip:"学术指理论框架，技术指代码框架", exampleEn:"They propose a framework for evaluating safety.", exampleCn:"他们提出了一套评估安全性的框架。", scene:"技术语境指 React 这类「开发框架」", cat:"academic"},
  {id:"acad015", word:"paradigm", phonetic:"/ˈpærədaɪm/", pos:"n.", cn:"范式", tip:"注意 g 不发音；paradigm shift 范式转变", exampleEn:"This marks a paradigm shift in the field.", exampleCn:"这标志着该领域的一次范式转变。", scene:"", cat:"academic"},
  {id:"acad016", word:"novel", phonetic:"/ˈnɑːvl/", pos:"adj.", cn:"新颖的；新的", tip:"论文里高频，不是「小说」的意思", exampleEn:"They introduce a novel approach to compression.", exampleCn:"他们提出了一种新颖的压缩方法。", scene:"作名词时是「小说」", cat:"academic"},
  {id:"acad017", word:"robust", phonetic:"/roʊˈbʌst/", pos:"adj.", cn:"稳健的；鲁棒的", tip:"换了条件也不崩，技术文档超高频", exampleEn:"The method is robust to noisy input.", exampleCn:"这个方法对噪声输入是稳健的。", scene:"", cat:"academic"},
  {id:"acad018", word:"plausible", phonetic:"/ˈplɔːzəbl/", pos:"adj.", cn:"看似合理的；说得通的", tip:"注意：合理但未必真，常带保留意味", exampleEn:"That's a plausible explanation, but unproven.", exampleCn:"这个解释说得通，但未经证实。", scene:"", cat:"academic"},
  {id:"acad019", word:"arbitrary", phonetic:"/ˈɑːrbɪtreri/", pos:"adj.", cn:"任意的；武断的", tip:"没有依据地随便定的", exampleEn:"The cutoff at 100 feels arbitrary.", exampleCn:"以 100 作为界限显得很武断。", scene:"", cat:"academic"},
  {id:"acad020", word:"explicit", phonetic:"/ɪkˈsplɪsɪt/", pos:"adj.", cn:"明确的；显式的", tip:"和 implicit 成对记；编程里指「显式声明」", exampleEn:"The docs are explicit about this limitation.", exampleCn:"文档对这个限制说得很明确。", scene:"", cat:"academic"},
  {id:"acad021", word:"implicit", phonetic:"/ɪmˈplɪsɪt/", pos:"adj.", cn:"隐含的；隐式的", tip:"没明说但暗含在里面", exampleEn:"There's an implicit assumption here.", exampleCn:"这里有一个隐含的假设。", scene:"", cat:"academic"},
  {id:"acad022", word:"subsequent", phonetic:"/ˈsʌbsɪkwənt/", pos:"adj.", cn:"随后的；后续的", tip:"subsequent to = after，书面语", exampleEn:"Subsequent tests confirmed the result.", exampleCn:"后续测试证实了这一结果。", scene:"", cat:"academic"},
  {id:"acad023", word:"preliminary", phonetic:"/prɪˈlɪməneri/", pos:"adj.", cn:"初步的", tip:"preliminary results 初步结果，常带「别下定论」的意思", exampleEn:"These are preliminary findings only.", exampleCn:"这些只是初步发现。", scene:"", cat:"academic"},
  {id:"acad024", word:"comprehensive", phonetic:"/ˌkɑːmprɪˈhensɪv/", pos:"adj.", cn:"全面的；综合的", tip:"覆盖得很完整", exampleEn:"They ran a comprehensive review of the literature.", exampleCn:"他们做了一次全面的文献综述。", scene:"", cat:"academic"},
  {id:"acad025", word:"substantial", phonetic:"/səbˈstænʃl/", pos:"adj.", cn:"大量的；可观的", tip:"比 big 更正式，强调分量足", exampleEn:"There was a substantial drop in latency.", exampleCn:"延迟有了大幅下降。", scene:"", cat:"academic"},
  {id:"acad026", word:"negligible", phonetic:"/ˈneɡlɪdʒəbl/", pos:"adj.", cn:"可忽略不计的", tip:"小到不用管；和 neglect（忽视）同源", exampleEn:"The overhead is negligible in practice.", exampleCn:"实际使用中开销可以忽略不计。", scene:"", cat:"academic"},
  {id:"acad027", word:"inherent", phonetic:"/ɪnˈhɪrənt/", pos:"adj.", cn:"固有的；内在的", tip:"天生就带的，去不掉的", exampleEn:"There's an inherent tradeoff between speed and accuracy.", exampleCn:"速度和准确率之间存在固有的取舍。", scene:"", cat:"academic"},
  {id:"acad028", word:"derive", phonetic:"/dɪˈraɪv/", pos:"v.", cn:"推导；得出", tip:"derive from 源自；数学里指「求导/推导」", exampleEn:"We can derive the formula from first principles.", exampleCn:"我们可以从第一性原理推导出这个公式。", scene:"", cat:"academic"},
  {id:"acad029", word:"infer", phonetic:"/ɪnˈfɜːr/", pos:"v.", cn:"推断", tip:"名词 inference；AI 里指模型「推理」", exampleEn:"We can infer user intent from the click pattern.", exampleCn:"我们可以从点击模式推断用户意图。", scene:"", cat:"academic"},
  {id:"acad030", word:"imply", phonetic:"/ɪmˈplaɪ/", pos:"v.", cn:"暗示；意味着", tip:"说话人 imply（暗示），听者 infer（推断）", exampleEn:"That doesn't imply the model is unsafe.", exampleCn:"这并不意味着模型不安全。", scene:"", cat:"academic"},
  {id:"acad031", word:"denote", phonetic:"/dɪˈnoʊt/", pos:"v.", cn:"表示；指代", tip:"论文里定义符号时常用：let x denote…", exampleEn:"Let n denote the number of samples.", exampleCn:"设 n 表示样本数量。", scene:"", cat:"academic"},
  {id:"acad032", word:"constitute", phonetic:"/ˈkɑːnstɪtuːt/", pos:"v.", cn:"构成；组成", tip:"A constitutes B：A 构成了 B", exampleEn:"These three parts constitute the whole system.", exampleCn:"这三部分构成了整个系统。", scene:"", cat:"academic"},
  {id:"acad033", word:"yield", phonetic:"/jiːld/", pos:"v./n.", cn:"产生；得出（结果）", tip:"Python 里 yield 是生成器关键字", exampleEn:"This approach yields better results on long inputs.", exampleCn:"这种方法在长输入上产生更好的结果。", scene:"编程中是生成器关键字；交通标志上指「让行」", cat:"academic"},
  {id:"acad034", word:"exhibit", phonetic:"/ɪɡˈzɪbɪt/", pos:"v.", cn:"表现出；显示", tip:"注意 h 不发音；比 show 正式", exampleEn:"Larger models exhibit this behavior more often.", exampleCn:"更大的模型更常表现出这种行为。", scene:"作名词指「展品、展览」", cat:"academic"},
  {id:"acad035", word:"underlying", phonetic:"/ˌʌndərˈlaɪɪŋ/", pos:"adj.", cn:"底层的；根本的", tip:"underlying cause 根本原因", exampleEn:"We never fixed the underlying problem.", exampleCn:"我们始终没解决根本问题。", scene:"", cat:"academic"},
  {id:"acad036", word:"respectively", phonetic:"/rɪˈspektɪvli/", pos:"adv.", cn:"分别地", tip:"按前面列举的顺序一一对应", exampleEn:"Accuracy was 91% and 87%, respectively.", exampleCn:"准确率分别为 91% 和 87%。", scene:"", cat:"academic"},
  {id:"acad037", word:"hence", phonetic:"/hens/", pos:"adv.", cn:"因此", tip:"比 so 正式，书面语常用", exampleEn:"The data was incomplete; hence the odd results.", exampleCn:"数据不完整，因此结果才这么奇怪。", scene:"", cat:"academic"},
  {id:"acad038", word:"thereby", phonetic:"/ˌðerˈbaɪ/", pos:"adv.", cn:"从而；由此", tip:"后面常接 -ing：thereby reducing…", exampleEn:"It caches results, thereby cutting response time.", exampleCn:"它缓存结果，从而缩短了响应时间。", scene:"", cat:"academic"},
  {id:"acad039", word:"whereas", phonetic:"/werˈæz/", pos:"conj.", cn:"然而；相比之下", tip:"用于对比两件事，比 but 正式", exampleEn:"Python is dynamic, whereas Rust is statically typed.", exampleCn:"Python 是动态类型，而 Rust 是静态类型。", scene:"", cat:"academic"},
  {id:"acad040", word:"albeit", phonetic:"/ˌɔːlˈbiːɪt/", pos:"conj.", cn:"尽管；虽然", tip:"= although，但只接短语不接完整句", exampleEn:"It works, albeit slowly.", exampleCn:"它能用，尽管慢了点。", scene:"", cat:"academic"},
  {id:"acad041", word:"namely", phonetic:"/ˈneɪmli/", pos:"adv.", cn:"即；也就是", tip:"后面具体点名是哪些", exampleEn:"Two issues remain, namely cost and latency.", exampleCn:"还剩两个问题，即成本和延迟。", scene:"", cat:"academic"},
  {id:"acad042", word:"notably", phonetic:"/ˈnoʊtəbli/", pos:"adv.", cn:"尤其；值得注意的是", tip:"引出最值得说的那个例子", exampleEn:"Several teams, notably ours, hit the same bug.", exampleCn:"好几个团队都碰到了同一个 bug，尤其是我们组。", scene:"", cat:"academic"},
  {id:"acad043", word:"literature", phonetic:"/ˈlɪtərətʃər/", pos:"n.", cn:"文献", tip:"学术里指某领域已有的研究，不是「文学」", exampleEn:"This is well documented in the literature.", exampleCn:"这一点在已有文献里有充分记载。", scene:"日常语境指「文学」", cat:"academic"},
  {id:"acad044", word:"cite", phonetic:"/saɪt/", pos:"v.", cn:"引用", tip:"名词 citation；和 site/sight 同音", exampleEn:"They cite over two hundred papers.", exampleCn:"他们引用了两百多篇论文。", scene:"", cat:"academic"},
  {id:"acad045", word:"replicate", phonetic:"/ˈreplɪkeɪt/", pos:"v.", cn:"复现；重复（实验）", tip:"别人能不能跑出同样结果，科研核心标准", exampleEn:"No one has been able to replicate their results.", exampleCn:"还没有人能复现他们的结果。", scene:"数据库里指「复制副本」", cat:"academic"},

  // ========== 新闻时事 (cat: news) ==========
  {id:"news001", word:"allegedly", phonetic:"/əˈledʒɪdli/", pos:"adv.", cn:"据称；据指控", tip:"新闻里表示「尚未证实」的免责用词", exampleEn:"The company allegedly ignored the warnings.", exampleCn:"据称该公司无视了这些警告。", scene:"", cat:"news"},
  {id:"news002", word:"amid", phonetic:"/əˈmɪd/", pos:"prep.", cn:"在……之中；在……背景下", tip:"新闻标题高频：amid concerns 在担忧声中", exampleEn:"The launch was delayed amid safety concerns.", exampleCn:"在安全担忧声中，发布被推迟。", scene:"", cat:"news"},
  {id:"news003", word:"surge", phonetic:"/sɜːrdʒ/", pos:"n./v.", cn:"激增；猛涨", tip:"股价、用户量暴涨都用它", exampleEn:"Downloads surged after the announcement.", exampleCn:"公告发布后下载量激增。", scene:"", cat:"news"},
  {id:"news004", word:"plunge", phonetic:"/plʌndʒ/", pos:"v./n.", cn:"暴跌；骤降", tip:"和 surge 正好相反，一涨一跌", exampleEn:"The stock plunged 20% in a single day.", exampleCn:"股价单日暴跌 20%。", scene:"", cat:"news"},
  {id:"news005", word:"probe", phonetic:"/proʊb/", pos:"n./v.", cn:"调查", tip:"新闻标题爱用它代替 investigation（更短）", exampleEn:"Regulators opened a probe into the company.", exampleCn:"监管机构对该公司展开调查。", scene:"", cat:"news"},
  {id:"news006", word:"crackdown", phonetic:"/ˈkrækdaʊn/", pos:"n.", cn:"严打；整治", tip:"crack down on sth 是动词形式", exampleEn:"There's been a crackdown on data scraping.", exampleCn:"针对数据抓取的整治已经开始。", scene:"", cat:"news"},
  {id:"news007", word:"sanction", phonetic:"/ˈsæŋkʃn/", pos:"n./v.", cn:"制裁", tip:"有趣：作动词也可指「批准」，看语境", exampleEn:"New sanctions target chip exports.", exampleCn:"新的制裁针对芯片出口。", scene:"正式语境下作动词可指「批准、认可」", cat:"news"},
  {id:"news008", word:"tariff", phonetic:"/ˈtærɪf/", pos:"n.", cn:"关税", tip:"贸易新闻核心词", exampleEn:"The new tariffs raised hardware prices.", exampleCn:"新关税抬高了硬件价格。", scene:"", cat:"news"},
  {id:"news009", word:"inflation", phonetic:"/ɪnˈfleɪʃn/", pos:"n.", cn:"通货膨胀", tip:"物价普涨、钱变毛", exampleEn:"Inflation has slowed for three months straight.", exampleCn:"通胀已连续三个月放缓。", scene:"", cat:"news"},
  {id:"news010", word:"recession", phonetic:"/rɪˈseʃn/", pos:"n.", cn:"经济衰退", tip:"通常指连续两季度经济负增长", exampleEn:"Hiring froze during the recession.", exampleCn:"经济衰退期间招聘冻结了。", scene:"", cat:"news"},
  {id:"news011", word:"lawsuit", phonetic:"/ˈlɔːsuːt/", pos:"n.", cn:"诉讼", tip:"file a lawsuit 提起诉讼", exampleEn:"They filed a lawsuit over the data breach.", exampleCn:"他们就数据泄露提起了诉讼。", scene:"", cat:"news"},
  {id:"news012", word:"regulator", phonetic:"/ˈreɡjuleɪtər/", pos:"n.", cn:"监管机构", tip:"科技新闻里天天出现", exampleEn:"Regulators are looking into the acquisition.", exampleCn:"监管机构正在审查这笔收购。", scene:"", cat:"news"},
  {id:"news013", word:"compliance", phonetic:"/kəmˈplaɪəns/", pos:"n.", cn:"合规", tip:"in compliance with 符合（法规）", exampleEn:"The feature was blocked for compliance reasons.", exampleCn:"这个功能因合规原因被叫停。", scene:"", cat:"news"},
  {id:"news014", word:"antitrust", phonetic:"/ˌæntiˈtrʌst/", pos:"adj./n.", cn:"反垄断的", tip:"大厂新闻常客", exampleEn:"The antitrust case could take years.", exampleCn:"这起反垄断案可能要拖好几年。", scene:"", cat:"news"},
  {id:"news015", word:"merger", phonetic:"/ˈmɜːrdʒər/", pos:"n.", cn:"合并；并购", tip:"和 Git 的 merge 同源，但这里指公司合并", exampleEn:"The merger was approved last quarter.", exampleCn:"这次合并在上季度获批。", scene:"", cat:"news"},
  {id:"news016", word:"acquisition", phonetic:"/ˌækwɪˈzɪʃn/", pos:"n.", cn:"收购", tip:"动词 acquire；M&A = 并购", exampleEn:"The acquisition cost them three billion dollars.", exampleCn:"这笔收购花了他们三十亿美元。", scene:"", cat:"news"},
  {id:"news017", word:"stake", phonetic:"/steɪk/", pos:"n.", cn:"股份；利害关系", tip:"a 10% stake 一成股份；at stake 岌岌可危", exampleEn:"They bought a minority stake in the startup.", exampleCn:"他们买下了这家创业公司的少数股份。", scene:"at stake 指「处于风险中」", cat:"news"},
  {id:"news018", word:"valuation", phonetic:"/ˌvæljuˈeɪʃn/", pos:"n.", cn:"估值", tip:"创业公司值多少钱", exampleEn:"The startup hit a $2 billion valuation.", exampleCn:"这家创业公司估值达到 20 亿美元。", scene:"", cat:"news"},
  {id:"news019", word:"startup", phonetic:"/ˈstɑːrtʌp/", pos:"n.", cn:"创业公司", tip:"技术语境下也指程序「启动」", exampleEn:"He left a big tech job to join a startup.", exampleCn:"他从大厂离职去了一家创业公司。", scene:"技术语境指程序「启动」过程", cat:"news"},
  {id:"news020", word:"funding", phonetic:"/ˈfʌndɪŋ/", pos:"n.", cn:"融资；资金", tip:"Series A/B 指融资轮次", exampleEn:"They raised Series B funding last month.", exampleCn:"他们上个月完成了 B 轮融资。", scene:"", cat:"news"},
  {id:"news021", word:"investor", phonetic:"/ɪnˈvestər/", pos:"n.", cn:"投资人", tip:"VC = 风险投资机构", exampleEn:"Investors were spooked by the earnings report.", exampleCn:"财报把投资人吓到了。", scene:"", cat:"news"},
  {id:"news022", word:"pledge", phonetic:"/pledʒ/", pos:"v./n.", cn:"承诺；保证", tip:"公开场合的正式承诺", exampleEn:"The company pledged to cut emissions by half.", exampleCn:"该公司承诺将排放减半。", scene:"", cat:"news"},
  {id:"news023", word:"unveil", phonetic:"/ˌʌnˈveɪl/", pos:"v.", cn:"发布；揭晓", tip:"发布会专用动词，字面是「揭开面纱」", exampleEn:"They unveiled the new model at the keynote.", exampleCn:"他们在主题演讲上发布了新模型。", scene:"", cat:"news"},
  {id:"news024", word:"roll out", phonetic:"/roʊl aʊt/", pos:"phr.", cn:"推出；分批上线", tip:"技术上常指灰度发布", exampleEn:"The update will roll out over the next week.", exampleCn:"这次更新会在下周内陆续推送。", scene:"", cat:"news"},
  {id:"news025", word:"halt", phonetic:"/hɔːlt/", pos:"v./n.", cn:"暂停；中止", tip:"比 stop 更正式、更突然", exampleEn:"The rollout was halted after user reports.", exampleCn:"在收到用户反馈后，推送被叫停。", scene:"", cat:"news"},
  {id:"news026", word:"ban", phonetic:"/bæn/", pos:"v./n.", cn:"禁止；封禁", tip:"账号被封也用它", exampleEn:"Several countries banned the app outright.", exampleCn:"好几个国家直接封禁了这款应用。", scene:"", cat:"news"},
  {id:"news027", word:"breach", phonetic:"/briːtʃ/", pos:"n./v.", cn:"泄露；违反", tip:"data breach 数据泄露，安全新闻高频", exampleEn:"The breach exposed millions of accounts.", exampleCn:"这次泄露波及数百万账号。", scene:"", cat:"news"},
  {id:"news028", word:"outage", phonetic:"/ˈaʊtɪdʒ/", pos:"n.", cn:"服务中断；断电", tip:"服务器挂了就是 outage", exampleEn:"A three-hour outage took down checkout.", exampleCn:"三小时的服务中断让结账功能瘫痪。", scene:"", cat:"news"},
  {id:"news029", word:"backlash", phonetic:"/ˈbæklæʃ/", pos:"n.", cn:"强烈反弹；抵制", tip:"公众的集体不满，舆论词", exampleEn:"The price change sparked a huge backlash.", exampleCn:"涨价引发了巨大的反弹。", scene:"", cat:"news"},
  {id:"news030", word:"controversy", phonetic:"/ˈkɑːntrəvɜːrsi/", pos:"n.", cn:"争议", tip:"形容词 controversial 更常用", exampleEn:"The decision stirred up controversy online.", exampleCn:"这个决定在网上引发了争议。", scene:"", cat:"news"},
  {id:"news031", word:"testimony", phonetic:"/ˈtestɪmoʊni/", pos:"n.", cn:"证词", tip:"听证会上作证说的话", exampleEn:"His testimony lasted over five hours.", exampleCn:"他的证词持续了五个多小时。", scene:"", cat:"news"},
  {id:"news032", word:"verdict", phonetic:"/ˈvɜːrdɪkt/", pos:"n.", cn:"裁决；判决", tip:"日常也可指「最终评价」", exampleEn:"The jury reached a verdict on Friday.", exampleCn:"陪审团在周五作出了裁决。", scene:"口语中可指对某物的「最终看法」", cat:"news"},
  {id:"news033", word:"spokesperson", phonetic:"/ˈspoʊkspɜːrsn/", pos:"n.", cn:"发言人", tip:"新闻里常见：a spokesperson said…", exampleEn:"A spokesperson declined to comment.", exampleCn:"一位发言人拒绝置评。", scene:"", cat:"news"},
  {id:"news034", word:"surveillance", phonetic:"/sərˈveɪləns/", pos:"n.", cn:"监控；监视", tip:"注意拼写和发音都容易错", exampleEn:"Critics call it mass surveillance.", exampleCn:"批评者称之为大规模监控。", scene:"", cat:"news"},
  {id:"news035", word:"privacy", phonetic:"/ˈpraɪvəsi/", pos:"n.", cn:"隐私", tip:"美音读 /ˈpraɪ-/，英音读 /ˈprɪ-/", exampleEn:"The policy raises serious privacy concerns.", exampleCn:"这项政策引发了严重的隐私担忧。", scene:"", cat:"news"},
  {id:"news036", word:"mandate", phonetic:"/ˈmændeɪt/", pos:"n./v.", cn:"强制规定；授权", tip:"政府强制要求做某事", exampleEn:"The new rule mandates two-factor authentication.", exampleCn:"新规强制要求双因素认证。", scene:"", cat:"news"},
  {id:"news037", word:"poll", phonetic:"/poʊl/", pos:"n./v.", cn:"民意调查", tip:"技术语境下 polling 指「轮询」", exampleEn:"The latest poll shows opinion is split.", exampleCn:"最新民调显示意见分歧。", scene:"编程中 polling 指定时「轮询」请求", cat:"news"},
  {id:"news038", word:"summit", phonetic:"/ˈsʌmɪt/", pos:"n.", cn:"峰会；顶峰", tip:"各国领导人开的会", exampleEn:"Leaders met at the climate summit.", exampleCn:"各国领导人在气候峰会上会面。", scene:"字面指山顶", cat:"news"},
  {id:"news039", word:"curb", phonetic:"/kɜːrb/", pos:"v./n.", cn:"遏制；抑制", tip:"新闻标题超高频：curb inflation 遏制通胀", exampleEn:"New rules aim to curb misleading ads.", exampleCn:"新规旨在遏制误导性广告。", scene:"作名词时指马路「路边石」", cat:"news"},
  {id:"news040", word:"scrutiny", phonetic:"/ˈskruːtəni/", pos:"n.", cn:"审视；严格审查", tip:"under scrutiny 被密切关注", exampleEn:"The deal is under intense scrutiny.", exampleCn:"这笔交易正受到严密审查。", scene:"", cat:"news"},

  // ========== 日常生活 补充 (cat: life) ==========
  {id:"life061", word:"deposit", phonetic:"/dɪˈpɑːzɪt/", pos:"n./v.", cn:"押金；存款", tip:"租房押金、银行存钱都用它", exampleEn:"The landlord kept part of my deposit.", exampleCn:"房东扣了我一部分押金。", scene:"", cat:"life"},
  {id:"life062", word:"utilities", phonetic:"/juːˈtɪlətiz/", pos:"n.", cn:"水电煤等公用事业费", tip:"租房广告里 utilities included 指含水电", exampleEn:"Rent is $900 plus utilities.", exampleCn:"租金 900 美元，水电另算。", scene:"", cat:"life"},
  {id:"life063", word:"lease", phonetic:"/liːs/", pos:"n./v.", cn:"租约；租赁", tip:"比口头租房正式，指签的那份合同", exampleEn:"My lease is up in two months.", exampleCn:"我的租约还有两个月到期。", scene:"", cat:"life"},
  {id:"life064", word:"mortgage", phonetic:"/ˈmɔːrɡɪdʒ/", pos:"n.", cn:"房贷；按揭", tip:"注意 t 不发音，很多人读错", exampleEn:"They're still paying off the mortgage.", exampleCn:"他们还在还房贷。", scene:"", cat:"life"},
  {id:"life065", word:"insurance", phonetic:"/ɪnˈʃʊrəns/", pos:"n.", cn:"保险", tip:"health insurance 医保，找工作必问", exampleEn:"Does the job come with health insurance?", exampleCn:"这份工作有医疗保险吗？", scene:"", cat:"life"},
  {id:"life066", word:"appliance", phonetic:"/əˈplaɪəns/", pos:"n.", cn:"家用电器", tip:"冰箱洗衣机这类大件", exampleEn:"All the appliances come with the apartment.", exampleCn:"公寓自带所有家电。", scene:"", cat:"life"},
  {id:"life067", word:"faucet", phonetic:"/ˈfɔːsɪt/", pos:"n.", cn:"水龙头", tip:"美式说法，英式叫 tap", exampleEn:"The kitchen faucet is dripping again.", exampleCn:"厨房水龙头又在滴水了。", scene:"", cat:"life"},
  {id:"life068", word:"drawer", phonetic:"/drɔːr/", pos:"n.", cn:"抽屉", tip:"读音接近 door，不读「德劳尔」", exampleEn:"The scissors are in the top drawer.", exampleCn:"剪刀在最上面那个抽屉里。", scene:"", cat:"life"},
  {id:"life069", word:"closet", phonetic:"/ˈklɑːzɪt/", pos:"n.", cn:"壁橱；衣柜", tip:"美式指嵌在墙里的储物空间", exampleEn:"My closet is completely full.", exampleCn:"我的衣柜完全塞满了。", scene:"", cat:"life"},
  {id:"life070", word:"blanket", phonetic:"/ˈblæŋkɪt/", pos:"n.", cn:"毯子", tip:"比 quilt（被子）薄", exampleEn:"Can you grab me an extra blanket?", exampleCn:"你能帮我拿条多余的毯子吗？", scene:"", cat:"life"},
  {id:"life071", word:"pillow", phonetic:"/ˈpɪloʊ/", pos:"n.", cn:"枕头", tip:"pillowcase 枕套", exampleEn:"This pillow is way too soft.", exampleCn:"这个枕头太软了。", scene:"", cat:"life"},
  {id:"life072", word:"towel", phonetic:"/ˈtaʊəl/", pos:"n.", cn:"毛巾", tip:"paper towel 厨房纸", exampleEn:"I forgot to pack a towel.", exampleCn:"我忘了带毛巾。", scene:"", cat:"life"},
  {id:"life073", word:"rinse", phonetic:"/rɪns/", pos:"v.", cn:"冲洗；涮", tip:"只用水冲，不打洗涤剂", exampleEn:"Rinse the rice before you cook it.", exampleCn:"煮之前把米淘一下。", scene:"", cat:"life"},
  {id:"life074", word:"defrost", phonetic:"/ˌdiːˈfrɔːst/", pos:"v.", cn:"解冻", tip:"微波炉上就有这个按钮", exampleEn:"Defrost the chicken before you cook it.", exampleCn:"做之前把鸡肉解冻。", scene:"", cat:"life"},
  {id:"life075", word:"microwave", phonetic:"/ˈmaɪkrəweɪv/", pos:"n./v.", cn:"微波炉；用微波炉加热", tip:"可以直接当动词用：microwave it", exampleEn:"Just microwave the leftovers for two minutes.", exampleCn:"剩菜微波炉打两分钟就行。", scene:"", cat:"life"},
  {id:"life076", word:"seasoning", phonetic:"/ˈsiːzənɪŋ/", pos:"n.", cn:"调料；调味品", tip:"season 作动词是「调味」", exampleEn:"It needs more seasoning.", exampleCn:"这个还得再加点调料。", scene:"", cat:"life"},
  {id:"life077", word:"bland", phonetic:"/blænd/", pos:"adj.", cn:"清淡无味的", tip:"不是「清淡健康」，多带贬义：没味道", exampleEn:"The soup was pretty bland.", exampleCn:"这汤挺没味的。", scene:"", cat:"life"},
  {id:"life078", word:"greasy", phonetic:"/ˈɡriːsi/", pos:"adj.", cn:"油腻的", tip:"形容食物或头发都行", exampleEn:"I can't eat anything greasy right now.", exampleCn:"我现在吃不了油腻的东西。", scene:"", cat:"life"},
  {id:"life079", word:"crispy", phonetic:"/ˈkrɪspi/", pos:"adj.", cn:"脆的", tip:"炸物的最高褒奖", exampleEn:"The skin was perfectly crispy.", exampleCn:"这皮脆得恰到好处。", scene:"", cat:"life"},
  {id:"life080", word:"tender", phonetic:"/ˈtendər/", pos:"adj.", cn:"（肉）嫩的；温柔的", tip:"形容肉不柴", exampleEn:"The beef was surprisingly tender.", exampleCn:"这牛肉意外地嫩。", scene:"形容人时指「温柔的」", cat:"life"},
  {id:"life081", word:"stale", phonetic:"/steɪl/", pos:"adj.", cn:"不新鲜的；放陈了的", tip:"面包放硬了、空气不流通都能用", exampleEn:"The bread has gone stale.", exampleCn:"面包已经不新鲜了。", scene:"技术语境指缓存「过期失效」", cat:"life"},
  {id:"life082", word:"expire", phonetic:"/ɪkˈspaɪər/", pos:"v.", cn:"过期；到期", tip:"expiration date 保质期", exampleEn:"The milk expired two days ago.", exampleCn:"这牛奶两天前就过期了。", scene:"", cat:"life"},
  {id:"life083", word:"refill", phonetic:"/ˈriːfɪl/", pos:"n./v.", cn:"续杯；再装满", tip:"美国餐厅软饮常免费续杯", exampleEn:"Do you want a refill on your coffee?", exampleCn:"你的咖啡要续杯吗？", scene:"", cat:"life"},
  {id:"life084", word:"tip", phonetic:"/tɪp/", pos:"n./v.", cn:"小费；给小费", tip:"美国餐厅通常给 15-20%", exampleEn:"How much should I tip here?", exampleCn:"这里该给多少小费？", scene:"也指「小建议、诀窍」", cat:"life"},
  {id:"life085", word:"reservation", phonetic:"/ˌrezərˈveɪʃn/", pos:"n.", cn:"预订", tip:"餐厅、酒店预订；动词 reserve", exampleEn:"I made a reservation for seven o'clock.", exampleCn:"我订了七点的位子。", scene:"也指「保留意见」", cat:"life"},
  {id:"life086", word:"aisle", phonetic:"/aɪl/", pos:"n.", cn:"过道；货架通道", tip:"s 不发音，读作 /aɪl/；超市问路必用", exampleEn:"Milk is in aisle four.", exampleCn:"牛奶在第四条通道。", scene:"飞机上指「过道座位」", cat:"life"},
  {id:"life087", word:"cart", phonetic:"/kɑːrt/", pos:"n.", cn:"购物车", tip:"网购的购物车也是它", exampleEn:"I left my phone in the cart.", exampleCn:"我把手机落在购物车里了。", scene:"", cat:"life"},
  {id:"life088", word:"checkout", phonetic:"/ˈtʃekaʊt/", pos:"n.", cn:"结账台；结账", tip:"Git 里 checkout 是「切换分支」", exampleEn:"The checkout line was insanely long.", exampleCn:"结账队伍长得离谱。", scene:"Git 中指「切换分支」（已在科技开发收录）", cat:"life"},
  {id:"life089", word:"pharmacy", phonetic:"/ˈfɑːrməsi/", pos:"n.", cn:"药房；药店", tip:"美国也叫 drugstore", exampleEn:"There's a pharmacy right across the street.", exampleCn:"街对面就有家药店。", scene:"", cat:"life"},
  {id:"life090", word:"clinic", phonetic:"/ˈklɪnɪk/", pos:"n.", cn:"诊所", tip:"比 hospital 小，看小病去的地方", exampleEn:"I went to a walk-in clinic yesterday.", exampleCn:"我昨天去了家不用预约的诊所。", scene:"", cat:"life"},
  {id:"life091", word:"allergy", phonetic:"/ˈælərdʒi/", pos:"n.", cn:"过敏", tip:"形容词 allergic：be allergic to 对……过敏", exampleEn:"I have a peanut allergy.", exampleCn:"我对花生过敏。", scene:"", cat:"life"},
  {id:"life092", word:"fever", phonetic:"/ˈfiːvər/", pos:"n.", cn:"发烧", tip:"run a fever / have a fever 发烧", exampleEn:"She's running a fever again.", exampleCn:"她又发烧了。", scene:"", cat:"life"},
  {id:"life093", word:"cough", phonetic:"/kɔːf/", pos:"n./v.", cn:"咳嗽", tip:"拼写和读音差很远，读作 /kɔːf/", exampleEn:"This cough has lasted two weeks.", exampleCn:"这个咳嗽已经持续两周了。", scene:"", cat:"life"},
  {id:"life094", word:"sneeze", phonetic:"/sniːz/", pos:"v./n.", cn:"打喷嚏", tip:"别人打喷嚏可以说 bless you", exampleEn:"I can't stop sneezing today.", exampleCn:"我今天喷嚏打个不停。", scene:"", cat:"life"},
  {id:"life095", word:"bandage", phonetic:"/ˈbændɪdʒ/", pos:"n.", cn:"绷带；创可贴", tip:"美国口语常叫 Band-Aid", exampleEn:"Do you have a bandage for this cut?", exampleCn:"你有创可贴给这个伤口贴一下吗？", scene:"", cat:"life"},
  {id:"life096", word:"dentist", phonetic:"/ˈdentɪst/", pos:"n.", cn:"牙医", tip:"看牙 go to the dentist", exampleEn:"I have a dentist appointment on Thursday.", exampleCn:"我周四约了牙医。", scene:"", cat:"life"},
  {id:"life097", word:"haircut", phonetic:"/ˈherkʌt/", pos:"n.", cn:"理发", tip:"get a haircut 去理发", exampleEn:"I need to get a haircut this weekend.", exampleCn:"我这周末得去剪个头发。", scene:"", cat:"life"},
  {id:"life098", word:"luggage", phonetic:"/ˈlʌɡɪdʒ/", pos:"n.", cn:"行李", tip:"不可数，别说 a luggage，用 a piece of luggage", exampleEn:"My luggage didn't make the connection.", exampleCn:"我的行李没赶上转机。", scene:"", cat:"life"},
  {id:"life099", word:"boarding pass", phonetic:"/ˈbɔːrdɪŋ pæs/", pos:"n.", cn:"登机牌", tip:"过安检和登机都要出示", exampleEn:"Have your boarding pass ready.", exampleCn:"把登机牌准备好。", scene:"", cat:"life"},
  {id:"life100", word:"layover", phonetic:"/ˈleɪoʊvər/", pos:"n.", cn:"中转停留", tip:"转机时在中间机场待的那段时间", exampleEn:"I have a six-hour layover in Tokyo.", exampleCn:"我在东京要中转停留六小时。", scene:"", cat:"life"},
  {id:"life101", word:"delay", phonetic:"/dɪˈleɪ/", pos:"n./v.", cn:"延误；推迟", tip:"航班延误、快递延迟都用它", exampleEn:"The flight was delayed by three hours.", exampleCn:"航班延误了三个小时。", scene:"", cat:"life"},
  {id:"life102", word:"itinerary", phonetic:"/aɪˈtɪnəreri/", pos:"n.", cn:"行程安排", tip:"拼写长但旅行必用", exampleEn:"Can you send me the itinerary?", exampleCn:"你能把行程发给我吗？", scene:"", cat:"life"},
  {id:"life103", word:"souvenir", phonetic:"/ˌsuːvəˈnɪr/", pos:"n.", cn:"纪念品", tip:"法语来的词，重音在最后", exampleEn:"I picked up a few souvenirs for my family.", exampleCn:"我给家里人带了几件纪念品。", scene:"", cat:"life"},
  {id:"life104", word:"sidewalk", phonetic:"/ˈsaɪdwɔːk/", pos:"n.", cn:"人行道", tip:"美式说法，英式叫 pavement", exampleEn:"The sidewalk was icy this morning.", exampleCn:"今早人行道上结冰了。", scene:"", cat:"life"},
  {id:"life105", word:"crosswalk", phonetic:"/ˈkrɔːswɔːk/", pos:"n.", cn:"人行横道", tip:"就是斑马线", exampleEn:"Use the crosswalk — it's safer.", exampleCn:"走人行横道，安全些。", scene:"", cat:"life"},
  {id:"life106", word:"elevator", phonetic:"/ˈelɪveɪtər/", pos:"n.", cn:"电梯", tip:"美式说法，英式叫 lift", exampleEn:"The elevator's been broken for a week.", exampleCn:"电梯已经坏了一个星期。", scene:"", cat:"life"},
  {id:"life107", word:"lobby", phonetic:"/ˈlɑːbi/", pos:"n.", cn:"大堂；门厅", tip:"作动词时指「游说」", exampleEn:"I'll wait for you in the lobby.", exampleCn:"我在大堂等你。", scene:"作动词指政治「游说」", cat:"life"},
  {id:"life108", word:"parcel", phonetic:"/ˈpɑːrsl/", pos:"n.", cn:"包裹", tip:"和 package 通用；避免和编程的 package 混淆时好用", exampleEn:"A parcel arrived for you this morning.", exampleCn:"今早有你的一个包裹。", scene:"", cat:"life"},
  {id:"life109", word:"deliver", phonetic:"/dɪˈlɪvər/", pos:"v.", cn:"送货；递送", tip:"delivery 是名词；外卖 food delivery", exampleEn:"They deliver until ten at night.", exampleCn:"他们送货到晚上十点。", scene:"也指「兑现承诺、交付成果」", cat:"life"},
  {id:"life110", word:"warranty", phonetic:"/ˈwɔːrənti/", pos:"n.", cn:"保修；质保", tip:"买电子产品必看", exampleEn:"The laptop is still under warranty.", exampleCn:"这台笔记本还在保修期内。", scene:"", cat:"life"},
  {id:"life111", word:"subscription", phonetic:"/səbˈskrɪpʃn/", pos:"n.", cn:"订阅", tip:"各种会员制服务；动词 subscribe", exampleEn:"I cancelled my subscription last month.", exampleCn:"我上个月取消了订阅。", scene:"", cat:"life"},
  {id:"life112", word:"vacuum", phonetic:"/ˈvækjuːm/", pos:"v./n.", cn:"吸尘；吸尘器", tip:"拼写两个 u，容易写错；也可说 vacuum cleaner", exampleEn:"I need to vacuum the living room.", exampleCn:"我得把客厅吸下尘。", scene:"物理语境指「真空」", cat:"life"},
  {id:"life113", word:"stain", phonetic:"/steɪn/", pos:"n./v.", cn:"污渍；弄脏", tip:"衣服上洗不掉的那块", exampleEn:"I can't get this coffee stain out.", exampleCn:"这块咖啡渍我洗不掉。", scene:"", cat:"life"},
  {id:"life114", word:"wrinkle", phonetic:"/ˈrɪŋkl/", pos:"n./v.", cn:"褶皱；皱纹", tip:"衣服皱了、脸上皱纹都用它", exampleEn:"This shirt wrinkles really easily.", exampleCn:"这件衬衫特别容易皱。", scene:"", cat:"life"},
  {id:"life115", word:"tidy", phonetic:"/ˈtaɪdi/", pos:"adj./v.", cn:"整洁的；收拾", tip:"tidy up 收拾一下", exampleEn:"Let me tidy up before they get here.", exampleCn:"他们到之前我收拾一下。", scene:"", cat:"life"},
];

if (typeof module !== "undefined") module.exports = { WORDS };
