// 三国武将录 —— 游戏数据（武将 / 招式 / 道具 / 地图 / NPC）
// 五行相克：金克木、木克土、土克水、水克火、火克金

const ELEM = {
  金: { beats: '木', color: '#c9a227' },
  木: { beats: '土', color: '#3f9a4a' },
  水: { beats: '火', color: '#3a86c8' },
  火: { beats: '金', color: '#d9482e' },
  土: { beats: '水', color: '#a0703a' },
  无: { beats: '',   color: '#8a8a8a' },
};

// c: w=武（武力对统率） z=智（智力对智力） s=辅助
// fx: {t:'stat',who,s,v,ch} / {t:'st',s,ch} / {t:'heal',v} ；crit:true 易暴击
const MOVES = {
  tackle:     { n: '突击',     e: '无', c: 'w', p: 40, a: 100, pp: 35 },
  slash:      { n: '劈砍',     e: '无', c: 'w', p: 55, a: 95,  pp: 25 },
  charge:     { n: '冲阵',     e: '无', c: 'w', p: 85, a: 90,  pp: 15 },
  shout:      { n: '呐喊',     e: '无', c: 's', a: 100, pp: 30, fx: { t: 'stat', who: 'foe', s: 'w', v: -1 } },
  encourage:  { n: '激励',     e: '无', c: 's', a: 100, pp: 20, fx: { t: 'stat', who: 'self', s: 'w', v: 1 } },
  defend:     { n: '坚守',     e: '无', c: 's', a: 100, pp: 20, fx: { t: 'stat', who: 'self', s: 't', v: 1 } },
  haste:      { n: '疾行',     e: '无', c: 's', a: 100, pp: 20, fx: { t: 'stat', who: 'self', s: 's', v: 2 } },
  focus:      { n: '凝神',     e: '无', c: 's', a: 100, pp: 20, fx: { t: 'stat', who: 'self', s: 'z', v: 1 } },
  arrow:      { n: '连弩',     e: '金', c: 'w', p: 45, a: 100, pp: 30 },
  pierce:     { n: '破甲斩',   e: '金', c: 'w', p: 70, a: 95,  pp: 15, fx: { t: 'stat', who: 'foe', s: 't', v: -1, ch: 0.3 } },
  blade_storm:{ n: '刀阵',     e: '金', c: 'z', p: 75, a: 100, pp: 15 },
  halberd:    { n: '画戟横扫', e: '金', c: 'w', p: 100, a: 90, pp: 10 },
  hundred:    { n: '百步穿杨', e: '金', c: 'w', p: 95, a: 100, pp: 10, crit: true },
  gold_bell:  { n: '金钟罩',   e: '金', c: 's', a: 100, pp: 10, fx: { t: 'stat', who: 'self', s: 't', v: 2 } },
  thrust:     { n: '枪刺',     e: '木', c: 'w', p: 45, a: 100, pp: 30 },
  snake:      { n: '蛇矛突',   e: '木', c: 'w', p: 90, a: 95,  pp: 15 },
  woodarray:  { n: '落木阵',   e: '木', c: 'z', p: 70, a: 100, pp: 15 },
  thicket:    { n: '八阵图',   e: '木', c: 'z', p: 115, a: 90, pp: 5, fx: { t: 'st', s: 'stun', ch: 0.3 } },
  heal:       { n: '疗伤',     e: '木', c: 's', a: 100, pp: 10, fx: { t: 'heal', v: 0.5 } },
  poison:     { n: '毒计',     e: '木', c: 's', a: 90,  pp: 20, fx: { t: 'st', s: 'poison', ch: 1 } },
  icespear:   { n: '寒枪',     e: '水', c: 'w', p: 55, a: 100, pp: 25 },
  returnspear:{ n: '回马枪',   e: '水', c: 'w', p: 75, a: 100, pp: 15, crit: true },
  flood:      { n: '水淹七军', e: '水', c: 'z', p: 90, a: 90,  pp: 10 },
  charm:      { n: '离间',     e: '水', c: 's', a: 100, pp: 15, fx: { t: 'stat', who: 'foe', s: 'w', v: -2 } },
  firearrow:  { n: '火箭',     e: '火', c: 'w', p: 50, a: 100, pp: 25, fx: { t: 'st', s: 'burn', ch: 0.1 } },
  burnoil:    { n: '火油',     e: '火', c: 'z', p: 55, a: 100, pp: 20, fx: { t: 'st', s: 'burn', ch: 0.2 } },
  firetactic: { n: '火计',     e: '火', c: 'z', p: 85, a: 95,  pp: 10, fx: { t: 'st', s: 'burn', ch: 0.3 } },
  dragonblade:{ n: '青龙斩',   e: '火', c: 'w', p: 100, a: 90, pp: 10 },
  xiliang:    { n: '西凉铁骑', e: '火', c: 'w', p: 95, a: 95,  pp: 10 },
  rock:       { n: '落石',     e: '土', c: 'w', p: 55, a: 95,  pp: 25 },
  sandstorm:  { n: '飞沙',     e: '土', c: 'z', p: 50, a: 100, pp: 20, fx: { t: 'stat', who: 'foe', s: 's', v: -1, ch: 0.3 } },
  quake:      { n: '地裂',     e: '土', c: 'w', p: 90, a: 90,  pp: 10 },
  yellowsky:  { n: '黄天咒',   e: '土', c: 'z', p: 90, a: 100, pp: 10 },
  stun:       { n: '定身术',   e: '土', c: 's', a: 75,  pp: 15, fx: { t: 'st', s: 'stun', ch: 1 } },
};

const ITEMS = {
  yao:    { n: '伤药',   price: 100, d: '恢复 30 兵力', heal: 30 },
  jinchuang: { n: '金创药', price: 500, d: '兵力全满', heal: 9999 },
  jiedu:  { n: '解毒丹', price: 150, d: '解除中毒、灼烧、定身', cure: true },
  huihun: { n: '回魂丹', price: 800, d: '让溃败的武将恢复一半兵力', revive: true },
  ling:   { n: '招降令', price: 200, d: '招降野外武将', ball: 1 },
  hufu:   { n: '虎符',   price: 600, d: '招降成功率更高', ball: 2 },
};

// b: [兵力, 武力, 统率, 智力, 速度]  rate: 招降难易（越大越容易）
// look: 立绘参数（程序生成像素画）
const H = '#1e1a18'; // 黑发
const GENS = {
  guanyu:   { n: '关羽', e: '火', b: [80, 95, 78, 72, 72], exp: 70, rate: .15,
    learn: [[1,'slash'],[1,'shout'],[7,'firearrow'],[12,'encourage'],[16,'firetactic'],[22,'charge'],[28,'dragonblade']],
    look: { face: '#c8442e', beard: 2, bc: H, hat: 'band', hatC: '#2f7a3f', armor: '#2f7a3f', trim: '#d8b24a', weapon: 'glaive' } },
  zhangfei: { n: '张飞', e: '木', b: [88, 98, 72, 40, 66], exp: 70, rate: .15,
    learn: [[1,'tackle'],[1,'shout'],[7,'thrust'],[12,'encourage'],[17,'charge'],[22,'snake'],[30,'quake']],
    look: { skin: '#a8744a', beard: 3, bc: H, hat: 'band', hatC: '#2a2a2e', armor: '#34343a', trim: '#b8862e', weapon: 'snake' } },
  zhaoyun:  { n: '赵云', e: '水', b: [76, 90, 76, 68, 92], exp: 70, rate: .15,
    learn: [[1,'tackle'],[1,'haste'],[7,'icespear'],[12,'defend'],[16,'returnspear'],[22,'charge'],[28,'flood']],
    look: { beard: 0, hat: 'helmet', hatC: '#e6ebf2', armor: '#dfe6ee', trim: '#3a78c8', weapon: 'spear' } },
  huangjin: { n: '黄巾兵', e: '土', b: [48, 52, 44, 28, 44], exp: 45, rate: .6,
    learn: [[1,'tackle'],[1,'shout'],[5,'rock'],[10,'sandstorm'],[16,'slash']],
    look: { beard: 0, hat: 'turban', hatC: '#e6c21e', armor: '#8a6a44', trim: '#e6c21e', weapon: 'staff' } },
  xiangyong: { n: '乡勇', e: '木', b: [52, 50, 50, 34, 50], exp: 45, rate: .6,
    learn: [[1,'tackle'],[1,'defend'],[5,'thrust'],[11,'encourage'],[18,'woodarray']],
    look: { beard: 1, bc: H, hat: 'band', hatC: '#7a5a36', armor: '#b09a6a', trim: '#6a4a2a', weapon: 'spear' } },
  gongshou: { n: '弓手', e: '金', b: [44, 58, 40, 42, 62], exp: 48, rate: .55,
    learn: [[1,'tackle'],[1,'arrow'],[8,'haste'],[14,'pierce'],[20,'firearrow']],
    look: { beard: 0, hat: 'helmet', hatC: '#8a8f98', armor: '#7a6a52', trim: '#c9a227', weapon: 'bow' } },
  youxia:   { n: '游侠', e: '水', b: [48, 56, 42, 46, 70], exp: 48, rate: .55,
    learn: [[1,'slash'],[4,'haste'],[8,'icespear'],[15,'returnspear']],
    look: { beard: 0, hat: 'bun', hatC: H, armor: '#3a6a9a', trim: '#e0e0e0', weapon: 'sword' } },
  fangshi:  { n: '方士', e: '火', b: [44, 30, 40, 66, 56], exp: 50, rate: .5,
    learn: [[1,'focus'],[1,'burnoil'],[7,'poison'],[12,'firetactic'],[18,'heal']],
    look: { beard: 1, bc: '#8a8a8a', hat: 'scholar', hatC: '#5a2a2a', armor: '#b83a2e', trim: '#e6c21e', weapon: 'staff', robe: 1 } },
  zhoucang: { n: '周仓', e: '土', b: [70, 78, 65, 35, 55], exp: 60, rate: .3,
    learn: [[1,'tackle'],[1,'shout'],[6,'rock'],[12,'encourage'],[18,'quake']],
    look: { skin: '#8a5a36', beard: 3, bc: H, hat: 'band', hatC: '#5a3a1a', armor: '#6a4a2a', trim: '#b8862e', weapon: 'axe' } },
  liaohua:  { n: '廖化', e: '木', b: [62, 68, 62, 55, 60], exp: 60, rate: .3,
    learn: [[1,'slash'],[5,'thrust'],[10,'defend'],[15,'woodarray'],[20,'snake']],
    look: { beard: 1, bc: H, hat: 'helmet', hatC: '#4a7a4a', armor: '#5a8a5a', trim: '#c9a227', weapon: 'sword' } },
  chengyuanzhi: { n: '程远志', e: '火', b: [60, 64, 50, 34, 52], exp: 55, rate: .35,
    learn: [[1,'slash'],[1,'firearrow'],[10,'encourage'],[15,'charge']],
    look: { beard: 3, bc: H, hat: 'turban', hatC: '#e6c21e', armor: '#9a4a2a', trim: '#e6c21e', weapon: 'axe' } },
  guanhai:  { n: '管亥', e: '金', b: [66, 72, 56, 30, 54], exp: 55, rate: .35,
    learn: [[1,'slash'],[1,'arrow'],[10,'pierce'],[16,'charge']],
    look: { skin: '#b07a50', beard: 1, bc: H, hat: 'turban', hatC: '#e6c21e', armor: '#6a6a6a', trim: '#e6c21e', weapon: 'mace' } },
  zhangbao: { n: '张宝', e: '土', b: [64, 50, 58, 78, 60], exp: 65, rate: .25,
    learn: [[1,'focus'],[1,'sandstorm'],[8,'stun'],[12,'yellowsky'],[16,'poison']],
    look: { beard: 1, bc: H, hat: 'turban', hatC: '#e6c21e', armor: '#c9a227', trim: '#8a4a1a', weapon: 'staff', robe: 1 } },
  zhangliang: { n: '张梁', e: '土', b: [72, 70, 64, 50, 55], exp: 65, rate: .25,
    learn: [[1,'tackle'],[1,'rock'],[9,'encourage'],[14,'quake']],
    look: { beard: 3, bc: H, hat: 'turban', hatC: '#e6c21e', armor: '#8a6a2a', trim: '#e6c21e', weapon: 'spear' } },
  zhangjiao: { n: '张角', e: '土', b: [80, 50, 70, 95, 65], exp: 90, rate: .08,
    learn: [[1,'focus'],[1,'sandstorm'],[1,'stun'],[10,'yellowsky'],[15,'heal'],[20,'quake']],
    look: { beard: 2, bc: '#e8e4dc', hat: 'turban', hatC: '#f0d020', armor: '#e6c21e', trim: '#8a3a1a', weapon: 'staff', robe: 1 } },
  xuchu:    { n: '许褚', e: '土', b: [95, 96, 80, 30, 52], exp: 75, rate: .12,
    learn: [[1,'tackle'],[1,'shout'],[1,'rock'],[14,'encourage'],[18,'quake'],[24,'charge']],
    look: { beard: 3, bc: H, hat: 'bun', hatC: H, armor: '#5a5a62', trim: '#a07a3a', weapon: 'mace' } },
  dianwei:  { n: '典韦', e: '金', b: [90, 97, 78, 32, 58], exp: 75, rate: .1,
    learn: [[1,'slash'],[1,'encourage'],[1,'pierce'],[16,'charge'],[22,'blade_storm'],[28,'halberd']],
    look: { skin: '#9a6a44', beard: 3, bc: H, hat: 'band', hatC: '#c9a227', armor: '#4a4a52', trim: '#c9a227', weapon: 'dual' } },
  yuejin:   { n: '乐进', e: '火', b: [66, 80, 64, 50, 72], exp: 60, rate: .3,
    learn: [[1,'slash'],[1,'firearrow'],[14,'haste'],[18,'firetactic']],
    look: { beard: 1, bc: H, hat: 'helmet', hatC: '#a83a2a', armor: '#8a3a2a', trim: '#c9a227', weapon: 'spear' } },
  lidian:   { n: '李典', e: '水', b: [64, 70, 70, 68, 64], exp: 60, rate: .3,
    learn: [[1,'slash'],[1,'icespear'],[14,'defend'],[18,'flood']],
    look: { beard: 1, bc: H, hat: 'helmet', hatC: '#3a5a8a', armor: '#3a5a8a', trim: '#d0d0d0', weapon: 'sword' } },
  yujin:    { n: '于禁', e: '金', b: [70, 76, 82, 60, 58], exp: 60, rate: .3,
    learn: [[1,'slash'],[1,'arrow'],[1,'defend'],[16,'pierce'],[22,'blade_storm']],
    look: { beard: 2, bc: H, hat: 'helmet', hatC: '#6a6a72', armor: '#6a6a72', trim: '#c9a227', weapon: 'halberd' } },
  xiahoudun: { n: '夏侯惇', e: '木', b: [80, 90, 74, 55, 70], exp: 75, rate: .12,
    learn: [[1,'slash'],[1,'thrust'],[1,'encourage'],[16,'snake'],[22,'charge']],
    look: { beard: 1, bc: H, hat: 'helmet', hatC: '#2a4a8a', armor: '#2a3a6a', trim: '#c9a227', weapon: 'spear', patch: 1 } },
  huaxiong: { n: '华雄', e: '火', b: [85, 88, 74, 40, 66], exp: 85, rate: .08,
    learn: [[1,'slash'],[1,'firearrow'],[1,'encourage'],[15,'firetactic'],[18,'charge'],[24,'dragonblade']],
    look: { skin: '#b07a50', beard: 3, bc: H, hat: 'helmet', hatC: '#8a2a1a', armor: '#6a2a1a', trim: '#e0a030', weapon: 'glaive', wc: '#c8ccd4' } },
  huzhen:   { n: '胡轸', e: '金', b: [66, 70, 64, 40, 58], exp: 55, rate: .35,
    learn: [[1,'slash'],[1,'arrow'],[14,'pierce']],
    look: { beard: 1, bc: H, hat: 'helmet', hatC: '#6a5a4a', armor: '#6a5a4a', trim: '#b0a080', weapon: 'spear' } },
  lisu:     { n: '李肃', e: '水', b: [60, 58, 60, 70, 66], exp: 55, rate: .35,
    learn: [[1,'focus'],[1,'icespear'],[12,'poison'],[15,'flood']],
    look: { beard: 1, bc: H, hat: 'scholar', hatC: '#2a3a5a', armor: '#3a5a7a', trim: '#e0e0e0', weapon: 'sword', robe: 1 } },
  zhangliao: { n: '张辽', e: '金', b: [80, 92, 78, 78, 86], exp: 80, rate: .1,
    learn: [[1,'slash'],[1,'haste'],[1,'pierce'],[18,'blade_storm'],[24,'halberd']],
    look: { beard: 1, bc: H, hat: 'helmet', hatC: '#4a4a6a', armor: '#5a5a7a', trim: '#e0b040', weapon: 'glaive' } },
  gaoshun:  { n: '高顺', e: '土', b: [84, 85, 90, 55, 60], exp: 80, rate: .1,
    learn: [[1,'tackle'],[1,'defend'],[1,'rock'],[18,'quake'],[22,'gold_bell']],
    look: { beard: 3, bc: H, hat: 'helmet', hatC: '#3a3a3a', armor: '#2a2a2e', trim: '#a0a0a0', weapon: 'sword' } },
  chengong: { n: '陈宫', e: '水', b: [62, 40, 58, 92, 68], exp: 75, rate: .12,
    learn: [[1,'focus'],[1,'poison'],[1,'icespear'],[20,'flood'],[24,'stun']],
    look: { beard: 1, bc: H, hat: 'scholar', hatC: '#1a2a3a', armor: '#2a4a6a', trim: '#e0e0e0', weapon: 'fan', robe: 1 } },
  lvbu:     { n: '吕布', e: '金', b: [100, 120, 88, 50, 100], exp: 110, rate: .05,
    learn: [[1,'slash'],[1,'shout'],[1,'pierce'],[20,'charge'],[25,'halberd'],[30,'gold_bell']],
    look: { beard: 0, hat: 'feather', hatC: '#e3b341', armor: '#b8302a', trim: '#e3b341', weapon: 'halberd' } },
  xuhuang:  { n: '徐晃', e: '金', b: [80, 90, 78, 58, 64], exp: 75, rate: .12,
    learn: [[1,'slash'],[1,'pierce'],[1,'encourage'],[20,'blade_storm']],
    look: { beard: 2, bc: H, hat: 'helmet', hatC: '#5a4a3a', armor: '#6a5a4a', trim: '#c9a227', weapon: 'axe' } },
  ganning:  { n: '甘宁', e: '水', b: [74, 90, 64, 55, 94], exp: 75, rate: .12,
    learn: [[1,'slash'],[1,'haste'],[1,'icespear'],[18,'returnspear'],[24,'flood']],
    look: { beard: 1, bc: H, hat: 'band', hatC: '#c83a2a', armor: '#2a6a8a', trim: '#e3b341', weapon: 'dual' } },
  taishici: { n: '太史慈', e: '木', b: [78, 90, 70, 60, 82], exp: 75, rate: .12,
    learn: [[1,'arrow'],[1,'thrust'],[1,'haste'],[18,'snake'],[24,'woodarray']],
    look: { beard: 1, bc: H, hat: 'helmet', hatC: '#2a6a3a', armor: '#3a7a4a', trim: '#e0e0e0', weapon: 'bow' } },
  liru:     { n: '李儒', e: '水', b: [60, 35, 55, 94, 70], exp: 70, rate: .15,
    learn: [[1,'focus'],[1,'poison'],[1,'flood'],[26,'charm']],
    look: { beard: 1, bc: H, hat: 'scholar', hatC: '#1a1a1a', armor: '#2a2a3a', trim: '#8a2a2a', weapon: 'fan', robe: 1 } },
  lijue:    { n: '李傕', e: '火', b: [72, 78, 64, 40, 64], exp: 65, rate: .2,
    learn: [[1,'slash'],[1,'firearrow'],[24,'firetactic']],
    look: { beard: 3, bc: H, hat: 'helmet', hatC: '#7a3a2a', armor: '#7a3a2a', trim: '#b0a080', weapon: 'glaive' } },
  guosi:    { n: '郭汜', e: '金', b: [72, 76, 66, 38, 66], exp: 65, rate: .2,
    learn: [[1,'slash'],[1,'arrow'],[24,'pierce']],
    look: { beard: 1, bc: H, hat: 'helmet', hatC: '#5a5a5a', armor: '#5a5a5a', trim: '#b0a080', weapon: 'spear' } },
  dongzhuo: { n: '董卓', e: '土', b: [115, 84, 84, 70, 40], exp: 120, rate: .05,
    learn: [[1,'tackle'],[1,'shout'],[1,'rock'],[1,'defend'],[28,'quake'],[30,'yellowsky']],
    look: { beard: 3, bc: H, hat: 'crown', hatC: '#1a1a1a', armor: '#6a2a6a', trim: '#e3b341', weapon: 'sword', fat: 1 } },
  diaochan: { n: '貂蝉', e: '水', b: [62, 40, 55, 90, 95], exp: 70, rate: .1,
    learn: [[1,'focus'],[1,'charm'],[1,'icespear'],[28,'flood'],[32,'heal']],
    look: { beard: 0, hat: 'female', hatC: H, armor: '#e87aa0', trim: '#fff0f4', weapon: 'fan', female: 1, robe: 1 } },
  machao:   { n: '马超', e: '火', b: [80, 98, 72, 50, 96], exp: 85, rate: .08,
    learn: [[1,'slash'],[1,'haste'],[1,'firearrow'],[24,'charge'],[28,'xiliang']],
    look: { beard: 0, hat: 'helmet', hatC: '#f0f0f0', armor: '#e8e8ee', trim: '#c83a2a', weapon: 'spear' } },
  huangzhong: { n: '黄忠', e: '金', b: [76, 92, 72, 60, 66], exp: 85, rate: .08,
    learn: [[1,'arrow'],[1,'pierce'],[1,'focus'],[26,'hundred']],
    look: { beard: 2, bc: '#e8e4dc', hat: 'helmet', hatC: '#a08a3a', armor: '#8a7a3a', trim: '#e3b341', weapon: 'bow' } },
  zhugeliang: { n: '诸葛亮', e: '木', b: [72, 40, 70, 120, 90], exp: 100, rate: .04,
    learn: [[1,'focus'],[1,'woodarray'],[1,'heal'],[26,'flood'],[30,'firetactic'],[35,'thicket']],
    look: { beard: 1, bc: H, hat: 'scholar', hatC: '#2a3a4a', armor: '#eef0f0', trim: '#2a3a4a', weapon: 'fan', robe: 1 } },
};

const PLAYER_LOOK = { beard: 1, bc: H, hat: 'bun', hatC: H, armor: '#3a6fb0', trim: '#e0c060', weapon: 'dual' };
const HEALER_LOOK = { beard: 2, bc: '#e0e0e0', hat: 'scholar', hatC: '#4a4a5a', armor: '#e8e2d0', trim: '#6a9a5a', weapon: 'staff', robe: 1 };
const MERCHANT_LOOK = { beard: 1, bc: H, hat: 'bun', hatC: H, armor: '#9a6a3a', trim: '#e0c060' };
const ELDER_LOOK = { beard: 2, bc: '#e0e0e0', hat: 'bun', hatC: '#d0d0d0', armor: '#7a6a5a', trim: '#b0a080' };
const VILLAGER_LOOK = { beard: 0, hat: 'band', hatC: '#6a4a2a', armor: '#8aa06a', trim: '#6a4a2a' };

// 地块：. 草地  , 深草（遇敌） = 土路  T 树  ~ 水  b 桥  r 屋顶  w 墙  H 医馆门  P 商铺门  D 民居门
//       # 城墙  G 城门  X 石板  c 营帐  K 旗帜  R 岩石  f 花  S 路牌
const SOLID = 'T~rwHPD#cKRS';

const MAPS = {
  zhuo: {
    n: '涿郡', banner: '#3a6fb0',
    rows: [
      'TTTTTTTTT==TTTTTTTTT',
      'T........==........T',
      'T.rrrr...==...rrrr.T',
      'T.wwHw...==...wPww.T',
      'T........==........T',
      'T.f.f....==....f.f.T',
      'T==================T',
      'T.......=..........T',
      'T.rrrr..=...rrrrr..T',
      'T.wwDw..=...wwDww..T',
      'T.......=....S.....T',
      'T..~~~..=..........T',
      'T..~~~..=...f..f...T',
      'T.......=..........T',
      'T.fff...=.....TT...T',
      'T.......=.....TT...T',
      'T.......=..........T',
      'TTTTTTTTTTTTTTTTTTTT',
    ],
    exits: [[9, 0, 'taoyuan', 9, 24], [10, 0, 'taoyuan', 10, 24]],
    signs: { '13,10': '涿郡。北去桃园道，黄巾贼正在广宗一带作乱。' },
    doors: { '4,3': 'heal', '15,3': 'shop', '4,9': '门关着。屋里传来织席贩履的声音。', '14,9': '门关着。' },
    shop: ['yao', 'jiedu', 'ling'],
  },
  taoyuan: {
    n: '桃园道', banner: '#3a6fb0',
    rows: [
      'TTTTTTTTT==TTTTTTTTT',
      'T,,,.....==.....,,,T',
      'T,,,.....==.....,,,T',
      'T,,,..TT.==.TT..,,,T',
      'T........==........T',
      'T..RR....==....f...T',
      'T~~~~~~~~bb~~~~~~~~T',
      'T~~~~~~~~bb~~~~~~~~T',
      'T........==........T',
      'T.,,,,,,.==..TTT...T',
      'T.,,,,,,.==..TTT...T',
      'T.,,,,,,.==........T',
      'T........======....T',
      'T.TT..........=....T',
      'T.TT..,,,,,,..=....T',
      'T.....,,,,,,..=....T',
      'T.....,,,,,,..=..S.T',
      'T....=========.....T',
      'T....=...f.........T',
      'T....=....,,,,,,,..T',
      'T....=....,,,,,,,..T',
      'T....=....,,,,,,,..T',
      'T....======........T',
      'T........==........T',
      'T........==........T',
      'TTTTTTTTT==TTTTTTTTT',
    ],
    exits: [[9, 25, 'zhuo', 9, 1], [10, 25, 'zhuo', 10, 1], [9, 0, 'guangzong', 10, 16], [10, 0, 'guangzong', 10, 16]],
    signs: { '17,16': '北：广宗·黄巾大营　南：涿郡' },
    wild: [['huangjin', 2, 4, 30], ['xiangyong', 2, 4, 25], ['gongshou', 3, 5, 15], ['youxia', 3, 5, 15], ['fangshi', 3, 5, 12], ['liaohua', 4, 6, 3], ['zhoucang', 5, 6, 2]],
  },
  guangzong: {
    n: '广宗·黄巾大营', banner: '#e6c21e',
    rows: [
      'TTTTTTTTTT=TTTTTTTTT',
      'T.........=........T',
      'T.cc..K...=...K..ccT',
      'T.cc......=......ccT',
      'T.........=........T',
      'T..cc.....=.....cc.T',
      'T..cc...=====...cc.T',
      'T.......=...=......T',
      'T.,,,...=...=...,,.T',
      'T.,,,...=...=...,,.T',
      'T.......=...=......T',
      'T..cc...=====..cc..T',
      'T..cc.....=....cc..T',
      'T.........=........T',
      'T.K.......=......K.T',
      'T.........=........T',
      'T.........=........T',
      'TTTTTTTTTT=TTTTTTTTT',
    ],
    exits: [[10, 17, 'taoyuan', 9, 1], [10, 0, 'suanzao', 12, 21]],
    wild: [['huangjin', 5, 8, 50], ['fangshi', 5, 8, 25], ['chengyuanzhi', 6, 8, 12], ['guanhai', 6, 8, 12]],
  },
  suanzao: {
    n: '酸枣·联军大营', banner: '#c0392b',
    rows: [
      'TTTTTTTTT=TTTTTTTTTT',
      'T,,,,,,..=..,,,,,,,T',
      'T,,,,,,..=..,,,,,,,T',
      'T........=.........T',
      'TTTT.....=.....TTTTT',
      'T~~~~....=....~~~~~T',
      'T~~~~....=....~~~~~T',
      'T........=.........T',
      'T..rrrr..=..rrrr...T',
      'T..wwHw..=..wPww...T',
      'T........=.........T',
      'T..=======.........T',
      'T..=......,,,,,,,..T',
      'T..=..RR..,,,,,,,..T',
      'T..=......,,,,,,,..T',
      'T..=...............T',
      'T..==========......T',
      'T.,,,,,,,,..=......T',
      'T.,,,,,,,,..=......T',
      'T.,,,,,,,,..=..TT..T',
      'T...........=..TT..T',
      'T...........=......T',
      'TTTTTTTTTTTT=TTTTTTT',
    ],
    exits: [[12, 22, 'guangzong', 10, 1], [9, 0, 'sishui', 9, 14]],
    doors: { '5,9': 'heal', '13,9': 'shop' },
    shop: ['yao', 'jinchuang', 'jiedu', 'huihun', 'ling', 'hufu'],
    wild: [['xiangyong', 8, 10, 20], ['gongshou', 8, 11, 20], ['yuejin', 9, 12, 14], ['lidian', 9, 12, 14], ['yujin', 9, 12, 14], ['xuchu', 10, 12, 6], ['dianwei', 10, 12, 5], ['xiahoudun', 11, 13, 4]],
  },
  sishui: {
    n: '汜水关', banner: '#6a2a1a',
    rows: [
      'TTTTTTTTT=TTTTTTTTTT',
      'T...,,...=...,,,...T',
      '#########G##########',
      '#XXXXXXXXXXXXXXXXXX#',
      '#XKXXXXXXXXXXXXXXKX#',
      '#XXXXXXXXXXXXXXXXXX#',
      '#XXXccXXXXXXXXccXXX#',
      '#XXXccXXXXXXXXccXXX#',
      '#XXXXXXXXXXXXXXXXXX#',
      '#XKXXXXXXXXXXXXXXKX#',
      '#XXXXXXXXXXXXXXXXXX#',
      '#########G##########',
      'T........=.........T',
      'T.,,,....=....,,,..T',
      'T........=.........T',
      'TTTTTTTTT=TTTTTTTTTT',
    ],
    exits: [[9, 15, 'suanzao', 9, 1], [9, 0, 'hulaodao', 9, 16]],
    wild: [['youxia', 12, 14, 40], ['fangshi', 12, 14, 40], ['yuejin', 12, 14, 10], ['lidian', 12, 14, 10]],
  },
  hulaodao: {
    n: '虎牢道', banner: '#3a6fb0',
    rows: [
      'TTTTTTTTT=TTTTTTTTTT',
      'T,,,,,,..=..,,,,,,,T',
      'T,,,,,,..=..,,,,,,,T',
      'T........=.........T',
      'T~~~~~~~~b~~~~~~~~~T',
      'T~~~~~~~~b~~~~~~~~~T',
      'T....=====.........T',
      'T....=....RR..,,,,.T',
      'T....=........,,,,.T',
      'T,,,,=,,,,....,,,,.T',
      'T,,,,=,,,,.........T',
      'T....=====....TT...T',
      'T........=....TT...T',
      'T..TT....=.........T',
      'T..TT....=..,,,,,,.T',
      'T........=..,,,,,,.T',
      'T........=.........T',
      'TTTTTTTTT=TTTTTTTTTT',
    ],
    exits: [[9, 17, 'sishui', 9, 1], [9, 0, 'hulao', 9, 14]],
    wild: [['gongshou', 14, 16, 20], ['youxia', 14, 16, 20], ['zhangliao', 14, 17, 12], ['gaoshun', 14, 17, 12], ['xuhuang', 15, 17, 12], ['ganning', 15, 17, 12], ['taishici', 15, 17, 12]],
  },
  hulao: {
    n: '虎牢关', banner: '#b8302a',
    rows: [
      'TTTTTTTTT=TTTTTTTTTT',
      'T...,,...=...,,,...T',
      '#########G##########',
      '#XXXXXXXXXXXXXXXXXX#',
      '#XKXXXXXXXXXXXXXXKX#',
      '#XXXXXXXXXXXXXXXXXX#',
      '#XXXccXXXXXXXXccXXX#',
      '#XXXccXXXXXXXXccXXX#',
      '#XXXXXXXXXXXXXXXXXX#',
      '#XKXXXXXXXXXXXXXXKX#',
      '#XXXXXXXXXXXXXXXXXX#',
      '#########G##########',
      'T........=.........T',
      'T.,,,....=....,,,..T',
      'T........=.........T',
      'TTTTTTTTT=TTTTTTTTTT',
    ],
    exits: [[9, 15, 'hulaodao', 9, 1], [9, 0, 'luoyang', 9, 15]],
    wild: [['zhangliao', 17, 19, 25], ['gaoshun', 17, 19, 25], ['youxia', 16, 18, 25], ['gongshou', 16, 18, 25]],
  },
  luoyang: {
    n: '洛阳', banner: '#6a2a6a',
    rows: [
      'TTTTTTTTTTTTTTTTTTTT',
      'T##################T',
      'T#rrrrrrrrrrrrrrrr#T',
      'T#wwwwwwwDwwwwwwww#T',
      'T#XXXXXXXXXXXXXXXX#T',
      'T#XKXXXXXXXXXXXXKX#T',
      'T#XXXXXXXXXXXXXXXX#T',
      'T########G#########T',
      'T........=.........T',
      'T.rrrr...=...rrrr..T',
      'T.wwHw...=...wPww..T',
      'T........=.........T',
      'T.ff.....=.....ff..T',
      'T.,,,,...=...,,,,..T',
      'T.,,,,...=...,,,,..T',
      'T........=.........T',
      'TTTTTTTTT=TTTTTTTTTT',
    ],
    exits: [[9, 16, 'hulao', 9, 1]],
    doors: { '4,10': 'heal', '14,10': 'shop', '9,3': '相国府大门紧闭。' },
    shop: ['yao', 'jinchuang', 'jiedu', 'huihun', 'ling', 'hufu'],
    wild: [['youxia', 20, 23, 30], ['fangshi', 20, 23, 30], ['machao', 22, 25, 15], ['huangzhong', 22, 25, 15], ['zhugeliang', 24, 26, 4]],
    // 讨董之后多出来的野生武将
    wildEnd: [['lvbu', 30, 32, 3], ['huaxiong', 26, 28, 5], ['zhangjiao', 26, 28, 5], ['dongzhuo', 30, 32, 3], ['huzhen', 24, 26, 10], ['lisu', 24, 26, 10], ['chengong', 26, 28, 6], ['liru', 26, 28, 6], ['lijue', 25, 27, 8], ['guosi', 25, 27, 8], ['zhangbao', 24, 26, 8], ['zhangliang', 24, 26, 8]],
  },
};

// NPC：look 可以是武将 id（用该武将的外形）或外形对象
// trainer：{team:[[武将,等级]...], gold, pre, win}；boss 赢了之后消失
const NPCS = [
  { id: 'elder', map: 'zhuo', x: 10, y: 7, dir: 'down', name: '乡老', look: ELDER_LOOK, talk: ['玄德公，桃园外黄巾横行。', '先去医馆（门上挂绿牌）歇歇脚，受伤了就回来。', '深草里常有散兵游勇，打到兵力见底时丢出「招降令」，就能收为己用。'] },
  { id: 'kid', map: 'zhuo', x: 6, y: 13, dir: 'right', name: '村童', look: VILLAGER_LOOK, talk: ['五行相克你知道吗？', '金克木、木克土、土克水、水克火、火克金。', '用克制对方的招式，伤害翻倍！被克就只剩一半。'] },
  { id: 'hunter', map: 'zhuo', x: 16, y: 11, dir: 'left', name: '猎户', look: VILLAGER_LOOK, talk: ['草丛边缘走一走，遇敌更频繁。', '武将名牌左边的色块就是他的五行。'] },
  { id: 'doc1', map: 'taoyuan', x: 13, y: 4, dir: 'down', name: '随军郎中', look: HEALER_LOOK, heal: 1, talk: ['前方就是黄巾大营。来，我替你的将士包扎一下。'] },
  { id: 't1', map: 'taoyuan', x: 14, y: 11, dir: 'left', name: '黄巾兵', look: 'huangjin', sight: 4,
    trainer: { team: [['huangjin', 4], ['huangjin', 5]], gold: 120, pre: '苍天已死，黄天当立！', win: '大贤良师不会放过你的……' } },
  { id: 't2', map: 'taoyuan', x: 4, y: 18, dir: 'right', name: '黄巾头目', look: 'chengyuanzhi', sight: 4,
    trainer: { team: [['huangjin', 5], ['fangshi', 6]], gold: 180, pre: '此路是我开！', win: '好厉害……广宗的弟兄们会替我报仇！' } },
  { id: 't3', map: 'taoyuan', x: 16, y: 2, dir: 'down', name: '乡勇', look: 'xiangyong', sight: 0,
    trainer: { team: [['xiangyong', 6], ['gongshou', 6]], gold: 150, pre: '想投军？先过我这关！', win: '服了！前面那条路，桥北有郎中。' } },

  { id: 'g1', map: 'guangzong', x: 6, y: 4, dir: 'right', name: '黄巾力士', look: 'huangjin', sight: 4,
    trainer: { team: [['huangjin', 7], ['huangjin', 7]], gold: 200, pre: '闯营者死！', win: '顶、顶不住了……' } },
  { id: 'g2', map: 'guangzong', x: 5, y: 15, dir: 'right', name: '人公将军', look: 'zhangliang', sight: 5,
    trainer: { team: [['huangjin', 7], ['zhangliang', 9]], gold: 300, pre: '我乃人公将军张梁！', win: '大哥……快走……' } },
  { id: 'g3', map: 'guangzong', x: 15, y: 4, dir: 'left', name: '地公将军', look: 'zhangbao', sight: 4,
    trainer: { team: [['fangshi', 8], ['zhangbao', 9]], gold: 300, pre: '看我妖术！', win: '法术……竟不灵了？' } },
  { id: 'boss1', map: 'guangzong', x: 10, y: 1, dir: 'down', name: '大贤良师·张角', look: 'zhangjiao', sight: 3, boss: 1,
    trainer: { team: [['huangjin', 9], ['zhangbao', 10], ['zhangjiao', 12]], gold: 800, pre: '苍天已死，黄天当立！岁在甲子，天下大吉！', win: '黄天……终究是……' },
    after: ['黄巾之乱平定！', '北方传来消息：董卓入京，废立天子，各路诸侯在酸枣会盟。'] },

  { id: 'caocao', map: 'suanzao', x: 10, y: 7, dir: 'down', name: '曹操', look: { beard: 1, bc: H, hat: 'crown', hatC: '#1a1a1a', armor: '#2a2a4a', trim: '#e3b341' },
    talk: ['原来是破黄巾的刘玄德！', '北面汜水关由华雄把守，已斩我联军数员大将。', '这些拿去用。'], give: { hufu: 3, yao: 5 } },
  { id: 'yuanshao', map: 'suanzao', x: 14, y: 3, dir: 'down', name: '联军兵', look: VILLAGER_LOOK, talk: ['盟主袁本初整日饮宴……', '听说汜水关的华雄是火五行，用水克他！'] },
  { id: 't4', map: 'suanzao', x: 15, y: 15, dir: 'left', name: '西凉斥候', look: 'youxia', sight: 5,
    trainer: { team: [['gongshou', 11], ['youxia', 12]], gold: 300, pre: '联军的探子？拿下！', win: '回去报告华雄将军！' } },
  { id: 't5', map: 'suanzao', x: 6, y: 20, dir: 'right', name: '西凉兵', look: 'huzhen', sight: 5,
    trainer: { team: [['youxia', 12], ['xiangyong', 12], ['fangshi', 13]], gold: 320, pre: '杀！', win: '撤！' } },

  { id: 'doc2', map: 'sishui', x: 11, y: 13, dir: 'down', name: '随军郎中', look: HEALER_LOOK, heal: 1, talk: ['关内全是西凉精兵，先养足精神。'] },
  { id: 's1', map: 'sishui', x: 4, y: 5, dir: 'right', name: '西凉校尉', look: 'huzhen', sight: 5,
    trainer: { team: [['gongshou', 13], ['huzhen', 14]], gold: 400, pre: '汜水关岂容你撒野！', win: '将军……会为我报仇……' } },
  { id: 's2', map: 'sishui', x: 15, y: 8, dir: 'left', name: '骑都尉·李肃', look: 'lisu', sight: 5,
    trainer: { team: [['lisu', 14], ['gongshou', 14]], gold: 400, pre: '有勇无谋之辈！', win: '失策了……' } },
  { id: 'boss2', map: 'sishui', x: 9, y: 2, dir: 'down', name: '都督·华雄', look: 'huaxiong', sight: 3, boss: 1,
    trainer: { team: [['huzhen', 15], ['lisu', 15], ['huaxiong', 18]], gold: 1200, pre: '又来一个送死的！报上名来！', win: '温酒……尚未凉……' },
    after: ['斩华雄于汜水关下！', '前方虎牢关，据说镇守的是天下无双的——吕布。'] },

  { id: 'doc3', map: 'hulaodao', x: 11, y: 3, dir: 'down', name: '随军郎中', look: HEALER_LOOK, heal: 1, talk: ['吕布是金五行，火克金。多带几员火将。'] },
  { id: 't6', map: 'hulaodao', x: 7, y: 12, dir: 'right', name: '并州骑兵', look: 'youxia', sight: 2,
    trainer: { team: [['youxia', 17], ['gongshou', 17]], gold: 450, pre: '温侯麾下，岂有弱兵！', win: '快马……回报……' } },
  { id: 't7', map: 'hulaodao', x: 12, y: 7, dir: 'left', name: '陷阵营', look: 'gaoshun', sight: 3,
    trainer: { team: [['gaoshun', 18]], gold: 500, pre: '陷阵之志，有死无生！', win: '……' } },

  { id: 'doc4', map: 'hulao', x: 11, y: 13, dir: 'down', name: '随军郎中', look: HEALER_LOOK, heal: 1, talk: ['当心！关内是吕布亲军！'] },
  { id: 'h1', map: 'hulao', x: 4, y: 5, dir: 'right', name: '张辽', look: 'zhangliao', sight: 5,
    trainer: { team: [['zhangliao', 20], ['gongshou', 19]], gold: 600, pre: '雁门张文远在此！', win: '好身手。' } },
  { id: 'h2', map: 'hulao', x: 15, y: 8, dir: 'left', name: '陈宫', look: 'chengong', sight: 5,
    trainer: { team: [['gaoshun', 20], ['chengong', 21]], gold: 600, pre: '温侯若听我计，岂有今日。', win: '天意如此。' } },
  { id: 'boss3', map: 'hulao', x: 9, y: 2, dir: 'down', name: '温侯·吕布', look: 'lvbu', sight: 3, boss: 1,
    trainer: { team: [['zhangliao', 21], ['chengong', 22], ['gaoshun', 22], ['lvbu', 25]], gold: 2000, pre: '三姓家奴？谁敢这么叫我！来战！', win: '哼……今日就到这里！' },
    after: ['三英战吕布，吕布败走！', '董卓挟天子逃往洛阳。直捣相国府！'] },

  { id: 'ly1', map: 'luoyang', x: 6, y: 11, dir: 'right', name: '百姓', look: VILLAGER_LOOK, talk: ['董太师把洛阳搜刮一空……', '城南深草里据说出没过卧龙先生。'] },
  { id: 'boss4a', map: 'luoyang', x: 9, y: 7, dir: 'down', name: '谋士·李儒', look: 'liru', sight: 3, boss: 1,
    trainer: { team: [['lijue', 24], ['guosi', 24], ['liru', 26]], gold: 1500, pre: '相国府岂是你能进的！', win: '太师……快走……' } },
  { id: 'boss4', map: 'luoyang', x: 9, y: 4, dir: 'down', name: '相国·董卓', look: 'dongzhuo', sight: 2, boss: 1,
    trainer: { team: [['lijue', 26], ['guosi', 26], ['liru', 27], ['dongzhuo', 30]], gold: 5000, pre: '织席贩履之徒，也敢来犯我！', win: '奉先……奉先何在……' },
    after: ['讨董成功！天下暂定。'], ending: 1 },
];
